const uz = [
  "qo'rqmoq",
  "rozi bo'lmoq",
  'jahlda',
  'yetib kelmoq',
  'hujum qilmoq',
  'tagi  osti',
  'aqlli',
  'shafqatsiz',
  'nihoyat',
  'yashirmoq',
  'ovlamoq',
  "ko'p",
  "o'rta",
  'lahza',
  'mamnun',
  "va'da bermoq",
  'javob bermoq',
  'xavfsiz',
  'hiyla',
  'yaxshi',
  'sarguzasht',
  'yaqinlashmoq',
  'ehtiyotkorlik bilan',
  'kimyoviy',
  'yaratmoq',
  'yomonlik',
  'tajriba',
  "o'ldirmoq",
  'laboratoriya',
  'kulmoq',
  'baland ovozda',
  'asabiy',
  'shovqin',
  'loyiha',
  "qo'rqitmoq",
  'sir',
  'baqirmoq',
  'hid',
  "qo'rqinchli",
  'yomonroq',
  'begona',
  'orasida',
  'grafik  jadval',
  'bulut',
  'tushunmoq',
  "ta'riflamoq",
  "qachon bo'lsa ham",
  'muvaffaqiyatsizlikka uchramoq',
  "do'stona",
  'baho',
  "o'rniga",
  'kutubxona',
  'sayyora',
  'hisobot',
  'bir nechta',
  'hal qilmoq',
  "to'satdan",
  'faraz qilmoq',
  'olam',
  "ko'rinish",
  'muvofiq',
  'oldini olmoq  saqlanmoq',
  "o'zini tutmoq",
  'sokin',
  'tashvishlanmoq',
  'mamnun',
  'kutmoq',
  'tez-tez',
  'odat',
  "ko'rsatma bermoq",
  'masala',
  'hech biri',
  'sabrli',
  'ijobiy',
  'jazolamoq',
  'vakillik qilmoq',
  'silkitmoq',
  'tarqalmoq',
  'sayrga chiqmoq',
  'qishloq',
  'xabardor',
  'yomon',
  "tegishli bo'lmoq",
  'davom etmoq',
  'xato',
  'tajriba',
  'maydon',
  'jarohat olmoq',
  'hukm  baho',
  'ehtimol',
  'oddiy',
  'noyob',
  'rohatlanmoq',
  "so'ramoq",
  'yashamoq',
  'natija',
  'dumalamoq',
  'chunki',
  "ko'rinadigan",
  'yovvoyi',
  'afzallik',
  'sababi',
  'tanlov',
  'jamoa',
  "o'lik",
  'masofa',
  'qochmoq',
  'yuz',
  'amal qilmoq  ortidan bormoq',
  "qo'rquv",
  'arvoh',
  'shaxs',
  'uy hayvoni',
  'erishmoq  yetib bormoq',
  'qaytmoq',
  'omon qolmoq',
  'xafa',
  'ovoz',
  'ob-havo',
  'dono',
  'ruxsat bermoq',
  "e'lon qilmoq",
  'yonida',
  'qiyinchilik',
  'takidlamoq',
  'holat',
  "hissa qo'shmoq",
  'farq',
  "bo'lmoq",
  'mutaxassis',
  'mashhur',
  'kuch',
  'zarar',
  'yoymoq',
  'tinchlik',
  'shahzoda',
  'himoya qilmoq',
  "ma'no",
  "to'satdan",
  'shuning uchun',
  'qabul qilmoq',
  'tartibga solmoq',
  'qatnashmoq',
  'muvozanat',
  'farq',
  "rag'batlantirmoq",
  'tanish',
  'changallamoq',
  "osib qo'y",
  'katta',
  'zarur',
  'naqsh  tartib',
  'taklif qilmoq',
  'maqsad',
  'ozod qilmoq',
  'talab qilmoq',
  'yakka',
  'muvaffaqiyat',
  "ko'z yoshi  yirtmoq",
  'nazariya',
  'qarshi',
  'sohil',
  'zarar',
  'kashf qilmoq',
  'hissiyot',
  'tuzatmoq',
  'samimiy',
  'aniqlash',
  'orol',
  'okean',
  'ehtimol',
  'yoqimli',
  'oldini olmoq',
  'tosh',
  'asramoq',
  'qadam',
  'hali ham',
  "ta'm  tatib ko'rmoq",
  'otmoq',
  "to'lqin",
  'foyda',
  'aniq',
  'imkoniyat',
  "ta'sir",
  'muhim',
  'uzoq',
  'diqqat markazi',
  'vazifa',
  "o't",
  "qo'riqchi",
  'rasm',
  'darhol',
  'asosiy',
  "mag'rur",
  'qolmoq',
  'dam olmoq  qolgan',
  'alohida',
  'sayt  joy',
  'dum',
  'muammo',
  'endi  qaytib',
  'uyquda',
  'maymunjon',
  "to'plamoq",
  'raqobatlashmoq',
  'suhbat',
  'jonzot',
  'qaror',
  'yoki',
  "o'rmon",
  'yer',
  'tanishtirmoq',
  'turmush qurmoq',
  'tayyorlamoq',
  'suzmoq',
  'jiddiy',
  'sarflamoq',
  "g'alati",
  'haqiqat',
  "uyg'otmoq",
  "yolg'iz",
  'xonadon',
  'maqola',
  'rassom',
  'munosabat',
  'solishtirmoq',
  'hukm qilmoq',
  'jurnal',
  'ashyo',
  'ovqat',
  'uslub',
  "qo'shni",
  'professional',
  'foyda',
  'sifat',
  'shakl',
  "bo'shliq",
  'zina',
  'belgi',
  'oriq',
  'qon',
  'kuymoq',
  'hujayra  panjara',
  "o'z ichiga olmoq",
  "to'g'ri",
  'ekin',
  'talab',
  'teng',
  'boqmoq',
  'teshik',
  "o'smoq",
  'lord',
  'qarzdor',
  'orin',
  'oshirmoq',
  "mas'ul",
  "ko'rish",
  'dog`  joy',
  'tuzilish',
  'butun',
  'murabbiy',
  'boshqaruv',
  'tushuntirish',
  "to'g'ridan-to'g'ri",
  'imtihon',
  'misol',
  'chegara',
  'mahalliy',
  'sehrli',
  'pochta',
  'roman',
  'reja',
  'shoir',
  'bosib chiqarmoq',
  'sahna',
  'varoq',
  'ahmoqona',
  "do'kon  saqlamoq",
  'azoblanmoq',
  'texnologiya',
  'kesib',
  'nafas olmoq',
  'xususiyat',
  "iste'mol qilmoq",
  'hayratlanmoq',
  'haddan tashqari',
  "qo'rquv",
  'baxtli',
  "sodir bo'lmoq",
  'uzunlik',
  'xato',
  'kuzatmoq',
  'imkoniyat',
  'sovrin',
  'irq',
  'tushunmoq',
  'javob bermoq',
  'xavf',
  'hayron bo`lmoq',
  'hali',
  'akademiya',
  'qadimiy',
  'taxta',
  'asr',
  'qo`shimcha ma`lumot',
  'kontsert',
  'graflik',
  "lug'at",
  'mavjud',
  'tekis',
  'jentleman',
  'maxfiy',
  'balki',
  'ofitser',
  'original',
  'funt  qoqmoq',
  'jarayon',
  'nashr etmoq',
  'teatr',
  'boylik',
  'qadrlamoq',
  'mavjud',
  'urmoq',
  'yorqin',
  'nishonlamoq',
  'aniqlamoq',
  "yo'qolmoq",
  'yana boshqa',
  'adolatli',
  'oqim',
  'oldinga',
  'tepalik',
  'daraja',
  "yolg'iz",
  "ko'lmak",
  'javob',
  'mavsum',
  'yechim',
  'chiqindi',
  'mi yoki',
  'bahslashmoq',
  'muloqot qilmoq',
  'olomon',
  'qaram bo`lmoq',
  'ovqat',
  "bo'sh",
  'aniq',
  'yangi',
  "to'plamoq",
  'ko`rsatmoq',
  'buyum',
  'taklif qilmoq',
  'narx',
  'mahsulot',
  'mulk',
  'sotib olmoq',
  'tavsiya qilmoq',
  'tanlamoq',
  'asbob',
  "davolamoq  munosabatda bo'lmoq",
  'tirik',
  'suyak',
  'bezovta qilmoq',
  'kapitan',
  'xulosa',
  'shubha',
  'kashf qilmoq',
  'xorijiy',
  'mamnun',
  'biroq',
  'adolatsizlik',
  'xalqaro',
  'yurist',
  'eslatmoq',
  'siyosat',
  'ijtimoiy',
  'nutq',
  'xodimlar',
  'tomonga',
  "yog'och",
  'erishmoq',
  'maslahat bermoq',
  'allaqachon',
  'asosiy',
  "bo'lak",
  "o'ylab ko'rmoq",
  "yo'q qilmoq",
  "ko'nglini ko'tarmoq",
  "qo'shimcha",
  'maqsad',
  "yolg'on gapirmoq",
  "go'sht",
  'fikr',
  'haqiqiy',
  'aks ettirmoq',
  'deb bilmoq',
  'xizmat qilmoq',
  'sabzavot',
  'urush',
  'qiymat',
  "paydo bo'ladi",
  'tayanch',
  'miya',
  'martaba',
  'xizmatchi',
  'harakat',
  'kirmoq',
  'ajoyib',
  'qahramon',
  'shoshilmoq',
  'axborot bermoq',
  'keyinchalik',
  'tashlab ketmoq',
  'topmoq',
  'hamshira',
  'operatsiya',
  "og'riq",
  'rad qilmoq',
  'garchi',
  'turli',
  'dolzarb  haqiqiy',
  'hayratlantirmoq',
  'zaryadlash',
  'farovonlik',
  'aloqa qilmoq',
  'mijoz',
  'yetkazib bermoq',
  'ishlab topmoq',
  'darvoza',
  "qo'shib qo'ymoq",
  'boshqarmoq',
  'sinoat',
  'uchramoq',
  'aks  qarama-qarshi',
  'likop',
  'qabul qilmoq',
  'sovrin',
  "qo'ymoq  o'rnatmoq",
  "o'g'irlamoq",
  "o'g'ri",
  'odimlamoq',
  'sportchi',
  "o'rtacha",
  'hatti-harakat',
  'orqasida',
  "yo'nalish  kurs",
  'pasaytirmoq',
  "o'yin",
  "a'zo",
  'aqliy',
  "yo'lovchi",
  'shaxsiyat',
  "she'r",
  'qutb  asos',
  'olib tashlash',
  'xavfsizlik',
  'otmoq',
  'ovoz',
  'suzmoq',
  "o'rgimchak to'ri",
  "bo'lak",
  'hayqiriq',
  'murakkab',
  'tanqidchi',
  'voqea',
  'mashq qilmoq',
  'mos kelmoq',
  "do'stlik",
  "yo'l ko'rsatuvchi",
  'kamchilik',
  "yo'lak",
  'ijro etmoq',
  'bosim',
  'ehtimol',
  'jamoat',
  'urmoq',
  "qo'llab-quvvatlamoq",
  'vazifa',
  'muddat',
  'birlashtirmoq',
  "bog'lamoq",
  'atrof-muhit',
  'zavod',
  'xususiyat',
  'misol',
  "mashg'ul bo'lmoq",
  'dori',
  'aralashtirmoq',
  'tashkillashtirmoq',
  'davr',
  'yashamoq',
  'ishlab chiqarmoq',
  'bir qator  tur',
  'tanimoq',
  'muntazam',
  'belgi',
  'uch',
  "an'ana",
  'axlat',
  'keng',
  'maslahat',
  'davomida',
  'diqqat',
  'jalb qilmoq',
  "ko'tarilmoq",
  'tomchi',
  'oxirgi',
  'uzoqroq',
  'shama qilmoq',
  'saqlamoq',
  'na',
  'aks holda',
  'jismoniy',
  'isbotlamoq',
  'javob bermoq',
  'uchmoq',
  'joylashgan',
  'jamiyat',
  'standart',
  'taklif qilmoq',
  'aslida',
  'luqma  tishlamoq',
  "qirg'oq",
  'kelishuv',
  "cho'l",
  'zilzila',
  'samarali',
  "o'rganmoq",
  "noto'g'ri",
  "sovg'a",
  'ochlik',
  'tasavvur qilmoq',
  'sayohat',
  'jumboq',
  'biroz  ancha',
  "maqul ko'rmoq",
  "o'ziga xos",
  'sayohat',
  'safar',
  'qiymat',
  'musiqiy guruh',
  "zo'rg'a",
  'zerikarli',
  'bekor qilmoq',
  "yo'lak",
  'axlat',
  'asbob',
  "ro'yxat",
  'sehrli',
  'xabar',
  'payqamoq',
  "ega bo'lmoq",
  'taxmin qilmoq',
  'professor',
  'shoshilmoq',
  'jadval',
  'ulashmoq',
  'bosqich',
  "bo'ron",
  'ichida',
  'reklama qilmoq',
  'tayinlamoq',
  'tomoshabin',
  'nonushta',
  'musobaqa',
  'salqin  ajoyib',
  "erishmoq  ega bo'lmoq",
  'ahamiyat',
  'bilim',
  'katta',
  'anglatmoq',
  "afzal ko'rmoq",
  'prezident',
  'taraqqiyot',
  'hurmat',
  'boy',
  'qobiliyat',
  "qandaydir yo'l bilan",
  'kuch-quvvat',
  'ovoz bermoq',
  'yuqorida',
  'oldinga',
  'miqdor',
  "e'tiqod",
  'markaz',
  'umumiy',
  'xarajat',
  'namoyish qilmoq',
  'turli',
  'dalillar',
  'halollik',
  'ibora',
  'mustaqil',
  'ichida',
  'usta',
  'xotira',
  "to'g'ri",
  "ko'rmoq",
  "bo'lim",
  'sirt',
];
