const uz2 = [
  'tashvishli',
  'dahshatli',
  'tashkil topmoq',
  'xohish',
  'ishtiyoqmand',
  'uy-joy',
  'niyat',
  'manzara',
  "ko'tarmoq",
  'yuk',
  "o'pka",
  'harakat',
  'tezligi',
  'muloyim',
  "ega bo'lmoq",
  'tezda',
  'eslatma',
  'izlash',
  'porlash',
  "to'kmoq",
  'olib kelmoq',
  "qal'a",
  'buyruq bermoq',
  'maslahat bermoq',
  'ishonch xosil qilmoq',
  'portlash',
  'zargarlik buyumlari',
  'yer',
  'meteor',
  'mahluq',
  'shimoliy',
  'uzoq',
  'Janubiy',
  'haykal',
  "bug '",
  'taqdim etmoq  amal qilmoq',
  'ibodatxona',
  'yuqori',
  "o't",
  'qanot',
  "o'q",
  'jang',
  'kamon',
  'jasur',
  'boshliq',
  'zararli tomoni',
  'dushman',
  'Kirish',
  'kamdan-kam',
  'niyat qilmoq',
  'kulgu',
  "jurnal  yog'och",
  'harbiy',
  'itoat qilmoq',
  "xavfsiz,  qo'lga kiritmoq",
  'barqaror',
  'ishonch',
  "o'ramoq",
  'agar ...masa',
  'qurol',
  "ko'krak",
  'ishonch',
  'oqibat  natija',
  'falokat',
  'bezovta qilmoq',
  'baholamoq',
  'hurmat',
  'taassurot qoldirmoq',
  'marafon',
  'tor',
  'rangsiz',
  "qo'pol",
  'qoniqtirmoq',
  'qichqirmoq',
  'tasirchan',
  'soya',
  "qo'shimcha",
  'daxshat',
  'tahdid',
  'qurbon',
  'ajdod',
  'burchak',
  'yuklash',
  'chegara',
  'tabriklamoq',
  'ramka',
  'jannat',
  'ajoyib',
  'afsona',
  'Maqtov',
  'davom etmoq',
  'sof  toza',
  'nisbiy  qarindosh',
  'katta',
  'jim  tinch',
  "cho'kmoq",
  'ustun  katta',
  "o'rab olmoq",
  'qalin',
  "o'ramoq",
  'chet el',
  "g'azab",
  'kelin',
  'qisqacha',
  'ketidan quvmoq',
  "ko'nglini qoldirmoq",
  "sho'ng'imoq",
  'almashtirmoq',
  'yaxshilik',
  'haq',
  'abadiy',
  'yigit',
  'ajoyib',
  'kayfiyat',
  'saroy',
  'ruxsat bermoq',
  'norozilik qilmoq',
  'haykal',
  'qabila',
  'yoshlar',
  'asos',
  'biologiya',
  'qafas',
  'hamkasb',
  'koloniya',
  'munozara',
  'ketmoq',
  'tushkunlikka solmoq',
  'Haqiqiy',
  'hayratda qoldirmoq',
  'missiya',
  'Shunga qaramay',
  'istilo  kasb',
  'dengiz orti',
  'ishontirmoq',
  "yo'nalish",
  'xarobalar',
  'olim',
  'muhim',
  'vulqon',
  'keng',
  'buta',
  'qobiliyatli',
  "mug'ombirlik qilmoq",
  'fikrni jamlamoq',
  'xulosa qilmoq',
  "o'ziga ishongan",
  'sezilarli',
  'yetkazmoq',
  'aniq',
  'zavq',
  'manzil',
  'aytib turmoq',
  'chet  qirra',
  "yo'l",
  'suyanmoq',
  'soya',
  'muvaffaqiyatga erishmoq',
  'gumon qilmoq',
  'vodiy',
  'hurmat qilmoq',
  'yordam',
  'urinish',
  'hokimiyat',
  'poytaxt',
  'hamkorlik qilmoq',
  'himoya qilmoq',
  'vayrongarchilik',
  'tartibsizlik',
  "bo'linish",
  'imkon bermoq',
  "ko'nglini qoldirmoq",
  'boshqarmoq',
  "mo'l",
  'xalos qilmoq',
  "obro'",
  'qirollik',
  'qul',
  'kurash',
  'ahmoqona',
  'fuqaro',
  'kengash',
  "e'lon qilmoq",
  'ulkan',
  'noodatiy',
  'tuman',
  'dafn marosimi',
  'ulkan',
  'taassurot',
  'daromadlar',
  'Telba',
  'kerak',
  "qarshilik ko'rsatmoq",
  'oshkor qilmoq',
  'qutilmoq',
  'qilich',
  'hikoya',
  'tuzoq',
  'sud',
  "zo'ravonlik",
  'ruxsat',
  'astronomiya',
  'ayblamoq',
  'kimyo',
  'qaramasdan',
  'dinozavr',
  "ko'rgazma",
  'shuhrat',
  "ob-havo ma'lumoti",
  'daho',
  'muloyim',
  'geografiya',
  'aralashmoq',
  'engil',
  'asosiy  direktor',
  'qator',
  'tokcha',
  'ataylab',
  'ajoyib',
  'nam',
  'ozor yetkazmoq',
  'qurbi yetmoq',
  'pishirmoq',
  'loviya',
  'sham',
  "o'zgartirmoq",
  'qarz',
  'kamaymoq',
  'xato',
  "jamg'arma",
  'saxiy',
  'ingredient',
  'turib olmoq',
  'tartibsizlik',
  'metall',
  'kuzatmoq',
  "qarshilik ko'rsatmoq",
  'sust',
  'miqdor',
  'sudga bermoq',
  'tashvish',
  'armiya',
  'milliard',
  "o'ymoq",
  'maslahatlashmoq',
  'favqulodda holat',
  'boylik  omad',
  'kafolat bermoq',
  'yurish',
  "boshlang'ich",
  "qizg'in  kuchli",
  'qarz berish',
  "cho'qqi",
  'ehtimoliy',
  "g'urur",
  'dalil',
  'chiqish',
  'aylantirmoq',
  'kichik',
  "o'qituvchi",
  'aniq',
  "ko'r",
  'hisoblmoq',
  'suhbat',
  'ahd qilmoq',
  'tuzmoq',
  'yotoqxona',
  'holdan toymoq',
  'issiqxona',
  "e'tibor bermaslik",
  'aniq',
  'fizika',
  'qism',
  'Eslatmoq',
  'kotib',
  'jiddiy',
  "iste'dod",
  'maqola',
  'forma',
  "ko'rish",
  'shimib olmoq',
  "xo'jayin",
  "Qo'mita",
  'shartnoma',
  'jamoa',
  "bag'ishlamoq",
  'qazimoq',
  'Ovqatlanmoq',
  'ehson qilmoq',
  'ikki karra',
  "ko'tarmoq",
  'lazzat',
  'asos',
  'avlod',
  'dastak',
  'qatlam',
  'loy',
  'silliq',
  'tuproq',
  "noyob  o'zgacha",
  'xujra',
  'inkor qilish',
  'hujjat',
  "ta'kidlab o'tish kerakki",
  'isitma',
  'gripp',
  'muzlatish',
  'imo-ishora',
  "gapni bo'lmoq",
  'oxirgi',
  "o'xshashlik",
  'Bundan tashqari',
  'kuzatasiz',
  'oqilona',
  'tiklash',
  'tayanmoq',
  'zarba',
  'uyatchang',
  'tikilmoq',
  'Shunday qilib',
  'maqsad',
  'ulamoq',
  'tikish',
  'arava',
  'mumtoz',
  'borib kelmoq',
  'tasdiqlamoq',
  'tanqid qilmoq',
  'farq qilmoq',
  'xarajatlar',
  'rasmiy',
  'balandlik',
  'ixtiro qilmoq',
  'kichik',
  'mehnat',
  'mexanik',
  'asosiy',
  "o'zgarish",
  'belgi',
  'samimiy',
  'qobiliyat',
  "qishloq xo'jaligi",
  'multfilm',
  'shift',
  'ishontirmoq',
  'qiziquvchan',
  'kechiktirmoq',
  'kundalik',
  'element',
  'iymon',
  'don',
  'salomlashmoq',
  'tekshirmoq',
  'quvonch',
  'yorliq',
  'rohib',
  "g'alati",
  "to'xtatib turmoq",
  'ruhoniy',
  'kasb',
  'astronavt',
  "uyg'oq",
  'jasorat',
  'suzmoq',
  'taqdim etmoq',
  'tortish kuchi',
  'qimmatbaho tosh',
  'konchi',
  'mineral',
  'ishtirok etish',
  'ruxsat',
  'quymoq',
  'mavjudlik',
  'xom',
  "sun'iy yo'ldosh",
  "ko'lam",
  "o'tkazib yuborish",
  "cho'zmoq",
  'teleskop',
  'yer osti',
  'ogohlantiruvchi ovoz',
  'alohida  ayro',
  'hibsga olish',
  'mukofot',
  'zot',
  'paqir',
  'tanlov',
  'aybdor deb topmoq',
  'garaj',
  'jurnalist',
  'it bolasi',
  'mos kelmoq',
  "ta'mirlamoq",
  'davom ettirmoq',
  'tunab ketmoq',
  'toyib ketmoq',
  'nimagadir',
  'barqaror',
  "to'qima  salfetka",
  'hovli',
  'astronavt',
  "uyg'oq",
  'jasorat',
  'suzmoq',
  'taqdim etmoq',
  'tortish kuchi',
  'qimmatbaho tosh',
  'konchi',
  'mineral',
  'ishtirok etish',
  'ruxsat',
  'quymoq',
  'mavjudlik',
  'xom',
  "sun'iy yo'ldosh",
  "ko'lam",
  "o'tkazib yuborish",
  "cho'zmoq",
  'teleskop',
  'yer osti',
  'ogohlantiruvchi ovoz',
  'alohida  ayro',
  'hibsga olish',
  'mukofot',
  'zot',
  'paqir',
  'tanlov',
  'aybdor deb topmoq',
  'garaj',
  'jurnalist',
  'it bolasi',
  'mos kelmoq',
  "ta'mirlamoq",
  'davom ettirmoq',
  'tunab ketmoq',
  'toyib ketmoq',
  'nimagadir',
  'barqaror',
  "to'qima  salfetka",
  'hovli',
  "o'xshash",
  "jig'iga tegmoq",
  'arxitektura',
  "sun'iy",
  'zanjir',
  'farqli',
  'ajratmoq',
  'chang',
  'hayajon',
  'tuzalmoq',
  'meros qilib olmoq',
  'ahloq  odob',
  'kuchaymoq',
  'tom',
  'kamchilik',
  'qattiq',
  "g'aram",
  'modda',
  'maqbara',
  'yara',
  'Vanna',
  'bukmoq',
  'chaynamoq',
  'nogiron',
  'ajoyib',
  "to'qima",
  'bayroq',
  'tekshirish',
  'jurnal',
  'suyuqlik',
  'ajoyibot',
  'ozuqa moddalari',
  'yengish',
  'eslatish',
  'afsuslanmoq',
  'ruh',
  'yetarli',
  'jarrohlik',
  'qiyin',
  'quvur',
  'tan olmoq',
  'idish',
  'kosa',
  'hujra',
  'naqd pul',
  'jinoyatchi',
  "o'nlab",
  'kattaroq',
  'yuzga oid',
  "to'siq",
  'ilhomlantirmoq',
  'biroz',
  'pokiza',
  'vaziyat',
  'jazo',
  "qo'pol",
  'joylashmoq',
  'transport vositasi',
  'hamyon',
  'baqirmoq',
  'ayblmoq',
  'sozlamoq',
  'qiziqtirmoq',
  'marjon',
  'paxta',
  "to'qnashmoq",
  'paluba',
  'jalb qilish',
  'firma',
  "yoqilg'i",
  'katta',
  "bo'ron",
  "yo'qotish",
  'tekis',
  'qoya',
  'yopish',
  "qat'iy",
  "to'lqinda uchmoq",
  'zona  hudud',
  "kechirim so'rash",
  'botir',
  'tutmoq',
  'asosiy',
  'gersog',
  "ta'sir ostida bo'lmoq",
  'aybdor',
  'ijaraga olish',
  'begunoh',
  'qamoqxona',
  'vazir',
  'oddiy',
  'doimiy',
  'himoya qilmoq',
  'talaffuz qilmoq',
  'aks etmoq',
  'belgi',
  'tamaki',
  'egizak',
  'jodugar',
  "hamroh bo'lmoq",
  "yalang'och",
  'shox',
  'nafas olish',
  "ko'prik",
  'uloqtirmoq',
  'jazm qilmoq',
  'elektron',
  'kichik mehmonxona',
  "to'r",
  'falsafa',
  'qozon',
  "urug'",
  "o'tkir",
  'tur',
  'ayirmoq',
  'qattiq',
  'haqiqiy',
  "o'lchamoq",
  'pichirlamoq',
  'mavhum',
  'yillik',
  'loy',
  'mato',
  'parda',
  'loyiq',
  'pat',
  'unumdor',
  'suv toshqini',
  'mebel',
  'qabr',
  'ideal',
  'idrok',
  'shu kunlarda',
  'olmoq',
  'diniy',
  'ishqiy',
  'qobiq',
  "qirg'oq",
  "g'ildirak",
  "o'ziga tortmoq",
  'faraz qilmoq',
  'qarz olmoq',
  'mijoz',
  'shahar markazi',
  'zerikarli',
  'uyatga qildirmoq',
  "haq  to'lov",
  'sobiq',
  'formula',
  'tashkil qilmoq',
  'sarmoya tikmoq',
  'qarz',
  'amaliy',
  'chorak',
  'ish haqi',
  'stipendiya',
  'vaqtinchalik',
  'xazina',
  "da'vat qilmoq",
];
