const uz3 = [
  'yuzaga kelmoq',
  "ko'mak beruvchi",
  'temirchi',
  "ochiqqo'l",
  "mo'ri",
  'qoplamoq',
  'duch kelmoq',
  'oshib ketmoq',
  'shakllantirmoq',
  'kamtarin',
  'temir',
  'narvon',
  'kamtarin',
  "ishg'ol qilmoq",
  'chaqa',
  'voizlik qilmoq',
  'muvaffaqiyatga erishmoq',
  'viloyat',
  'mamnuniyat',
  'davom ettirmoq',
  "ega bo'lmoq",
  'noqulay',
  'enaga',
  'aldash',
  'tushkunlikka solmoq',
  'soxta',
  'nafrat',
  'kulba',
  'past',
  'kulba',
  'beparvolik qilmoq',
  'yangi kelgan',
  'jinoyat',
  "e'tiborsizlik",
  'qaytarish',
  'kulgili',
  'qoniqarli',
  "cho'pon",
  'oshiqmoq',
  "bug'doy",
  "tor ko'cha",
  'bolta',
  'dasta shingil',
  'majburyat',
  'yaxshi',
  'sharmandalik',
  'tirsak',
  'minnatdor',
  'jaxlini chiqarmoq',
  'bola',
  "bo'sh mustahkam emas",
  'xafa qilmoq',
  'kechki paytda',
  'davom etmoq',
  "qarag'ay",
  'chandiq',
  'hissiyot',
  'chana',
  'masxara qilmoq',
  "shaydo bo'lmoq",
  'gullamoq',
  'ixcham',
  'jingala',
  'parchalanish',
  'shirinlik',
  'botirmoq',
  'uzoq',
  'tutilish',
  'farishta',
  'viqor',
  'dam olish',
  'insoniyat',
  'ehtiros',
  'yostiq',
  'zarba',
  'yangilash',
  'aksirmoq',
  'ziravorlar',
  'hushtak',
  'jun',
  'tanishmoq',
  'qabriston',
  "la'natlamoq",
  'niqob',
  'noodatiy',
  'chiroq',
  'palpoq',
  'yashovchi',
  'oziqlantirish',
  'qaroqchi',
  'nashr',
  'topishmoq',
  'chirimoq',
  "qo'rqitmoq",
  'qisqa vaqt ichida',
  'skelet',
  'buzilmoq',
  'och qolmoq',
  'qiziqish',
  'yomon',
  'ogohlantirmoq',
  'eshittirish',
  'xabarnoma',
  "do'ng bo'rtgan joy",
  "bo'laklamoq",
  'shkaf',
  'yupatmoq',
  'tuman',
  'tortma',
  'chidamoq',
  'qatl qilmoq',
  'mahkam tutmoq',
  'orqa',
  'senator',
  'bosh suyagi',
  'aralashtirmoq',
  'bosmoq',
  'ulkan',
  'ostida',
  'qurt',
  'tark etmoq',
  'shijoatli',
  'vovullamoq',
  "qo'ltiq",
  'aqilli',
  "jag'",
  'shikoyat',
  'kar',
  "g'ayratli",
  'ekspeditsiya',
  'ufq',
  'sodiq',
  'shahar hokimi',
  "o'zaro",
  'semiz',
  'boshpana',
  'tiklash',
  'ishqalamoq',
  'hislar',
  'veterinar',
  'yilligi',
  'arifmetik',
  'uyatli',
  'portlash',
  'duradgor',
  "ko'mir",
  'divan',
  'tomchilamoq',
  'bashang',
  'mato',
  "tog'li hududlar",
  'fil suyagi',
  'tegirmon',
  'igna',
  'jilo bermoq',
  'tikmoq',
  'omborxona',
  'ip',
  'tartibga solmoq',
  'yuqoriga',
  'ozor bermoq',
  'ittifoqchi',
  'maqtanmoq',
  'dukkilamoq',
  'bezori',
  'karbongidrat',
  'emaklamoq',
  "mag'lubiyat",
  'terish',
  'dominant',
  'rahmdillik',
  'bosh qimirlatmoq',
  'raqib',
  'janjallashmoq',
  'raqib',
  "og'riq",
  'nish chaqmoq',
  'tirishmoq',
  'qiynoq',
  'kurashmoq',
  "yo'qlik",
  'ovoz chiqarib',
  'kal',
  "ko'rpa",
  "o'rmalamoq",
  'ajrashmoq',
  'taqlid qilish',
  'chaqaloq',
  "o'g'irlash",
  "mizg'ish",
  'hech qayerda',
  'ohista urmoq',
  'yengillik',
  'nusxa yasamoq',
  'qofiya',
  "so'rmoq",
  'shoshilinch',
  "yo'qolmoq",
  'aravacha',
  'ajin',
  'noodatiy',
  'bambuk',
  'gullamoq',
  'kompas',
  'lahja',
  "yolg'onchi",
  'mitti',
  'ekosistema',
  'ayanchli',
  'sabrsiz',
  'yaproq',
  "qo'lyozmasi",
  'yaylov',
  'sabr-toqat',
  'atir',
  'hovuz',
  'maqola',
  "ta'qib qilish",
  'takrorlamoq qaytarmoq',
  'biyobon',
  'oldindan bilmoq',
  'bochka',
  'nur',
  'oddiy',
  'ehtiyotkorlik',
  'teskari',
  'qasddan atay',
  'suyuqlikda erimoq',
  'portlamoq',
  "bog'lamoq",
  'mikrob',
  "to'plam",
  'tutun',
  'latta',
  'sochmoq',
  'hid',
  "po'lat",
  'tezkor',
  'otmoq tashlamoq',
  "g'alaba",
  'bortda',
  'achchiq',
  "o'q",
  'shayton',
  'siljimoq',
  'majburlash',
  'fontan',
  'bandargoh',
  'yashamoq',
  'qadam tashlamoq',
  'millioner',
  'port',
  'sherif',
  "cho'chimoq",
  'terlamoq',
  'tepki',
  'birlashtirmoq',
  'kema',
  'sayohat',
  'ibodat qilmoq',
  'shogird',
  'ishontirmoq',
  'bint',
  'qonamoq',
  "bog'lanmoq",
  'oshpaz',
  'toj',
  'ketish',
  'mehnatsevar',
  'imperator',
  'tola',
  'dahshatli',
  "qo'pol",
  'tizzalamoq',
  'hashamat',
  'katta',
  'vahima',
  'ustuvorlik',
  'xalat',
  'tanbeh bermoq',
  'munosabat',
  "yig'ilish",
  'yorlaqamoq',
  'don',
  'quvnoq',
  'diametr',
  'majburiy ishlatmoq',
  'ochlik',
  'hosil',
  'xushchaqchaq',
  "yong'oq",
  'afv etish',
  "Fir'avn",
  'pishgan',
  'qovurilgan',
  'muntazam',
  'sxema',
  'nozik',
  'pechka',
  "o'g'irlik",
  "o'smir",
  'qobiliyat',
  'iltifot',
  "to'siq qo'yish",
  'jurnalistika',
  "hakamlar hay'ati",
  'adolat',
  'ozodlik',
  'adabiy',
  'dori darmon',
  'hapdori',
  'taxmin qilish',
  'maxfiylik',
  'jazo',
  'aqlli',
  'tilim',
  "qayg'u",
  'somon',
  'shishmoq',
  'toza',
  'muhabbat',
  'agentlik',
  'kul',
  'saqlamoq',
  'olib tashlamoq',
  'otilmoq',
  'taqdir',
  'lava',
  'bechora',
  'boshqarmoq',
  'kelib chiqmoq',
  'qoldiq',
  'topib kelmoq',
  'sayoz',
  'qiyalik',
  'kenglik',
  'insu-jins xurofot',
  'hamdartlik achinish',
  'tebranmoq',
  "sang'imoq",
  'zirh',
  "portlamoq (ko'rinish)",
  'portlamoq (ovoz)',
  'qoya',
  'alanga',
  'mustaqillik',
  'bosqin',
  'ritsar',
  'chaqmoq',
  'isyonchi',
  'chekinmoq',
  'inqilob',
  'nayza',
  'tik',
  "cho'qqi",
  'momaqaldiroq',
  'askarlar',
  'jangchi',
  'olib tashlamoq',
  "yo'l bermoq",
  "o'rindiq",
  'qarshi turmoq',
  'moychechak',
  'kelishmovchilik',
  'dahshat',
  'hodisa',
  'tuman',
  "ob'ekt",
  'etim',
  'reja',
  'homilador',
  "g'azab",
  'intiqom',
  'sharmandalik',
  "xo'rsinmoq",
  'sezdirmasdan yurmoq',
  'ortiqcha',
  'tana',
  'kechki ovqat',
  'yumshoq',
  'ostida',
  'kub',
  'tong',
  'qoniqmagan',
  'yengillik',
  'aniq',
  "do'l",
  'uvullamoq',
  'sakrash',
  'ajoyib',
  'majburiyat',
  'natija',
  'uyum',
  'aqilli',
  'changallamoq',
  'siqmoq',
  'oliy',
  'ajoyib',
  'xususiyatlari',
  'hayotiy',
  'odat tusiga kirgan',
  'tasdiqlamoq',
  'hayratda qolgan',
  'gumburlatmoq',
  'qabila',
  "kuchsiz yorug'lik",
  'diqqat',
  'matal',
  'bayram',
  "yorug'lik",
  "ichi bo'sh",
  'instinkt',
  "qo'shma",
  'oqish',
  'shifokor',
  'qurbon qilmoq',
  'qattiq',
  'paypaslamoq',
  'fojiali',
  'sozlash',
  'joylashtirish',
  'sirk',
  "baravar bo'moq",
  "haq to'lamoq",
  'doza',
  "bo'yoq",
  "ko'lam",
  'jins',
  'sarlavha',
  'norasmiy',
  "so'ramoq",
  'xabarchi',
  'kuzatmoq',
  'portret',
  'pozitsiya',
  'rancho',
  'boshqarmoq',
  "yo'l-yo'l chiziq",
  "qo'lga o'rgatilgan",
  'undamoq',
  'Aborigen',
  'taqiqlamoq',
  'ehtiyotkor',
  'tan olish',
  'yozgi uy',
  'kunduzi',
  'istalgan',
  "rangi o'chmoq",
  'shafqatsiz',
  'qimor',
  'maysazor',
  "o'roq",
  'noqonuniy',
  'istiqbol',
  'sumka',
  'tayoq',
  'kamdan-kam hollarda',
  'soqol olmoq',
  "qo'rqqan",
  'sehrgar',
  'yuk',
  'Lampochka',
  "to'plam",
  'qoramol',
  'qochmoq',
  "o'tlamoq",
  "ochko'zlik",
  'poda',
  'boshlamoq',
  "yo'l",
  'yuk',
  'asab',
  'optimist',
  'parad',
  'tosh yotqizmoq',
  'hayoliy',
  'portativ',
  'afisha',
  'tirnamoq',
  'simfoniya',
  'beva ayol',
  'tarqatmoq',
  'natijada',
  "ko'chirmoq",
  "cho'kmoq",
  'sulola',
  'qism',
  'yaxlmalak',
  'illuziya',
  "ishg'ol qilish",
  'leytenant',
  'dengizdagi',
  'qadr-qimmati',
  'flot',
  'qutbli',
  'nur',
  "iste'foga chiqmoq",
  "o'z joniga qasd qilish",
  'qaltirash',
  'asosiy',
  'orqali',
  "o'zgartirmoq",
  'chetda',
  'kuz',
  'aralashtirmoq',
  'qulamoq',
  'ezish',
  'egri',
  'jirkanchli',
  'oqova',
  'quchoqlamoq',
  'hasad qilmoq',
  'mushak',
  'un',
  'yonadigan arqon',
  'zanjabil',
  'hasadchi',
  'pasta',
  'chek',
  'artmoq',
  'sim',
  "e'tirof etish",
  'elchi',
  'mallasoch',
  "ishg'ol qilish",
  'tortmoq',
  "oshirib ko'rsatmoq",
  'meros',
  'haqorat qilmoq',
  'paytida',
  'marjon',
  'oliyjanob',
  'qimmatbaho',
  'xurofot',
  'mish-mish',
  'gunoh',
  'manzara',
  "g'aram",
  'shubhali',
  'qalay',
  'vaza',
  "og'riq",
  'arktik',
  'kanal',
  'kimyogar',
  'salqinlamoq',
  'Kongress',
  'sut mahsulotlari',
  'tushmoq',
  'baqqol',
  'ikkilanmoq',
  'muassasa',
  'yugurmoq',
  'savdogar',
  'bosmoq turtmoq',
  'kechiktirmoq',
  'sepmoq',
  "o'jar",
  'shahar cheti',
  "to'lqin",
  'fojia',
  'bomba',
  'sertifikat',
  'vaziyat',
  'tobut',
  'uddalamoq',
  'tanqid',
  'vayron qilmoq',
  "qovoq o'ymoq",
  'qaramoq',
  'qarash',
  "qayg'u",
  'kuyov',
  'litsenziya',
  'mikroskop',
  'yadroviy',
  "ko'rsatmoq",
  'aylantirmoq',
  'estalik',
  'batiskaf',
  'iz',
  'qurilma',
  'havza',
  'supurgi',
  'kapalak qurti',
  'Javon',
  'nozik',
  "paydo bo'lmoq",
  'falajlik',
  'ilmoq',
  'sakramoq',
  'kir kiyim',
  "ta'qib qilish",
  'istamay',
  'yeng',
  'umurtqa',
  "dog'",
  'plyonka',
  'ont ichmoq',
  'belanchak',
];
