const uz4 = [
  'foydalanmoq',
  "xushbo'y hid",
  'ichimliklar',
  "to'plam",
  "qo'shmoq",
  'zichlangan',
  'zamonaviy',
  'yetishtirmoq',
  'ilohiy',
  'nam',
  'hid',
  "tag'nay",
  'jannat',
  'dala maydoni',
  'tez',
  'tezligi',
  'tinchlantiruvchi',
  'sezilmas',
  'yuza shakli',
  'zaxarli',
  'farq qilmoq',
  'baxtsiz xodisa',
  'admiral',
  'yoy',
  "fe'l",
  'vijdon',
  'olovli',
  "go'sht",
  'mandarin',
  'pichan',
  'dahshatga tushgan',
  'kerosin',
  'aylana',
  'eshkak',
  'sol',
  'nordon',
  'qoziq',
  'xizmatchi',
  'ip',
  'tikan',
  'halokatga uchramoq',
  'tanbeh bermoq',
  'eshitiladigan',
  'ajoyib',
  "ehtiyot bo'lmoq",
  'maqtanmoq',
  'xushi joyida',
  "rozi bo'lmaslik",
  'aks sado',
  "so'ngi",
  'ishora',
  'ahmoq',
  'ulkan',
  'bilvosita',
  'tanlov',
  "ko'ngilochar mashg'ulot",
  'mukammal',
  'aniqlamoq',
  "o'zgartirmoq",
  "batafsil  to'liq",
  'azob bermoq',
  'tumshuq',
  "ho'l",
  "ma'qullamaslik",
  'mustasno',
  'parvoz',
  "xush ko'rmoq",
  'axloqsiz',
  'pechak',
  'oh tortmoq',
  'bexabar',
  "halok bo'lish",
  'chuqur',
  'rim',
  'roost',
  'sirpanchiq',
  "baland ko'tarilmoq",
  'ahamiyatsiz',
  'odatiy',
  'umuman',
  "yig'lamoq",
  'bir muddat',
  'kiber-maydon',
  'tuzatish kiritmoq',
  'insho',
  'baholamoq',
  'xushdan ketish',
  'global',
  'sport zali',
  "belgilab qo'ymoq",
  'bexabar',
  'indeks',
  'maruza',
  "ahloqiy  tub ma'no",
  'ishlamoq',
  'xususiy',
  'yaqinda',
  'qaror',
  'semestr',
  'yozma',
  "g'alati",
  'mutlaq',
  'Afsuski',
  'diqqatli',
  'yopinchiq',
  'tasavvur qilish',
  'teng ravishda',
  'xalq',
  'erimoq',
  'yer',
  'zavq',
  'paq (tovush)',
  'puding',
  'panjara qismi',
  'retsept',
  'rol',
  'kichraymoq',
  'namlamoq',
  'uchqun',
  'ruh',
  'kostyum',
  'hisob raqam',
  "me'mor",
  'yashirmoq',
  'jinoyat',
  'guvohnoma',
  'minnatdorchilik',
  'yashash joyi',
  'aralashmoq',
  "yo'l ko'rsatgich",
  'qonuniy',
  'unutilmas',
  'majbur qilmoq',
  'jinoyat',
  "e'lon qilmoq",
  'miting',
  'hal qilmoq',
  'manba',
  'hukm',
  "ko'ngilli ishlamoq",
  'guvoh',
  'kirish imkoniyati',
  'yurish-turish',
  'doimiy',
  'yoriq',
  'qurilma',
  "o'ralgan",
  'mahkam tutmoq',
  "to'xtamoq",
  'yaqinlashib kelayotgan',
  "ta'sir o'tkazmoq",
  'qonun',
  'holat',
  'terlamoq',
  "o'zgartirmoq",
  'sindirmoq',
  'ayyor',
  'moyil',
  'ishonchli',
  'versiya',
  'umuman',
  'yonida',
  'ishtaha',
  'yordam bermoq',
  'yengil shamol',
  'qarshilik qilmoq',
  "ko'rsatmoq",
  'samarali',
  'zaif',
  'kechirmoq',
  "jo'shqin",
  "ulug'vor",
  'ham emas',
  "g'azablangan",
  'noumid',
  'tarsaki tushirmoq',
  'sindirmoq',
  'mavzu',
  'ish haqi',
  'holbuki',
  'jonli',
  'tasniflash',
  'tan olmoq',
  'tushuncha',
  'qurmoq',
  "o'n yil",
  'diagramma',
  'kema',
  'foydali',
  "ajratib qo'ymoq",
  'intizorlik',
  "ko'p",
  'zarracha',
  "o'tinch",
  "o'zini tiymoq",
  "ko'rib chiqmoq",
  'murakkab',
  "taslim bo'lmoq",
  'tik',
  'maqsadga muofiq',
  'ittifoq',
  'olqish',
  'qurollangan',
  'ustuvor',
  'marosim',
  'madaniyat',
  'mudofaa',
  'kichik axborot',
  'turli xil',
  'sehrlamoq',
  'jihozlamoq',
  'istisno',
  'janr',
  "ta'sir",
  "o'ziga jalb qilmoq",
  "to'siq",
  'boshpana',
  'tartibga solmoq',
  "ta'minlamoq",
  "o'ziga bino qo'ygan",
  'muqobil',
  "ko'cha",
  'qorin',
  'urinish',
  'puflamoq',
  'nizo',
  "qit'a",
  'oqim  hozirgi',
  'hurmatsizlik',
  "g'ayrat",
  "qattiqqo'l",
  'suyanmoq',
  'mobainida',
  'nayrang',
  'mushak',
  'qutqarmoq',
  'ketma-ketlik',
  'yer',
  "qo'rqoq",
  "zo'ravonlik",
  "ta'sir qilmoq",
  'autograf',
  'tomchi',
  'damlamoq',
  "e'tiborni tortmoq",
  'taqdir',
  'shox  signal',
  'tez asabiylashadigan',
  'ortda qolmoq',
  'kuchaytirmoq',
  'yomon tush',
  'foydali',
  'oqsil',
  'imzo',
  'narsa',
  'ong osti',
  'yuk mashinasi',
  'ogohlantirmoq',
  'mashq',
  'tez  yurmoq  yaqinlashtirmoq',
  "g'isht",
  "to'kilib qolmoq",
  'xamir',
  'ifodalamoq',
  'musht',
  'moslashuvchan',
  'qizarmoq',
  'shikastlamoq',
  "bo'lak",
  'aralashma',
  'yarashmoq',
  'vayron qilmoq',
  'sindirmoq',
  'tashqi deraza',
  'elamoq',
  'biroz',
  'chaqnamoq',
  'sepmoq',
  'qotgan',
  'gapirmoq',
  "bo'lsa-da",
  "qo'ymoq",
  'kutmoq',
  'sevimli',
  'dafn qilmoq',
  'iqlim',
  'shikoyat qilmoq',
  'adashtirmoq',
  'kutilmoq',
  'butun',
  'tashkil etmoq',
  'isitgich',
  'arqon',
  "ulg'aymoq",
  "o'lchamoq",
  "o'rtada",
  'baxtsizlik',
  'oldin',
  'tadqiqot',
  'turli',
  'batamom',
  'birlashmoq',
  "ko'karish  lat",
  'odat',
  'itoatsiz',
  "oldindan ko'rmoq",
  'qaramoq',
  'halqa',
  'baxtsizlik',
  'salbiy',
  'boshiga  har bir',
  "yalinib so'ramoq",
  'yirtmoq',
  'uchun',
  'qirmoq',
  'manba',
  'juda jiddiy',
  'tikmoq',
  "do'ppillash",
  'asabiylashgan',
  'sivilizatsiya',
  'qulay',
  "in  o'ra",
  'shudring',
  "qattiq  og'ir",
  'chiqmoq',
  'suruv',
  'qatlamoq',
  'qopqoq',
  "cho'lg'amoq",
  'qudratli',
  "qo'ziqorin",
  'mahalliy',
  'zahar',
  'qamish',
  'himoya qilmoq',
  "bo'ronli",
  'tebranmoq',
  'shahar',
  'suvda yurmoq',
  'talaffuz  aksent',
  'sartarosh',
  "yerto'la",
  "bo'sh",
  "ko'zni yumib ochmoq",
  'xor',
  'kulgili',
  'murakkablashtirmoq',
  'rad etmoq',
  'harakat',
  "qo'lqop",
  'odamovi',
  'adolatli',
  'charm',
  "o'ylab ko'rmoq",
  "olib qo'ymoq",
  'ssenariy',
  'qidirmoq',
  'qattiq yopmoq',
  'zina',
  'azoblangan',
  "yo'lak",
  'atmosfera',
  'muallif',
  'buzilish',
  'yuk',
  "bo'lim",
  'ulanmoq',
  'va boshqalar',
  'bosmoq',
  "bo'sh",
  'xabar bermoq',
  "no'xat",
  'mayiz',
  'saqlamoq',
  'takidlamoq',
  'patnis',
  'baxtsiz',
  'rang-barang',
  'qayt qilmoq',
  'xiyonat qilmoq',
  'portlash',
  'bilaguzuk',
  "to'xtamoq",
  "yo'talmoq",
  'fuqarolik',
  'sharhlamoq',
  "kesib o'tmoq",
  'pachoq',
  'ishonmaslik',
  "qal'a",
  'tashkil etmoq',
  'astar',
  'uyum',
  'ibodat qilmoq',
  "to'la",
  'tag',
  'supurmoq',
  'xiyonat',
  'joylamoq',
  'tarbiya',
  "xo'rak",
  'yozib bormoq',
  'mis',
  'kasallik',
  'xalq ijodi',
  'yuqtirmoq',
  'qichimoq',
  'adabiyot',
  'mingyillik',
  'afsona',
  'mansabini oshirmoq',
  "bog'lamoq",
  'din',
  'miqdor',
  'bank ishchisi',
  'ishonchli',
  'yangilash',
  'tomir',
  'zahar',
  'xayriya',
  'tijorat',
  'hukm qilish',
  'qulay',
  'tugatmoq',
  'iqtisodiyot',
  'imperiya',
  'mahsulot',
  'diqqat qilmoq',
  'tekinga yurmoq',
  'masxara qilmoq',
  'betaraf',
  'kamsitmoq',
  'achinish',
  'kamaytirish',
  'xattot',
  'jaxl',
  'taxt',
  'birlik',
  "g'olib",
  'tahlil qilish',
  'asteroid',
  'tortishuv',
  'rivojlanmoq',
  'omil',
  'genetik',
  'irsiyat',
  'bir xil',
  'oqil',
  "ko'pchilik",
  'sutemizuvchi',
  "ko'paymoq",
  'zurriyod',
  'pestisid',
  'tartibga solmoq',
  'kuchaytirmoq',
  'aziyat chekgan',
  'katta',
  'vegetarian',
  'qadrlamoq',
  'rahm',
  'rozilik',
  "o'zak",
  'ayyor',
  'holsiz',
  'muvozanat',
  'shakllantirish',
  'ezmoq',
  'irillamoq',
  "o'rtacha",
  'yirtqich',
  'ongli',
  'likopcha',
  'yulib olmoq',
  'dovdiramoq',
  'qoqilmoq',
  'tashvishda',
  'dumalab ketmoq',
  'bermaslik',
  'samolyot',
  'mashhur kishi',
  'beton',
  'hal qiluvchi',
  'hurmatli',
  'axloqiy',
  "yo'qolgan",
  'irodali',
  'institut',
  'rashk',
  "ko'chmoq",
  'tarbiyalamoq',
  'tepadan',
  'odob-ahloq',
  'qishloq',
  'olis',
  'tur',
  'botqoqlik',
  'kezmoq',
  'zoologiya',
  'taxmin',
  'arpa',
  'maxluq',
  'polkovnik',
  'yuqumli',
  'murda',
  'inqiroz',
  'davolamoq',
  'qiyshaygan',
  'kamsitmoq',
  'elchixona',
  "o'chirmoq",
  'tosh',
  "tazyiq o'tkazmoq",
  "qo'shilmoq",
  'mitti',
  'ozuqa',
  'darhol',
  'usta',
  'tropik mintaqa',
  'foydali',
  "tug'ilgan joyi",
  "sig'im",
  'qiyosiy',
  'keng qamrovli',
  'saqlab qolmoq',
  'muhim',
  "yig'iladigan",
  "qo'ymoq",
  'tarqatmoq',
  'ekvator',
  'ekzotik',
  'federal',
  'shakllanish',
  'takrorlanish',
  'maqsad',
  'kislorod',
  "tropik o'rmon",
  'strategiya',
  "o'rmonli",
  'yordam',
  'kengaymoq',
  'belgilamoq',
  "qo'rqmoq",
  'asosiy',
  'dahshatli',
  "ishonib bo'lmaydigan",
  "ko'p vaqt turmoq",
  'organizm',
  'soddalashtirmoq',
  'vabo',
  'hozirgi kunda',
  'tasodifiy',
  'isyon',
  'qoralamoq',
  'ziyoratgoh',
  "yolg'izlik",
  'mutlaq',
  'chaqirmoq',
  'yomonlashmoq',
  'avtomobil',
  'nomzod',
  'maxfiy',
  'korporativ',
  'yaxshilamoq',
  'davr',
  "ko'rsatma",
  "qo'shmoq",
  'aloqa qilmoq',
  'tanaffus',
  'mobil',
  "o'zgartirmoq",
  'parallel',
  'hodisa',
  'ifloslamoq',
  'masxara qilmoq',
  'quyosh',
  'hudud',
  'turnir',
  'transport',
  "to'lov",
  'chegara',
  'chalkashlik',
  'tartibli',
  "to'fon",
  'umidsiz',
  "merosxo'r",
  'jang',
  'organik',
  'parranda',
  'hovliqmoq',
  'serjant',
  'haqqoniy',
  'mulohaza',
  'telegraf',
  'mato',
  'quyun',
  "to'fon",
  "yig'lamoq",
  'kiyim jovoni',
  'aniq',
];
