// **Question-13**
// *tayyor*
// # 1: Yuqoridagi hammat testlar (jami 460)
'use strick';
// Array of Object;
const quiz = [
  {
    q: `arise`,
    options: [`paydo bo'lamoq`, `xo'rsinmoq`, `ajoyib`, `hop`],
    answer: 0,
  },
  {
    q: `benefactor`,
    options: [`xayrixoh,`, `qarag'ay`, `o'smir`, `chorvachilik`],
    answer: 0,
  },
  {
    q: `blacksmith`,
    options: [`temirchi`, `tuman`, `puflash`, `so'ramoq`],
    answer: 0,
  },
  {
    q: `charitable`,
    options: [`xayriya`, `oqilona`, `emish`, `tushish`],
    answer: 0,
  },
  { q: `chimney`, options: [`mo'ri`, `portativ`, `tırtıl`, `nur`], answer: 0 },
  {
    q: `compensate`,
    options: [`kompensatsiya to'lamoq`, `sayoz`, `surtish`, `artib oling`],
    answer: 0,
  },
  {
    q: `encounter`,
    options: [`uchrashish`, `tark etmoq`, `ko'mir`, `tasvirlash`],
    answer: 0,
  },
  {
    q: `exceed`,
    options: [`oshib ketish`, `sodiq`, `chandiq`, `ostida`],
    answer: 0,
  },
  {
    q: `forge`,
    options: [`soxta`, `uyat`, `hamdardlik`, `aylanish`],
    answer: 0,
  },
  {
    q: `humble`,
    options: [`kamtarin`, `bandaj`, `qoniqish`, `qolgan`],
    answer: 0,
  },
  { q: `iron`, options: [`temir`, `fir'avn`, `mato`, `qovurilgan`], answer: 0 },
  {
    q: `ladder`,
    options: [`narvon`, `xayrixoh`, `chiroq`, `imperator`],
    answer: 0,
  },
  {
    q: `modest`,
    options: [`kamtarin`, `poya`, `xayriya`, `alanga`],
    answer: 0,
  },
  {
    q: `occupy`,
    options: [`egallash`, `asosida`, `yangilash`, `natija`],
    answer: 0,
  },
  {
    q: `penny`,
    options: [`tiyin`, `shifokor`, `haqorat qilish`, `va'z qilish`],
    answer: 0,
  },
  {
    q: `preach`,
    options: [`va'z qilish`, `havzasi`, `titramoq`, `ail`],
    answer: 0,
  },
  {
    q: `prosper`,
    options: [`gullab-yashnamoq`, `kamdan-kam hollarda`, `kesish`, `do'l`],
    answer: 0,
  },
  {
    q: `province`,
    options: [`viloyat`, `sabrsiz`, `ittifoqdosh`, `ko'paytirish`],
    answer: 0,
  },
  {
    q: `satisfaction`,
    options: [`qoniqish`, `mato`, `ob'ekt`, `eymoq`],
    answer: 0,
  },
  {
    q: `sustain`,
    options: [`ushlab turish`, `so'ramoq`, `tirnash`, `bo'yoq`],
    answer: 0,
  },
  {
    q: `acquire`,
    options: [`egallash`, `aniq`, `poya`, `bashorat qilish`],
    answer: 0,
  },
  {
    q: `awkward`,
    options: [`noqulay`, `sovuq`, `ochlik`, `inoyat`],
    answer: 0,
  },
  {
    q: `caretaker`,
    options: [`qo'riqchi`, `tashlamoq`, `tanqid`, `qichqirmoq`],
    answer: 0,
  },
  {
    q: `deceive`,
    options: [`aldamoq`, `agentlik`, `xayrixoh`, `tan olmoq`],
    answer: 0,
  },
  {
    q: `discourage`,
    options: [`tushkunlikka tushirish`, `qarash`, `marsh`, `raqib`],
    answer: 0,
  },
  { q: `fake`, options: [`soxta`, `ip`, `tegirmon`, `torting`], answer: 0 },
  {
    q: `hatred`,
    options: [`nafrat`, `insult`, `senator`, `bortida`],
    answer: 0,
  },
  { q: `hut`, options: [`kulba`, `zarba`, `tashlamoq`, `jun`], answer: 0 },
  {
    q: `inferior`,
    options: [`pastroq`, `hamdardlik`, `dengiz`, `zaruriyat`],
    answer: 0,
  },
  {
    q: `lodge`,
    options: [`turar joy`, `chegaralash`, `egallash`, `ayni paytda`],
    answer: 0,
  },
  {
    q: `neglect`,
    options: [`e'tiborsizlik`, `yostiq`, `ulkan`, `sirk`],
    answer: 0,
  },
  {
    q: `newcomer`,
    options: [`yangi kelgan`, `barg`, `tomizish`, `chaqmoq`],
    answer: 0,
  },
  {
    q: `offense`,
    options: [`jinoyat`, `o'rmalash`, `tiyin`, `ochko'zlik`],
    answer: 0,
  },
  {
    q: `overlook`,
    options: [`e'tiborsizlik`, `kunduzi`, `don`, `egallash`],
    answer: 0,
  },
  {
    q: `repay`,
    options: [`to'lash`, `g'azab`, `cho'kmoq`, `hosil qilish`],
    answer: 0,
  },
  {
    q: `ridiculous`,
    options: [`kulgili`, `baland ovozda`, `darajada`, `suvenir`],
    answer: 0,
  },
  {
    q: `satisfactory`,
    options: [`qoniqarli`, `tushkunlikka tushirish`, `nafrat`, `dahshat`],
    answer: 0,
  },
  {
    q: `shepherd`,
    options: [`cho'pon`, `un`, `gullab-yashnamoq`, `orqa`],
    answer: 0,
  },
  {
    q: `venture`,
    options: [`tashabbus`, `jazo`, `tutmoq`, `sodiq`],
    answer: 0,
  },
  {
    q: `wheat`,
    options: [`bug'doy`, `mitti`, `sakrash`, `aralashtirmoq`],
    answer: 0,
  },
  {
    q: `alley`,
    options: [`xiyobon`, `dam olish`, `shirinlik`, `mag'lubiyat`],
    answer: 0,
  },
  {
    q: `ax`,
    options: [`bolta`, `taqlid qilish`, `sayoz`, `oqlangan`],
    answer: 0,
  },
  {
    q: `bunch`,
    options: [`to'da`, `qoramol`, `hukmron`, `xiyobon`],
    answer: 0,
  },
  { q: `chore`, options: [`ish`, `xayriya`, `kulgili`, `kurash`], answer: 0 },
  {
    q: `decent`,
    options: [`munosib`, `duradgor`, `emaklash`, `meros`],
    answer: 0,
  },
  {
    q: `disgrace`,
    options: [`sharmandalik`, `to'plam`, `kub`, `shayton`],
    answer: 0,
  },
  {
    q: `elbow`,
    options: [`tirsak`, `jingalak`, `rahm-shafqat`, `mikroskop`],
    answer: 0,
  },
  {
    q: `grateful`,
    options: [`minnatdor`, `olijanob`, `skameyka`, `duch kelmoq`],
    answer: 0,
  },
  {
    q: `irritate`,
    options: [`asabiylashtirmoq`, `taqiqlash`, `mehr`, `teging`],
    answer: 0,
  },
  {
    q: `kid`,
    options: [`bola`, `natijada`, `tik`, `taqlid qilish`],
    answer: 0,
  },
  { q: `loose`, options: [`bo'sh`, `hashamatli`, `kul`, `iyagi`], answer: 0 },
  {
    q: `offend`,
    options: [`xafa qilish`, `to'kmoq`, `olijanob`, `chaqaloq`],
    answer: 0,
  },
  {
    q: `overnight`,
    options: [`kecha davomida`, `dog '`, `o'tlamoq`, `qisqa vaqt ichida`],
    answer: 0,
  },
  {
    q: `persist`,
    options: [`davom eting`, `cho'kmoq`, `tiz cho'kish`, `jangchi`],
    answer: 0,
  },
  {
    q: `pine`,
    options: [`qarag'ay`, `aralashtirmoq`, `hosil qilish`, `kelib chiqishi`],
    answer: 0,
  },
  {
    q: `scar`,
    options: [`chandiq`, `bayram`, `adolat`, `temirchi`],
    answer: 0,
  },
  {
    q: `sensation`,
    options: [`sensatsiya`, `hayajon`, `lampochka`, `zanjabil`],
    answer: 0,
  },
  {
    q: `sled`,
    options: [`chana`, `ustuvorlik`, `chekinish`, `pastroq`],
    answer: 0,
  },
  {
    q: `tease`,
    options: [`mazax qilish`, `vasvasaga solmoq`, `xiyobon`, `titramoq`],
    answer: 0,
  },
  {
    q: `valentine`,
    options: [`valentin`, `sammit`, `hakamlar hay'ati`, `emish`],
    answer: 0,
  },
  { q: `bloom`, options: [`gullash`, `muassasa`, `kal`, `tuman`], answer: 0 },
  {
    q: `compact`,
    options: [`ixcham`, `qimor o'ynash`, `qichqirmoq`, `rishta`],
    answer: 0,
  },
  { q: `curl`, options: [`jingalak`, `chop`, `diametri`, `chekka`], answer: 0 },
  {
    q: `decay`,
    options: [`parchalanish`, `kul`, `yopishtiring`, `istaksiz`],
    answer: 0,
  },
  {
    q: `dessert`,
    options: [`shirinlik`, `Aborigen`, `chiziq`, `nozik`],
    answer: 0,
  },
  {
    q: `dip`,
    options: [`cho'milish`, `hayratda`, `yashovchi`, `konsol`],
    answer: 0,
  },
  {
    q: `distant`,
    options: [`uzoq`, `og'riq`, `simfoniya`, `paydo bo'ladi`],
    answer: 0,
  },
  {
    q: `eclipse`,
    options: [`tutilish`, `iz`, `taqlid qilish`, `yugurish`],
    answer: 0,
  },
  {
    q: `fairy`,
    options: [`peri`, `g'ayritabiiy`, `muloyim`, `hamyon`],
    answer: 0,
  },
  { q: `grace`, options: [`inoyat`, `uyqu`, `tasodifiy`, `tanbeh`], answer: 0 },
  {
    q: `leisure`,
    options: [`dam olish`, `emaklash`, `sodiq`, `chidamoq`],
    answer: 0,
  },
  {
    q: `mankind`,
    options: [`insoniyat`, `gullash`, `portativ`, `bajarmoq`],
    answer: 0,
  },
  {
    q: `passion`,
    options: [`ehtiros`, `joylashtirmoq`, `istaksiz`, `stack`],
    answer: 0,
  },
  {
    q: `pillow`,
    options: [`yostiq`, `suv osti kemasi`, `cho'pon`, `istiqbol`],
    answer: 0,
  },
  {
    q: `pulse`,
    options: [`puls`, `ishdan bo'shatish`, `quvnoq`, `romashka`],
    answer: 0,
  },
  {
    q: `refresh`,
    options: [`yangilash`, `kechki ovqat`, `raqib`, `tayoq`],
    answer: 0,
  },
  {
    q: `sneeze`,
    options: [`aksirish`, `jirkanch`, `aralashtirmoq`, `davom eting`],
    answer: 0,
  },
  {
    q: `spice`,
    options: [`ziravorlar`, `istaksiz`, `plakat`, `sim`],
    answer: 0,
  },
  {
    q: `whistle`,
    options: [`hushtak chalish`, `muloyim`, `alanga`, `portret`],
    answer: 0,
  },
  { q: `wool`, options: [`jun`, `tomosha`, `to'kmoq`, `achchiq`], answer: 0 },
  {
    q: `acquaint`,
    options: [`tanishish`, `mehr`, `beva ayol`, `qiynoqlar`],
    answer: 0,
  },
  {
    q: `cemetery`,
    options: [`qabriston`, `qulash`, `tong`, `sherif`],
    answer: 0,
  },
  {
    q: `curse`,
    options: [`la'nat`, `odatlangan`, `kir yuvish`, `ta'kidlash`],
    answer: 0,
  },
  {
    q: `disguise`,
    options: [`niqoblash`, `skameyka`, `mahkamlang`, `jingalak`],
    answer: 0,
  },
  {
    q: `fancy`,
    options: [`xayoliy`, `sarg'ish`, `shoshilinch`, `peri`],
    answer: 0,
  },
  {
    q: `flashlight`,
    options: [`chiroq`, `parchalanish`, `sharmandalik`, `mazax qilish`],
    answer: 0,
  },
  { q: `hood`, options: [`kaput`, `katta`, `hislar`, `Javon`], answer: 0 },
  {
    q: `inhabitant`,
    options: [`yashovchi`, `komissiya`, `qovog'ini burish`, `shishiradi`],
    answer: 0,
  },
  {
    q: `nourish`,
    options: [`oziqlantirish`, `qasos`, `umidsiz`, `to'plam`],
    answer: 0,
  },
  {
    q: `pirate`,
    options: [`qaroqchi`, `kuylash`, `sim`, `oqilona`],
    answer: 0,
  },
  {
    q: `publication`,
    options: [`nashr`, `oliy`, `g'azab`, `jinoyat`],
    answer: 0,
  },
  {
    q: `riddle`,
    options: [`topishmoq`, `ittifoqdosh`, `arifmetik`, `ish`],
    answer: 0,
  },
  {
    q: `rot`,
    options: [`chirigan`, `kechir`, `yangi kelgan`, `oshib ketish`],
    answer: 0,
  },
  {
    q: `scare`,
    options: [`qo'rqitish`, `qobiliyat`, `dahshat`, `qoya`],
    answer: 0,
  },
  {
    q: `shortly`,
    options: [`qisqa vaqt ichida`, `taqdir`, `natijada`, `vaza`],
    answer: 0,
  },
  {
    q: `skeleton`,
    options: [`skelet`, `topishmoq`, `qoziq`, `aniq`],
    answer: 0,
  },
  {
    q: `spoil`,
    options: [`buzmoq`, `tilim`, `navigatsiya qilish`, `portlash`],
    answer: 0,
  },
  { q: `starve`, options: [`ochlik`, `chekka`, `chana`, `o'q`], answer: 0 },
  {
    q: `thrill`,
    options: [`hayajon`, `bortida`, `tayoq`, `g'ayratli`],
    answer: 0,
  },
  { q: `wicked`, options: [`yovuz`, `o'g'irlik`, `fojiali`, `kul`], answer: 0 },
  {
    q: `alert`,
    options: [`ogohlantirish`, `ilgak`, `oraliq`, `paydo bo'ladi`],
    answer: 0,
  },
  {
    q: `broadcast`,
    options: [`efirga uzatish`, `bay`, `ekotizim`, `chiroq`],
    answer: 0,
  },
  {
    q: `bulletin`,
    options: [`byulleten`, `shogird`, `xurofot`, `emaklash`],
    answer: 0,
  },
  {
    q: `bump`,
    options: [`zarba`, `bajarmoq`, `asabiylashtirmoq`, `nayza`],
    answer: 0,
  },
  {
    q: `chop`,
    options: [`chop`, `mehnatsevar`, `portlash`, `yozgi uy`],
    answer: 0,
  },
  {
    q: `closet`,
    options: [`shkaf`, `ogohlantirish`, `eymoq`, `Kongress`],
    answer: 0,
  },
  {
    q: `console`,
    options: [`konsol`, `tuman`, `bortida`, `yig'ilish`],
    answer: 0,
  },
  {
    q: `district`,
    options: [`tuman`, `nayza`, `dam olish`, `millioner`],
    answer: 0,
  },
  {
    q: `drawer`,
    options: [`tortma`, `achchiq`, `shayton`, `xususiyat`],
    answer: 0,
  },
  {
    q: `endure`,
    options: [`chidamoq`, `sherif`, `atir`, `munosib`],
    answer: 0,
  },
  {
    q: `execute`,
    options: [`bajarmoq`, `qayg'u`, `adabiy`, `qaysar`],
    answer: 0,
  },
  {
    q: `grasp`,
    options: [`tutmoq`, `instinkt`, `siqish`, `to'lqin`],
    answer: 0,
  },
  {
    q: `rear`,
    options: [`orqa`, `nur`, `tasvirlash`, `yangi kelgan`],
    answer: 0,
  },
  {
    q: `senator`,
    options: [`senator`, `qo'shinlar`, `mustaqillik`, `oqish`],
    answer: 0,
  },
  {
    q: `skull`,
    options: [`bosh suyagi`, `sabr`, `homilador`, `maqol`],
    answer: 0,
  },
  {
    q: `stir`,
    options: [`aralashtirmoq`, `buzmoq`, `portlash`, `kir yuvish`],
    answer: 0,
  },
  { q: `tap`, options: [`teging`, `bola`, `ko'paytirish`, `raqib`], answer: 0 },
  {
    q: `tremendous`,
    options: [`ulkan`, `hovuz`, `tengdosh`, `xo'rsinmoq`],
    answer: 0,
  },
  {
    q: `underneath`,
    options: [`ostida`, `sharmandalik`, `lava`, `qarash`],
    answer: 0,
  },
  { q: `worm`, options: [`qurt`, `xabarchi`, `qulash`, `favvora`], answer: 0 },
  {
    q: `abandon`,
    options: [`tark etmoq`, `qoziq`, `jingalak`, `portlash`],
    answer: 0,
  },
  {
    q: `ambitious`,
    options: [`ambitsiyali`, `marsh`, `mos keladi`, `eritish`],
    answer: 0,
  },
  { q: `bark`, options: [`qobiq`, `sarlavha`, `kema`, `tashlamoq`], answer: 0 },
  {
    q: `bay`,
    options: [`bay`, `kechiktirish`, `chekinmoq`, `cho'pon`],
    answer: 0,
  },
  { q: `brilliant`, options: [`ajoyib`, `ostida`, `pishgan`, `un`], answer: 0 },
  { q: `chin`, options: [`iyagi`, `zaxira`, `olov`, `cho'milish`], answer: 0 },
  {
    q: `complaint`,
    options: [`shikoyat`, `qonundan tashqari`, `belanchak`, `gullab-yashnamoq`],
    answer: 0,
  },
  {
    q: `deaf`,
    options: [`kar`, `chekinmoq`, `to'lqin`, `yengillik`],
    answer: 0,
  },
  {
    q: `enthusiastic`,
    options: [`g'ayratli`, `pastroq`, `taxmin qilish`, `bezori`],
    answer: 0,
  },
  {
    q: `expedition`,
    options: [`ekspeditsiya`, `sim`, `kompas`, `boshpana`],
    answer: 0,
  },
  {
    q: `horizon`,
    options: [`gorizont`, `ail`, `e'tiborsizlik`, `majburlash`],
    answer: 0,
  },
  { q: `loyal`, options: [`sodiq`, `orqa`, `yozgi uy`, `vagon`], answer: 0 },
  { q: `mayor`, options: [`mer`, `tobut`, `bosqin`, `kvitansiya`], answer: 0 },
  {
    q: `mutual`,
    options: [`o'zaro`, `zirh`, `aldamoq`, `topishmoq`],
    answer: 0,
  },
  {
    q: `overweight`,
    options: [`ortiqcha vazn`, `chuqur`, `fir'avn`, `yangilash`],
    answer: 0,
  },
  {
    q: `refuge`,
    options: [`boshpana`, `ritsar`, `foydalanish`, `qoniqish`],
    answer: 0,
  },
  { q: `restore`, options: [`tiklash`, `qolgan`, `ter`, `qoziq`], answer: 0 },
  {
    q: `rub`,
    options: [`surtish`, `darajada`, `uchastka`, `o'zaro`],
    answer: 0,
  },
  {
    q: `senses`,
    options: [`hislar`, `kamtarin`, `qalay`, `sehrgar`],
    answer: 0,
  },
  {
    q: `veterinarian`,
    options: [`veterinar`, `vaza`, `yo'qligi`, `kimyogar`],
    answer: 0,
  },
  {
    q: `anniversary`,
    options: [`yubiley`, `beva ayol`, `ustuvorlik`, `chetga`],
    answer: 0,
  },
  {
    q: `arithmetic`,
    options: [`arifmetik`, `parad`, `zanjabil`, `bosh irg'adi`],
    answer: 0,
  },
  {
    q: `ashamed`,
    options: [`uyaldi`, `tebranish`, `havzasi`, `tanishish`],
    answer: 0,
  },
  {
    q: `burst`,
    options: [`portlash`, `poza`, `kelib chiqishi`, `gullash`],
    answer: 0,
  },
  {
    q: `carpenter`,
    options: [`duradgor`, `qimmatli`, `soxta`, `mato`],
    answer: 0,
  },
  {
    q: `coal`,
    options: [`ko'mir`, `paydo bo'ladi`, `ertak`, `leytenant`],
    answer: 0,
  },
  {
    q: `couch`,
    options: [`divan`, `qasam iching`, `qo'shma`, `tutmoq`],
    answer: 0,
  },
  {
    q: `drip`,
    options: [`tomizish`, `uchastka`, `tetik`, `dam olish`],
    answer: 0,
  },
  {
    q: `elegant`,
    options: [`oqlangan`, `baland tog'lar`, `rashkchi`, `kesish`],
    answer: 0,
  },
  {
    q: `fabric`,
    options: [`mato`, `byulleten`, `litsenziya`, `lava`],
    answer: 0,
  },
  {
    q: `highlands`,
    options: [`baland tog'lar`, `aksirish`, `aniq`, `optimist`],
    answer: 0,
  },
  {
    q: `ivory`,
    options: [`fil suyagi`, `dahshatli`, `mish-mish`, `kamtarin`],
    answer: 0,
  },
  { q: `mill`, options: [`tegirmon`, `eymoq`, `insult`, `qayg'u`], answer: 0 },
  {
    q: `needle`,
    options: [`igna`, `maydalash`, `o'g'irlik`, `mish-mish`],
    answer: 0,
  },
  {
    q: `polish`,
    options: [`jilo`, `qoniqarli`, `kamtarin`, `tasma`],
    answer: 0,
  },
  { q: `sew`, options: [`tikish`, `poda`, `katta`, `uchrashish`], answer: 0 },
  {
    q: `shed`,
    options: [`to'kmoq`, `xayoliy`, `soqol olish`, `engish`],
    answer: 0,
  },
  { q: `thread`, options: [`ip`, `yadroviy`, `maqol`, `ataylab`], answer: 0 },
  {
    q: `trim`,
    options: [`kesish`, `istiqbol`, `asab`, `o'zgartirish`],
    answer: 0,
  },
  {
    q: `upwards`,
    options: [`yuqoriga`, `marjon`, `vaza`, `otilib chiqish`],
    answer: 0,
  },
  { q: `ail`, options: [`ail`, `yozgi uy`, `poza`, `sovuq`], answer: 0 },
  {
    q: `ally`,
    options: [`ittifoqdosh`, `xalat`, `veterinar`, `zarba`],
    answer: 0,
  },
  {
    q: `boast`,
    options: [`maqtanmoq`, `qayg'u`, `oshib ketish`, `o'g'irlash`],
    answer: 0,
  },
  {
    q: `bounce`,
    options: [`sakrash`, `ochlik`, `tilim`, `umidsiz`],
    answer: 0,
  },
  {
    q: `bully`,
    options: [`bezori`, `gullash`, `ajralish`, `og'riq`],
    answer: 0,
  },
  {
    q: `carbohydrate`,
    options: [`uglevod`, `so'nish`, `tuman`, `hid`],
    answer: 0,
  },
  {
    q: `crawl`,
    options: [`emaklash`, `ochlik`, `komissiya`, `po'lat`],
    answer: 0,
  },
  {
    q: `defeat`,
    options: [`mag'lubiyat`, `yugurish`, `hashamatli`, `yuqoriga`],
    answer: 0,
  },
  {
    q: `dial`,
    options: [`tering`, `doza`, `kecha davomida`, `suv osti kemasi`],
    answer: 0,
  },
  {
    q: `dominant`,
    options: [`hukmron`, `aralashtirmoq`, `zirh`, `kamdan-kam hollarda`],
    answer: 0,
  },
  {
    q: `mercy`,
    options: [`rahm-shafqat`, `mish-mish`, `so'ramoq`, `fojia`],
    answer: 0,
  },
  {
    q: `nod`,
    options: [`bosh irg'adi`, `sakrash`, `baca`, `veterinar`],
    answer: 0,
  },
  {
    q: `opponent`,
    options: [`raqib`, `pishgan`, `stack`, `to'lash`],
    answer: 0,
  },
  {
    q: `quarrel`,
    options: [`janjal`, `tering`, `tebranish`, `gorizont`],
    answer: 0,
  },
  { q: `rival`, options: [`raqib`, `ochko'zlik`, `barg`, `tez`], answer: 0 },
  {
    q: `sore`,
    options: [`og'riq`, `tasdiqlamoq`, `norasmiy`, `xabarchi`],
    answer: 0,
  },
  { q: `sting`, options: [`chaqish`, `maqol`, `ritsar`, `bolta`], answer: 0 },
  {
    q: `strain`,
    options: [`kuchlanish`, `bezori`, `teging`, `mehnatsevar`],
    answer: 0,
  },
  {
    q: `torture`,
    options: [`qiynoqlar`, `teging`, `fil suyagi`, `olijanob`],
    answer: 0,
  },
  { q: `wrestle`, options: [`kurash`, `kar`, `xira`, `doza`], answer: 0 },
  {
    q: `absence`,
    options: [`yo'qligi`, `yashash`, `kamdan-kam hollarda`, `kaput`],
    answer: 0,
  },
  {
    q: `aloud`,
    options: [`baland ovozda`, `to'da`, `inqilob`, `chaqish`],
    answer: 0,
  },
  { q: `bald`, options: [`kal`, `soxta`, `tering`, `tutilish`], answer: 0 },
  {
    q: `blanket`,
    options: [`adyol`, `dengiz`, `hovuz`, `bandargoh`],
    answer: 0,
  },
  {
    q: `creep`,
    options: [`o'rmalash`, `zaruriyat`, `dog '`, `o'z joniga qasd qilish`],
    answer: 0,
  },
  {
    q: `divorce`,
    options: [`ajralish`, `viloyat`, `qisqa vaqt ichida`, `qobiliyat`],
    answer: 0,
  },
  {
    q: `imitate`,
    options: [`taqlid qilish`, `somon`, `jazo`, `qasam iching`],
    answer: 0,
  },
  {
    q: `infant`,
    options: [`chaqaloq`, `shikoyat`, `ekspluatatsiya qilish`, `vayron qilish`],
    answer: 0,
  },
  {
    q: `kidnap`,
    options: [`o'g'irlash`, `adabiy`, `muassasa`, `kamtarin`],
    answer: 0,
  },
  { q: `nap`, options: [`uyqu`, `tushish`, `bandaj`, `o'smir`], answer: 0 },
  {
    q: `nowhere`,
    options: [`hech qayerda`, `qoniqish`, `qasos`, `mer`],
    answer: 0,
  },
  { q: `pat`, options: [`pat`, `alanga`, `paydo bo'ladi`, `atir`], answer: 0 },
  {
    q: `relief`,
    options: [`yengillik`, `port`, `hech qayerda`, `qobiq`],
    answer: 0,
  },
  {
    q: `reproduce`,
    options: [`ko'paytirish`, `shoshilinch`, `tushish`, `fojiali`],
    answer: 0,
  },
  {
    q: `rhyme`,
    options: [`qofiya`, `savob`, `va'z qilish`, `quvnoq`],
    answer: 0,
  },
  { q: `suck`, options: [`emish`, `don`, `xalat`, `insoniyat`], answer: 0 },
  {
    q: `urgent`,
    options: [`shoshilinch`, `xira`, `majburlash`, `barg`],
    answer: 0,
  },
  {
    q: `vanish`,
    options: [`g'oyib bo'lish`, `qurt`, `bum`, `ekotizim`],
    answer: 0,
  },
  {
    q: `wagon`,
    options: [`vagon`, `boshpana`, `optimist`, `umurtqa pog'onasi`],
    answer: 0,
  },
  { q: `wrinkle`, options: [`ajin`, `ajin`, `fojia`, `zabt etmoq`], answer: 0 },
  {
    q: `abnormal`,
    options: [`g'ayritabiiy`, `favvora`, `ochko'zlik`, `rahm-shafqat`],
    answer: 0,
  },
  {
    q: `bamboo`,
    options: [`bambuk`, `muntazam`, `shiddatli`, `kulba`],
    answer: 0,
  },
  {
    q: `blossom`,
    options: [`gullash`, `asabiylashtirmoq`, `bo'sh`, `yubiley`],
    answer: 0,
  },
  {
    q: `compass`,
    options: [`kompas`, `hislar`, `kulba`, `egri chiziq`],
    answer: 0,
  },
  {
    q: `dialect`,
    options: [`dialekt`, `lava`, `ochlik`, `lampochka`],
    answer: 0,
  },
  {
    q: `dishonest`,
    options: [`insofsiz`, `asfaltlash`, `aylantiring`, `momaqaldiroq`],
    answer: 0,
  },
  {
    q: `dwarf`,
    options: [`mitti`, `klan`, `uglevod`, `fil suyagi`],
    answer: 0,
  },
  {
    q: `ecosystem`,
    options: [`ekotizim`, `tasma`, `qoniqarli`, `jins`],
    answer: 0,
  },
  {
    q: `fatal`,
    options: [`halokatli`, `to'sqinlik qilmoq`, `mitti`, `belanchak`],
    answer: 0,
  },
  {
    q: `impatient`,
    options: [`sabrsiz`, `asbob`, `qovurilgan`, `kuyov`],
    answer: 0,
  },
  {
    q: `leaf`,
    options: [`barg`, `Javon`, `qo'rqitish`, `yo'qligi`],
    answer: 0,
  },
  {
    q: `manuscript`,
    options: [`qo'lyozmasi`, `kompas`, `puls`, `don`],
    answer: 0,
  },
  {
    q: `marsh`,
    options: [`botqoq`, `qabriston`, `yovuz`, `mos keladi`],
    answer: 0,
  },
  { q: `patience`, options: [`sabr`, `kesish`, `po'lat`, `dog '`], answer: 0 },
  {
    q: `perfume`,
    options: [`atir`, `qon ketish`, `ishontirmoq`, `adolat`],
    answer: 0,
  },
  { q: `pond`, options: [`hovuz`, `atir`, `ajin`, `sensatsiya`], answer: 0 },
  {
    q: `proverb`,
    options: [`maqol`, `isyonchi`, `portret`, `ajralish`],
    answer: 0,
  },
  {
    q: `pursuit`,
    options: [`ta'qib qilish`, `boshqarmoq`, `igna`, `maysazor`],
    answer: 0,
  },
  {
    q: `recite`,
    options: [`qiroat qilmoq`, `baca`, `uyat`, `jirkanch`],
    answer: 0,
  },
  {
    q: `wilderness`,
    options: [`cho'l`, `bosh irg'adi`, `noqulay`, `Aborigen`],
    answer: 0,
  },
  {
    q: `anticipate`,
    options: [`bashorat qilish`, `ta'qib qilish`, `illyuziya`, `oziqlantirish`],
    answer: 0,
  },
  { q: `barrel`, options: [`bochka`, `soxta`, `mer`, `insofsiz`], answer: 0 },
  { q: `beam`, options: [`nur`, `jins`, `sajda qilish`, `to'da`], answer: 0 },
  {
    q: `casual`,
    options: [`tasodifiy`, `diametri`, `oziqlantirish`, `somon`],
    answer: 0,
  },
  {
    q: `caution`,
    options: [`ehtiyot`, `iste'foga chiqish`, `qiyalik`, `qator`],
    answer: 0,
  },
  {
    q: `contrary`,
    options: [`aksincha`, `xafa qilish`, `kompensatsiya qilish`, `duradgor`],
    answer: 0,
  },
  {
    q: `deliberate`,
    options: [`ataylab`, `maxfiylik`, `yashash`, `to'kmoq`],
    answer: 0,
  },
  {
    q: `dissolve`,
    options: [`eritish`, `tashabbus`, `meros`, `to'sqinlik qilmoq`],
    answer: 0,
  },
  {
    q: `explode`,
    options: [`portlash`, `supurgi`, `qarag'ay`, `hakamlar hay'ati`],
    answer: 0,
  },
  {
    q: `fasten`,
    options: [`mahkamlang`, `kulba`, `muntazam`, `qutbli`],
    answer: 0,
  },
  {
    q: `germ`,
    options: [`mikrob`, `rashkchi`, `yeng`, `o'rmalash`],
    answer: 0,
  },
  { q: `kit`, options: [`to'plam`, `do'l`, `zarba`, `bosqin`], answer: 0 },
  { q: `puff`, options: [`puflash`, `hayratda`, `hamyon`, `poya`], answer: 0 },
  {
    q: `rag`,
    options: [`latta`, `rahm-shafqat`, `g'ayratli`, `orqali`],
    answer: 0,
  },
  {
    q: `scatter`,
    options: [`sochmoq`, `bosqin`, `tashabbus`, `voqea`],
    answer: 0,
  },
  {
    q: `scent`,
    options: [`hid`, `dengiz floti`, `xafa qilish`, `ixcham`],
    answer: 0,
  },
  {
    q: `steel`,
    options: [`po'lat`, `Kongress`, `Yuk`, `qonundan tashqari`],
    answer: 0,
  },
  {
    q: `swift`,
    options: [`tez`, `bambuk`, `ogohlantirish`, `halokatli`],
    answer: 0,
  },
  {
    q: `toss`,
    options: [`tashlamoq`, `oshirib yuborish`, `tan olmoq`, `kechir`],
    answer: 0,
  },
  {
    q: `triumph`,
    options: [`g'alaba`, `qochmoq`, `mikrob`, `tanqid`],
    answer: 0,
  },
  {
    q: `aboard`,
    options: [`bortida`, `tiklash`, `umurtqa pog'onasi`, `dengiz`],
    answer: 0,
  },
  {
    q: `bitter`,
    options: [`achchiq`, `to'lash`, `xurofot`, `boshlash`],
    answer: 0,
  },
  {
    q: `bullet`,
    options: [`o'q`, `tasvirlash`, `hayratda`, `sarg'ish`],
    answer: 0,
  },
  { q: `devil`, options: [`shayton`, `sehrgar`, `pat`, `instinkt`], answer: 0 },
  {
    q: `drift`,
    options: [`drift`, `xurofot`, `romashka`, `ittifoqdosh`],
    answer: 0,
  },
  {
    q: `enforce`,
    options: [`majburlash`, `egallash`, `nozik`, `tirnash`],
    answer: 0,
  },
  {
    q: `fountain`,
    options: [`favvora`, `inqilob`, `baland ovozda`, `senator`],
    answer: 0,
  },
  {
    q: `harbor`,
    options: [`bandargoh`, `uglevod`, `jinoyat`, `pechka`],
    answer: 0,
  },
  {
    q: `inhabit`,
    options: [`yashash`, `illyuziya`, `bezori`, `tushkunlikka tushirish`],
    answer: 0,
  },
  { q: `march`, options: [`marsh`, `ichi bo'sh`, `tez`, `qo'pol`], answer: 0 },
  {
    q: `millionaire`,
    options: [`millioner`, `iltifot`, `tasdiqlamoq`, `tong`],
    answer: 0,
  },
  {
    q: `port`,
    options: [`port`, `xayol`, `bosh irg'adi`, `ketish`],
    answer: 0,
  },
  {
    q: `sheriff`,
    options: [`sherif`, `ayni paytda`, `og'riq`, `e'tiborsizlik`],
    answer: 0,
  },
  {
    q: `startle`,
    options: [`hayratda`, `shayton`, `portlash`, `sayohat`],
    answer: 0,
  },
  {
    q: `sweat`,
    options: [`ter`, `qo'rqitish`, `qochmoq`, `dorixona`],
    answer: 0,
  },
  { q: `trigger`, options: [`tetik`, `konsol`, `bochka`, `oshpaz`], answer: 0 },
  {
    q: `unify`,
    options: [`birlashtirish`, `kanal`, `oshirib yuborish`, `yashirincha`],
    answer: 0,
  },
  { q: `vessel`, options: [`kema`, `homilador`, `skelet`, `soxta`], answer: 0 },
  {
    q: `voyage`,
    options: [`sayohat`, `etim`, `cho'l`, `sertifikat`],
    answer: 0,
  },
  {
    q: `worship`,
    options: [`sajda qilish`, `bandargoh`, `achchiq`, `xayoliy`],
    answer: 0,
  },
  {
    q: `apprentice`,
    options: [`shogird`, `tasodifiy`, `erkinlik`, `port`],
    answer: 0,
  },
  {
    q: `assure`,
    options: [`ishontirmoq`, `Yuk`, `eritish`, `tasodifiy`],
    answer: 0,
  },
  {
    q: `bandage`,
    options: [`bandaj`, `g'alaba`, `boshpana`, `baland ovozda`],
    answer: 0,
  },
  {
    q: `bleed`,
    options: [`qon ketish`, `sarson-sargardon`, `janjal`, `gunoh`],
    answer: 0,
  },
  { q: `bond`, options: [`rishta`, `hid`, `toj`, `hech qayerda`], answer: 0 },
  {
    q: `chef`,
    options: [`oshpaz`, `adolat`, `tortma`, `g'ayritabiiy`],
    answer: 0,
  },
  {
    q: `crown`,
    options: [`toj`, `chaqmoq`, `bashorat qilish`, `ritsar`],
    answer: 0,
  },
  {
    q: `departure`,
    options: [`ketish`, `qovog'ini burish`, `qo'shinlar`, `qarash`],
    answer: 0,
  },
  {
    q: `diligent`,
    options: [`mehnatsevar`, `erkinlik`, `ekspeditsiya`, `ulkan`],
    answer: 0,
  },
  {
    q: `emperor`,
    options: [`imperator`, `mahkamlang`, `insoniyat`, `qalay`],
    answer: 0,
  },
  {
    q: `fiber`,
    options: [`tola`, `bashorat qilish`, `chaqish`, `mitti`],
    answer: 0,
  },
  {
    q: `horrible`,
    options: [`dahshatli`, `sertifikat`, `odatlangan`, `qoramol`],
    answer: 0,
  },
  {
    q: `impolite`,
    options: [`qo'pol`, `ixcham`, `qayg'u`, `xayrixoh`],
    answer: 0,
  },
  {
    q: `kneel`,
    options: [`tiz cho'kish`, `engish`, `orqa`, `yostiq`],
    answer: 0,
  },
  {
    q: `luxury`,
    options: [`hashamatli`, `ketish`, `sakrash`, `ortiqcha vazn`],
    answer: 0,
  },
  {
    q: `massive`,
    options: [`katta`, `sxema`, `minnatdor`, `qo'shma`],
    answer: 0,
  },
  {
    q: `panic`,
    options: [`vahima`, `bosh suyagi`, `yubiley`, `zaxira`],
    answer: 0,
  },
  {
    q: `priority`,
    options: [`ustuvorlik`, `portret`, `yashirincha`, `ostida`],
    answer: 0,
  },
  { q: `robe`, options: [`xalat`, `bomba`, `hayajon`, `hayotiy`], answer: 0 },
  {
    q: `scold`,
    options: [`tanbeh`, `dahshat`, `tan olmoq`, `poda`],
    answer: 0,
  },
  {
    q: `affair`,
    options: [`ish`, `quchoqlash`, `bosh suyagi`, `asbob`],
    answer: 0,
  },
  {
    q: `assembly`,
    options: [`yig'ilish`, `vaziyat`, `aksirish`, `qasos`],
    answer: 0,
  },
  {
    q: `bless`,
    options: [`baraka ber`, `jinoyat`, `ehtiyot`, `niqoblash`],
    answer: 0,
  },
  {
    q: `cereal`,
    options: [`don`, `yovuz`, `taqiqlash`, `sarson-sargardon`],
    answer: 0,
  },
  {
    q: `cheerful`,
    options: [`quvnoq`, `tutmoq`, `o'z joniga qasd qilish`, `qimmatli`],
    answer: 0,
  },
  {
    q: `diameter`,
    options: [`diametri`, `skelet`, `shogird`, `chekinmoq`],
    answer: 0,
  },
  {
    q: `exploit`,
    options: [`ekspluatatsiya qilish`, `bo'yoq`, `bola`, `drenaj`],
    answer: 0,
  },
  {
    q: `famine`,
    options: [`ochlik`, `qiynoqlar`, `qoramol`, `qattiq`],
    answer: 0,
  },
  {
    q: `harvest`,
    options: [`o'rim-yig'im`, `qiyalik`, `shishiradi`, `o'g'irlik`],
    answer: 0,
  },
  { q: `merry`, options: [`quvnoq`, `qobiq`, `natija`, `inqilob`], answer: 0 },
  { q: `nut`, options: [`yong'oq`, `sovuq`, `yostiq`, `quvnoq`], answer: 0 },
  {
    q: `pardon`,
    options: [`kechir`, `chaqish`, `tomosha`, `baxtsiz`],
    answer: 0,
  },
  {
    q: `pharaoh`,
    options: [`fir'avn`, `uchrashish`, `ail`, `qon ketish`],
    answer: 0,
  },
  { q: `ripe`, options: [`pishgan`, `insofsiz`, `yadroviy`, `Yuk`], answer: 0 },
  {
    q: `roast`,
    options: [`qovurilgan`, `shiddatli`, `pechka`, `puflash`],
    answer: 0,
  },
  {
    q: `routine`,
    options: [`muntazam`, `baraka ber`, `qabriston`, `sut mahsulotlari`],
    answer: 0,
  },
  {
    q: `scheme`,
    options: [`sxema`, `sug'urta`, `elchi`, `xafa qilish`],
    answer: 0,
  },
  { q: `slim`, options: [`nozik`, `shubhali`, `hasad`, `janjal`], answer: 0 },
  {
    q: `stove`,
    options: [`pechka`, `maqtanmoq`, `mehnatsevar`, `komissiya`],
    answer: 0,
  },
  {
    q: `theft`,
    options: [`o'g'irlik`, `pechka`, `sulola`, `vahima`],
    answer: 0,
  },
  {
    q: `adolescent`,
    options: [`o'smir`, `drift`, `mag'lubiyat`, `qarag'ay`],
    answer: 0,
  },
  {
    q: `aptitude`,
    options: [`qobiliyat`, `yo'qligi`, `uchrashish`, `aylantiring`],
    answer: 0,
  },
  {
    q: `compliment`,
    options: [`iltifot`, `gunoh`, `kimyogar`, `kechki ovqat`],
    answer: 0,
  },
  {
    q: `hinder`,
    options: [`to'sqinlik qilmoq`, `Yo'l bering`, `aylanish`, `sabr`],
    answer: 0,
  },
  {
    q: `journalism`,
    options: [`jurnalistika`, `efirga uzatish`, `temirchi`, `igna`],
    answer: 0,
  },
  {
    q: `jury`,
    options: [`hakamlar hay'ati`, `senator`, `kechiktirish`, `toj`],
    answer: 0,
  },
  {
    q: `justice`,
    options: [`adolat`, `simfoniya`, `tushkunlikka tushirish`, `o'tlamoq`],
    answer: 0,
  },
  {
    q: `liberty`,
    options: [`erkinlik`, `peri`, `topishmoq`, `ish`],
    answer: 0,
  },
  {
    q: `literary`,
    options: [`adabiy`, `ushlab turish`, `ambitsiyali`, `g'azab`],
    answer: 0,
  },
  {
    q: `pharmacy`,
    options: [`dorixona`, `qo'shma`, `boshlash`, `latta`],
    answer: 0,
  },
  {
    q: `pill`,
    options: [`hap`, `oshpaz`, `tuman`, `oshirib yuborish`],
    answer: 0,
  },
  {
    q: `presume`,
    options: [`taxmin qilish`, `elchi`, `kar`, `qo'rqitish`],
    answer: 0,
  },
  {
    q: `privacy`,
    options: [`maxfiylik`, `hukmron`, `bajarmoq`, `egallash`],
    answer: 0,
  },
  { q: `punishment`, options: [`jazo`, `kir yuvish`, `ip`, `tik`], answer: 0 },
  {
    q: `sensible`,
    options: [`oqilona`, `ambitsiyali`, `iyagi`, `hushtak chalish`],
    answer: 0,
  },
  {
    q: `slice`,
    options: [`tilim`, `nogironlik`, `qon ketish`, `kulgili`],
    answer: 0,
  },
  {
    q: `sorrow`,
    options: [`qayg'u`, `chayqalish`, `ushlab turish`, `tomosha`],
    answer: 0,
  },
  { q: `straw`, options: [`somon`, `eritish`, `kuz`, `bomba`], answer: 0 },
  {
    q: `swell`,
    options: [`shishiradi`, `ataylab`, `iste'foga chiqish`, `adyol`],
    answer: 0,
  },
  {
    q: `tidy`,
    options: [`toza`, `qaroqchi`, `hushtak chalish`, `chayqalish`],
    answer: 0,
  },
  {
    q: `affection`,
    options: [`mehr`, `duch kelmoq`, `shifokor`, `ochlik`],
    answer: 0,
  },
  {
    q: `agency`,
    options: [`agentlik`, `ajoyib`, `maydalash`, `porlash`],
    answer: 0,
  },
  { q: `ash`, options: [`kul`, `xususiyat`, `instinkt`, `shkaf`], answer: 0 },
  {
    q: `confine`,
    options: [`chegaralash`, `fojiali`, `iz`, `yopishtiring`],
    answer: 0,
  },
  {
    q: `dismiss`,
    options: [`ishdan bo'shatish`, `hushtak chalish`, `duradgor`, `rashkchi`],
    answer: 0,
  },
  {
    q: `erupt`,
    options: [`otilib chiqish`, `bug'doy`, `sug'urta`, `baca`],
    answer: 0,
  },
  {
    q: `fate`,
    options: [`taqdir`, `kub`, `sarson-sargardon`, `portativ`],
    answer: 0,
  },
  {
    q: `lava`,
    options: [`lava`, `sajda qilish`, `la'nat`, `navigatsiya qilish`],
    answer: 0,
  },
  { q: `miserable`, options: [`baxtsiz`, `qaysar`, `un`, `pat`], answer: 0 },
  {
    q: `navigate`,
    options: [`navigatsiya qilish`, `uzoq`, `yong'oq`, `hovuz`],
    answer: 0,
  },
  {
    q: `originate`,
    options: [
      `kelib chiqishi`,
      `mikroskop`,
      `sut mahsulotlari`,
      `ishdan bo'shatish`,
    ],
    answer: 0,
  },
  {
    q: `remainder`,
    options: [`qolgan`, `drenaj`, `qimmatli`, `dahshatga tushgan`],
    answer: 0,
  },
  {
    q: `retrieve`,
    options: [`olish`, `stack`, `uzoq`, `baland tog'lar`],
    answer: 0,
  },
  {
    q: `shallow`,
    options: [`sayoz`, `mazax qilish`, `latta`, `portlash`],
    answer: 0,
  },
  {
    q: `slope`,
    options: [`qiyalik`, `og'riq`, `qo'pol`, `vasvasaga solmoq`],
    answer: 0,
  },
  { q: `span`, options: [`oraliq`, `olish`, `tark etmoq`, `marsh`], answer: 0 },
  {
    q: `superstition`,
    options: [`xurofot`, `fojia`, `zabt etmoq`, `iste'foga chiqish`],
    answer: 0,
  },
  {
    q: `sympathy`,
    options: [`hamdardlik`, `ko'paytirish`, `voqea`, `dahshatli`],
    answer: 0,
  },
  {
    q: `vibrate`,
    options: [`tebranish`, `e'tiborsizlik`, `hayratda`, `chirigan`],
    answer: 0,
  },
  {
    q: `wander`,
    options: [`sarson-sargardon`, `tiz cho'kish`, `sochmoq`, `supurgi`],
    answer: 0,
  },
  {
    q: `armor`,
    options: [`zirh`, `ehtiyot`, `sabrsiz`, `hamdardlik`],
    answer: 0,
  },
  { q: `blaze`, options: [`alanga`, `shkaf`, `ostida`, `ajin`], answer: 0 },
  { q: `boom`, options: [`bum`, `tirnash`, `aksincha`, `chop`], answer: 0 },
  {
    q: `cliff`,
    options: [`qoya`, `voqea`, `davom eting`, `tırtıl`],
    answer: 0,
  },
  { q: `flame`, options: [`olov`, `puflash`, `do'l`, `quchoqlash`], answer: 0 },
  {
    q: `independence`,
    options: [`mustaqillik`, `baqqol`, `vahima`, `cho'l`],
    answer: 0,
  },
  {
    q: `invasion`,
    options: [`bosqin`, `sochmoq`, `asfaltlash`, `uyqu`],
    answer: 0,
  },
  {
    q: `knight`,
    options: [`ritsar`, `otilib chiqish`, `yengillik`, `bandaj`],
    answer: 0,
  },
  {
    q: `lightning`,
    options: [`chaqmoq`, `qisqa vaqt ichida`, `qo'lyozmasi`, `valentin`],
    answer: 0,
  },
  {
    q: `rebel`,
    options: [`isyonchi`, `ob'ekt`, `byulleten`, `birlashtirish`],
    answer: 0,
  },
  {
    q: `retreat`,
    options: [`chekinish`, `aylanish`, `momaqaldiroq`, `ichi bo'sh`],
    answer: 0,
  },
  {
    q: `revolution`,
    options: [`inqilob`, `chirigan`, `dorixona`, `vaziyat`],
    answer: 0,
  },
  {
    q: `spear`,
    options: [`nayza`, `zabt etmoq`, `parchalanish`, `marjon`],
    answer: 0,
  },
  { q: `steep`, options: [`tik`, `to'plam`, `doza`, `buzmoq`], answer: 0 },
  {
    q: `summit`,
    options: [`sammit`, `taxmin qilish`, `vasvasaga solmoq`, `uglevod`],
    answer: 0,
  },
  {
    q: `thunder`,
    options: [`momaqaldiroq`, `toza`, `ayni paytda`, `kub`],
    answer: 0,
  },
  {
    q: `troops`,
    options: [`qo'shinlar`, `iyagi`, `Javon`, `muloyim`],
    answer: 0,
  },
  {
    q: `warrior`,
    options: [`jangchi`, `botqoq`, `artib oling`, `arktika`],
    answer: 0,
  },
  {
    q: `withdraw`,
    options: [`chekinmoq`, `cho'l`, `tirsak`, `ikkilanish`],
    answer: 0,
  },
  {
    q: `yield`,
    options: [`Yo'l bering`, `titramoq`, `bomba`, `bola`],
    answer: 0,
  },
  {
    q: `bench`,
    options: [`skameyka`, `quvnoq`, `to'lash`, `og'riq`],
    answer: 0,
  },
  {
    q: `confront`,
    options: [`duch kelmoq`, `bochka`, `bayram`, `narvon`],
    answer: 0,
  },
  { q: `daisy`, options: [`romashka`, `aksincha`, `ish`, `klan`], answer: 0 },
  { q: `dispute`, options: [`bahs`, `chiroq`, `sovuq`, `skameyka`], answer: 0 },
  { q: `horror`, options: [`dahshat`, `bahs`, `klan`, `xurofot`], answer: 0 },
  {
    q: `incident`,
    options: [`voqea`, `majburlash`, `baland tog'lar`, `ajoyib`],
    answer: 0,
  },
  {
    q: `mist`,
    options: [`tuman`, `dorixona`, `yugurish`, `tegirmon`],
    answer: 0,
  },
  {
    q: `object`,
    options: [`ob'ekt`, `tutilish`, `millioner`, `viloyat`],
    answer: 0,
  },
  {
    q: `orphan`,
    options: [`etim`, `bostirib kirish`, `adyol`, `qo'riqchi`],
    answer: 0,
  },
  {
    q: `plot`,
    options: [`uchastka`, `oqish`, `yig'ilish`, `isyonchi`],
    answer: 0,
  },
  {
    q: `pregnant`,
    options: [`homilador`, `va'z qilish`, `nayza`, `elchi`],
    answer: 0,
  },
  {
    q: `rage`,
    options: [`g'azab`, `ekspeditsiya`, `kechki ovqat`, `qurt`],
    answer: 0,
  },
  {
    q: `revenge`,
    options: [`qasos`, `ekotizim`, `chop`, `agentlik`],
    answer: 0,
  },
  { q: `shame`, options: [`uyat`, `tortma`, `porlash`, `ehtiyot`], answer: 0 },
  {
    q: `sigh`,
    options: [`xo'rsinmoq`, `natija`, `shubhali`, `tobut`],
    answer: 0,
  },
  {
    q: `sneak`,
    options: [`yashirincha`, `paydo bo'ladi`, `chekka`, `bostirib kirish`],
    answer: 0,
  },
  {
    q: `spare`,
    options: [`zaxira`, `oziqlantirish`, `kunduzi`, `boshqarmoq`],
    answer: 0,
  },
  {
    q: `stem`,
    options: [`poya`, `o'rim-yig'im`, `xo'rsinmoq`, `qaroqchi`],
    answer: 0,
  },
  {
    q: `supper`,
    options: [`kechki ovqat`, `shirinlik`, `qattiq`, `shiddatli`],
    answer: 0,
  },
  {
    q: `tender`,
    options: [`tender`, `niqoblash`, `otilib chiqish`, `odatlangan`],
    answer: 0,
  },
  {
    q: `beneath`,
    options: [`ostida`, `vagon`, `tiklash`, `ekspeditsiya`],
    answer: 0,
  },
  { q: `cub`, options: [`kub`, `kema`, `qiroat qilmoq`, `sayoz`], answer: 0 },
  { q: `dawn`, options: [`tong`, `qovurilgan`, `oliy`, `oliy`], answer: 0 },
  {
    q: `dissatisfied`,
    options: [`norozi`, `halokatli`, `o'zgartirish`, `kompensatsiya qilish`],
    answer: 0,
  },
  { q: `ease`, options: [`yengillik`, `sulola`, `bambuk`, `yeng`], answer: 0 },
  { q: `evident`, options: [`aniq`, `nozik`, `to'plam`, `bahs`], answer: 0 },
  {
    q: `hail`,
    options: [`do'l`, `qiroat qilmoq`, `vayron qilish`, `tebranish`],
    answer: 0,
  },
  {
    q: `howl`,
    options: [`qichqirmoq`, `mustaqillik`, `qobiq`, `homilador`],
    answer: 0,
  },
  { q: `leap`, options: [`sakrash`, `tiyin`, `bay`, `tetik`], answer: 0 },
  {
    q: `magnificent`,
    options: [`ajoyib`, `tong`, `sehrgar`, `divan`],
    answer: 0,
  },
  {
    q: `necessity`,
    options: [`zaruriyat`, `momaqaldiroq`, `olish`, `tark etmoq`],
    answer: 0,
  },
  {
    q: `outcome`,
    options: [`natija`, `rishta`, `chaqmoq`, `ta'qib qilish`],
    answer: 0,
  },
  { q: `pile`, options: [`qoziq`, `latta`, `qolgan`, `nogironlik`], answer: 0 },
  {
    q: `profound`,
    options: [`chuqur`, `valentin`, `shikoyat`, `sovuq`],
    answer: 0,
  },
  {
    q: `seize`,
    options: [`tutmoq`, `yashirincha`, `e'tiborsizlik`, `havzasi`],
    answer: 0,
  },
  {
    q: `squeeze`,
    options: [`siqish`, `jangchi`, `sarlavha`, `qochmoq`],
    answer: 0,
  },
  {
    q: `supreme`,
    options: [`oliy`, `suvenir`, `quvnoq`, `xayriya`],
    answer: 0,
  },
  {
    q: `terrific`,
    options: [`ajoyib`, `bolta`, `zaruriyat`, `qurbon qilish`],
    answer: 0,
  },
  {
    q: `trait`,
    options: [`xususiyat`, `navigatsiya qilish`, `munosib`, `hislar`],
    answer: 0,
  },
  {
    q: `vital`,
    options: [`hayotiy`, `tayoq`, `chorvachilik`, `ko'mir`],
    answer: 0,
  },
  {
    q: `accustomed`,
    options: [`odatlangan`, `yeng`, `bolta`, `chegaralash`],
    answer: 0,
  },
  {
    q: `affirm`,
    options: [`tasdiqlamoq`, `savdogar`, `kechir`, `uzoq`],
    answer: 0,
  },
  {
    q: `astonished`,
    options: [`hayratda`, `davom eting`, `ish`, `tirsak`],
    answer: 0,
  },
  {
    q: `bang`,
    options: [`portlash`, `qurbon qilish`, `hap`, `tikish`],
    answer: 0,
  },
  { q: `clan`, options: [`klan`, `ish`, `tender`, `etim`], answer: 0 },
  { q: `dim`, options: [`xira`, `arktika`, `nashr`, `soqol olish`], answer: 0 },
  {
    q: `emphasis`,
    options: [`ta'kidlash`, `chana`, `rishta`, `shirinlik`],
    answer: 0,
  },
  {
    q: `fable`,
    options: [`ertak`, `tola`, `leytenant`, `tomizish`],
    answer: 0,
  },
  {
    q: `feast`,
    options: [`bayram`, `hamyon`, `ta'qib qilish`, `pok`],
    answer: 0,
  },
  {
    q: `glow`,
    options: [`porlash`, `vayron qilish`, `qutbli`, `otashinlar`],
    answer: 0,
  },
  {
    q: `hollow`,
    options: [`ichi bo'sh`, `po'lat`, `qaysar`, `puls`],
    answer: 0,
  },
  {
    q: `instinct`,
    options: [`instinkt`, `kasr`, `savob`, `oraliq`],
    answer: 0,
  },
  {
    q: `joint`,
    options: [`qo'shma`, `o'smir`, `qo'riqchi`, `simfoniya`],
    answer: 0,
  },
  { q: `leak`, options: [`oqish`, `hasad`, `marjon`, `maydalash`], answer: 0 },
  {
    q: `physician`,
    options: [`shifokor`, `haqorat qilish`, `imperator`, `tortma`],
    answer: 0,
  },
  {
    q: `sacrifice`,
    options: [`qurbon qilish`, `zanjabil`, `agentlik`, `gullash`],
    answer: 0,
  },
  { q: `stiff`, options: [`qattiq`, `sayohat`, `ajoyib`, `jazo`], answer: 0 },
  {
    q: `stroke`,
    options: [`insult`, `optimist`, `raqib`, `chiziq`],
    answer: 0,
  },
  {
    q: `tragic`,
    options: [`fojiali`, `ekspluatatsiya qilish`, `tutmoq`, `la'nat`],
    answer: 0,
  },
  {
    q: `tune`,
    options: [`kuylash`, `sakrash`, `suv osti kemasi`, `o'rim-yig'im`],
    answer: 0,
  },
  {
    q: `accommodate`,
    options: [`joylashtirmoq`, `jurnalistika`, `ixcham`, `yashovchi`],
    answer: 0,
  },
  { q: `circus`, options: [`sirk`, `plakat`, `kuchlanish`, `kema`], answer: 0 },
  {
    q: `coincide`,
    options: [`mos keladi`, `shishiradi`, `ziravorlar`, `kuchlanish`],
    answer: 0,
  },
  {
    q: `commission`,
    options: [`komissiya`, `chetga`, `dahshatli`, `muassasa`],
    answer: 0,
  },
  { q: `dose`, options: [`doza`, `inoyat`, `ehtiros`, `bayram`], answer: 0 },
  {
    q: `dye`,
    options: [`bo'yoq`, `ehtiyotkor`, `sensatsiya`, `kasr`],
    answer: 0,
  },
  {
    q: `extent`,
    options: [`darajada`, `yubiley`, `kurash`, `yashash`],
    answer: 0,
  },
  { q: `gender`, options: [`jins`, `ish`, `xususiyat`, `uyat`], answer: 0 },
  {
    q: `headline`,
    options: [`sarlavha`, `pat`, `ishdan bo'shatish`, `qabriston`],
    answer: 0,
  },
  {
    q: `informal`,
    options: [`norasmiy`, `dahshatga tushgan`, `aralashtirmoq`, `shifokor`],
    answer: 0,
  },
  {
    q: `inquire`,
    options: [`so'ramoq`, `tirsak`, `maysazor`, `nozik`],
    answer: 0,
  },
  {
    q: `messenger`,
    options: [`xabarchi`, `romashka`, `dialekt`, `bosh suyagi`],
    answer: 0,
  },
  { q: `peer`, options: [`tengdosh`, `tengdosh`, `botqoq`, `toza`], answer: 0 },
  {
    q: `portrait`,
    options: [`portret`, `lampochka`, `tikish`, `turar joy`],
    answer: 0,
  },
  {
    q: `pose`,
    options: [`poza`, `sensatsiya`, `jun`, `sharmandalik`],
    answer: 0,
  },
  {
    q: `ranch`,
    options: [`chorvachilik`, `hakamlar hay'ati`, `g'oyib bo'lish`, `asab`],
    answer: 0,
  },
  {
    q: `steer`,
    options: [`boshqarmoq`, `ertak`, `hayotiy`, `tender`],
    answer: 0,
  },
  {
    q: `stripe`,
    options: [`chiziq`, `toj`, `qobiliyat`, `e'tiborsizlik`],
    answer: 0,
  },
  { q: `tame`, options: [`muloyim`, `vahima`, `jilo`, `ter`], answer: 0 },
  {
    q: `tempt`,
    options: [`vasvasaga solmoq`, `kvitansiya`, `tanishish`, `kuz`],
    answer: 0,
  },
  {
    q: `Aborigine`,
    options: [`Aborigen`, `oraliq`, `o'zaro`, `nafrat`],
    answer: 0,
  },
  {
    q: `ban`,
    options: [`taqiqlash`, `belanchak`, `ilgak`, `kechiktirish`],
    answer: 0,
  },
  {
    q: `cautious`,
    options: [`ehtiyotkor`, `turar joy`, `ataylab`, `chekinish`],
    answer: 0,
  },
  {
    q: `confess`,
    options: [`tan olmoq`, `yig'ilish`, `efirga uzatish`, `mahkamlang`],
    answer: 0,
  },
  {
    q: `cottage`,
    options: [`yozgi uy`, `yuqoriga`, `suvenir`, `nur`],
    answer: 0,
  },
  {
    q: `daytime`,
    options: [`kunduzi`, `kimyogar`, `temir`, `zirh`],
    answer: 0,
  },
  {
    q: `desperate`,
    options: [`umidsiz`, `qattiq`, `tobut`, `sakrash`],
    answer: 0,
  },
  {
    q: `fade`,
    options: [`so'nish`, `yangilash`, `ketish`, `shoshilinch`],
    answer: 0,
  },
  {
    q: `fierce`,
    options: [`shiddatli`, `xiyobon`, `chegaralash`, `qovog'ini burish`],
    answer: 0,
  },
  {
    q: `gamble`,
    options: [`qimor o'ynash`, `norasmiy`, `duch kelmoq`, `bo'sh`],
    answer: 0,
  },
  {
    q: `lawn`,
    options: [`maysazor`, `kuyov`, `Kongress`, `surtish`],
    answer: 0,
  },
  {
    q: `mow`,
    options: [`eymoq`, `kelib chiqishi`, `savdogar`, `taqiqlash`],
    answer: 0,
  },
  {
    q: `outlaw`,
    options: [`qonundan tashqari`, `porlash`, `norozi`, `ob'ekt`],
    answer: 0,
  },
  {
    q: `prospect`,
    options: [`istiqbol`, `kaput`, `og'riq`, `tiyin`],
    answer: 0,
  },
  { q: `purse`, options: [`hamyon`, `o'zaro`, `baxtsiz`, `savob`], answer: 0 },
  { q: `rod`, options: [`tayoq`, `sirk`, `kasr`, `minnatdor`], answer: 0 },
  {
    q: `seldom`,
    options: [`kamdan-kam hollarda`, `baxtsiz`, `ta'qib qilish`, `adabiy`],
    answer: 0,
  },
  {
    q: `shave`,
    options: [`soqol olish`, `foydalanish`, `cho'milish`, `cho'kmoq`],
    answer: 0,
  },
  {
    q: `terrified`,
    options: [`dahshatga tushgan`, `tan olmoq`, `nur`, `ochlik`],
    answer: 0,
  },
  {
    q: `wizard`,
    options: [`sehrgar`, `ulkan`, `chirigan`, `qiyalik`],
    answer: 0,
  },
  {
    q: `baggage`,
    options: [`Yuk`, `g'oyib bo'lish`, `qarash`, `sarlavha`],
    answer: 0,
  },
  {
    q: `bulb`,
    options: [`lampochka`, `tez`, `gullash`, `qimor o'ynash`],
    answer: 0,
  },
  {
    q: `bundle`,
    options: [`to'plam`, `orqali`, `baqqol`, `insult`],
    answer: 0,
  },
  { q: `cattle`, options: [`qoramol`, `qoya`, `pastroq`, `poza`], answer: 0 },
  {
    q: `flee`,
    options: [`qochmoq`, `yashovchi`, `inoyat`, `hayratda`],
    answer: 0,
  },
  {
    q: `graze`,
    options: [`o'tlamoq`, `tan olmoq`, `sxema`, `xira`],
    answer: 0,
  },
  {
    q: `greed`,
    options: [`ochko'zlik`, `tegirmon`, `favvora`, `sammit`],
    answer: 0,
  },
  {
    q: `herd`,
    options: [`poda`, `e'tiborsizlik`, `xabarchi`, `darajada`],
    answer: 0,
  },
  {
    q: `initiate`,
    options: [`boshlash`, `quvnoq`, `sarg'ish`, `qo'lyozmasi`],
    answer: 0,
  },
  { q: `lane`, options: [`qator`, `bum`, `qiynoqlar`, `olish`], answer: 0 },
  {
    q: `nerve`,
    options: [`asab`, `portlash`, `ortiqcha vazn`, `kuylash`],
    answer: 0,
  },
  {
    q: `optimist`,
    options: [`optimist`, `leytenant`, `kamtarin`, `uyaldi`],
    answer: 0,
  },
  {
    q: `parade`,
    options: [`parad`, `qo'riqchi`, `supurgi`, `pishgan`],
    answer: 0,
  },
  { q: `pave`, options: [`asfaltlash`, `igna`, `qator`, `kanal`], answer: 0 },
  {
    q: `phantom`,
    options: [`xayol`, `chekinish`, `Aborigen`, `baraka ber`],
    answer: 0,
  },
  {
    q: `portable`,
    options: [`portativ`, `norozi`, `orqali`, `tiz cho'kish`],
    answer: 0,
  },
  {
    q: `poster`,
    options: [`plakat`, `qalay`, `chaqaloq`, `hayratda`],
    answer: 0,
  },
  {
    q: `scratch`,
    options: [`tirnash`, `tanbeh`, `qayg'u`, `yengillik`],
    answer: 0,
  },
  {
    q: `symphony`,
    options: [`simfoniya`, `ajoyib`, `quchoqlash`, `bug'doy`],
    answer: 0,
  },
  {
    q: `widow`,
    options: [`beva ayol`, `munosib`, `yuqoriga`, `sug'urta`],
    answer: 0,
  },
  {
    q: `circulate`,
    options: [`aylanish`, `oqlangan`, `qofiya`, `uchastka`],
    answer: 0,
  },
  {
    q: `consequent`,
    options: [`natijada`, `nashr`, `buzmoq`, `kunduzi`],
    answer: 0,
  },
  {
    q: `derive`,
    options: [`hosil qilish`, `cho'pon`, `tanbeh`, `ip`],
    answer: 0,
  },
  {
    q: `drown`,
    options: [`cho'kmoq`, `artib oling`, `xayoliy`, `jurnalistika`],
    answer: 0,
  },
  {
    q: `dynasty`,
    options: [`sulola`, `torting`, `etim`, `sabrsiz`],
    answer: 0,
  },
  { q: `fraction`, options: [`kasr`, `nafrat`, `sammit`, `sxema`], answer: 0 },
  {
    q: `frost`,
    options: [`sovuq`, `hosil qilish`, `o'g'irlash`, `temir`],
    answer: 0,
  },
  {
    q: `illusion`,
    options: [`illyuziya`, `raqib`, `jurnalistika`, `tering`],
    answer: 0,
  },
  {
    q: `invade`,
    options: [`bostirib kirish`, `litsenziya`, `vagon`, `chana`],
    answer: 0,
  },
  {
    q: `lieutenant`,
    options: [`leytenant`, `dialekt`, `g'ayritabiiy`, `taqdir`],
    answer: 0,
  },
  {
    q: `marine`,
    options: [`dengiz`, `ajralish`, `ostida`, `nashr`],
    answer: 0,
  },
  {
    q: `merit`,
    options: [`savob`, `temir`, `otashinlar`, `sajda qilish`],
    answer: 0,
  },
  {
    q: `navy`,
    options: [`dengiz floti`, `hayotiy`, `gorizont`, `chandiq`],
    answer: 0,
  },
  {
    q: `polar`,
    options: [`qutbli`, `chorvachilik`, `parad`, `yong'oq`],
    answer: 0,
  },
  {
    q: `ray`,
    options: [`nur`, `hop`, `ichi bo'sh`, `haqorat qilish`],
    answer: 0,
  },
  {
    q: `resign`,
    options: [`iste'foga chiqish`, `adyol`, `shkaf`, `ekspluatatsiya qilish`],
    answer: 0,
  },
  {
    q: `suicide`,
    options: [`o'z joniga qasd qilish`, `meros`, `o'rim-yig'im`, `sulola`],
    answer: 0,
  },
  {
    q: `tremble`,
    options: [`titramoq`, `portlash`, `valentin`, `olov`],
    answer: 0,
  },
  {
    q: `underlying`,
    options: [`asosida`, `kurash`, `bahs`, `shubhali`],
    answer: 0,
  },
  { q: `via`, options: [`orqali`, `la'nat`, `o'rmalash`, `hasad`], answer: 0 },
  {
    q: `alter`,
    options: [`o'zgartirish`, `tender`, `turar joy`, `mikrob`],
    answer: 0,
  },
  { q: `aside`, options: [`chetga`, `yengillik`, `divan`, `drift`], answer: 0 },
  { q: `autumn`, options: [`kuz`, `kuz`, `qurt`, `kal`], answer: 0 },
  {
    q: `blend`,
    options: [`aralashtirmoq`, `qo'lyozmasi`, `chayqalish`, `efirga uzatish`],
    answer: 0,
  },
  {
    q: `collapse`,
    options: [`qulash`, `chidamoq`, `pok`, `qiroat qilmoq`],
    answer: 0,
  },
  {
    q: `crush`,
    options: [`maydalash`, `jun`, `sirk`, `ishontirmoq`],
    answer: 0,
  },
  { q: `curve`, options: [`egri chiziq`, `hap`, `qoya`, `botqoq`], answer: 0 },
  {
    q: `disgusting`,
    options: [`jirkanch`, `millioner`, `chuqur`, `aksincha`],
    answer: 0,
  },
  {
    q: `drain`,
    options: [`drenaj`, `pok`, `bostirib kirish`, `kecha davomida`],
    answer: 0,
  },
  {
    q: `embrace`,
    options: [`quchoqlash`, `uyaldi`, `to'plam`, `asosida`],
    answer: 0,
  },
  {
    q: `envy`,
    options: [`hasad`, `kamtarin`, `egallash`, `arifmetik`],
    answer: 0,
  },
  {
    q: `fireworks`,
    options: [`otashinlar`, `o'z joniga qasd qilish`, `nogironlik`, `kompas`],
    answer: 0,
  },
  { q: `flour`, options: [`un`, `ehtiros`, `qaroqchi`, `sochmoq`], answer: 0 },
  {
    q: `fuse`,
    options: [`sug'urta`, `qutbli`, `xayol`, `diametri`],
    answer: 0,
  },
  {
    q: `ginger`,
    options: [`zanjabil`, `kuchlanish`, `viloyat`, `hap`],
    answer: 0,
  },
  {
    q: `jealous`,
    options: [`rashkchi`, `kompensatsiya qilish`, `hop`, `maxfiylik`],
    answer: 0,
  },
  {
    q: `paste`,
    options: [`yopishtiring`, `ter`, `ikkilanish`, `ajoyib`],
    answer: 0,
  },
  {
    q: `receipt`,
    options: [`kvitansiya`, `sut mahsulotlari`, `niqoblash`, `yadroviy`],
    answer: 0,
  },
  { q: `wipe`, options: [`artib oling`, `divan`, `nozik`, `katta`], answer: 0 },
  {
    q: `wire`,
    options: [`sim`, `ortiqcha vazn`, `tutilish`, `tengdosh`],
    answer: 0,
  },
  {
    q: `acknowledge`,
    options: [`tan olmoq`, `insoniyat`, `uyqu`, `parad`],
    answer: 0,
  },
  {
    q: `ambassador`,
    options: [`elchi`, `o'tlamoq`, `gunoh`, `ustuvorlik`],
    answer: 0,
  },
  { q: `blonde`, options: [`sarg'ish`, `qator`, `poda`, `jilo`], answer: 0 },
  {
    q: `conquer`,
    options: [`zabt etmoq`, `ko'mir`, `port`, `asfaltlash`],
    answer: 0,
  },
  { q: `drag`, options: [`torting`, `boshlash`, `oqish`, `chuqur`], answer: 0 },
  {
    q: `exaggerate`,
    options: [`oshirib yuborish`, `ta'qib qilish`, `maqtanmoq`, `natijada`],
    answer: 0,
  },
  {
    q: `heritage`,
    options: [`meros`, `chiziq`, `Yo'l bering`, `g'oyib bo'lish`],
    answer: 0,
  },
  {
    q: `insult`,
    options: [`haqorat qilish`, `jilo`, `insofsiz`, `aldamoq`],
    answer: 0,
  },
  {
    q: `meanwhile`,
    options: [`ayni paytda`, `qarash`, `o'q`, `tasdiqlamoq`],
    answer: 0,
  },
  { q: `necklace`, options: [`marjon`, `to'lqin`, `nur`, `xalat`], answer: 0 },
  {
    q: `noble`,
    options: [`olijanob`, `tetik`, `boshqarmoq`, `noqulay`],
    answer: 0,
  },
  {
    q: `precious`,
    options: [`qimmatli`, `chaqaloq`, `konsol`, `aralashtirmoq`],
    answer: 0,
  },
  {
    q: `prejudice`,
    options: [`xurofot`, `g'ayratli`, `somon`, `qo'shinlar`],
    answer: 0,
  },
  {
    q: `rumor`,
    options: [`mish-mish`, `oshib ketish`, `so'nish`, `qofiya`],
    answer: 0,
  },
  {
    q: `sin`,
    options: [`gunoh`, `kulgili`, `istiqbol`, `byulleten`],
    answer: 0,
  },
  {
    q: `spectacle`,
    options: [`tomosha`, `yengillik`, `qasam iching`, `fir'avn`],
    answer: 0,
  },
  {
    q: `stack`,
    options: [`stack`, `emish`, `kuyov`, `taxmin qilish`],
    answer: 0,
  },
  {
    q: `suspicious`,
    options: [`shubhali`, `minnatdor`, `kvitansiya`, `dialekt`],
    answer: 0,
  },
  {
    q: `tin`,
    options: [`qalay`, `tikish`, `mazax qilish`, `soxta`],
    answer: 0,
  },
  {
    q: `vase`,
    options: [`vaza`, `temirchi`, `sertifikat`, `joylashtirmoq`],
    answer: 0,
  },
  {
    q: `ache`,
    options: [`og'riq`, `gullab-yashnamoq`, `qurbon qilish`, `hashamatli`],
    answer: 0,
  },
  {
    q: `arctic`,
    options: [`arktika`, `o'g'irlash`, `qonundan tashqari`, `plakat`],
    answer: 0,
  },
  { q: `canal`, options: [`kanal`, `mer`, `sabr`, `foydalanish`], answer: 0 },
  {
    q: `chemist`,
    options: [`kimyogar`, `surtish`, `narvon`, `ajoyib`],
    answer: 0,
  },
  {
    q: `chill`,
    options: [`sovuq`, `tutmoq`, `qarash`, `beva ayol`],
    answer: 0,
  },
  {
    q: `congress`,
    options: [`Kongress`, `janjal`, `drift`, `aksirish`],
    answer: 0,
  },
  {
    q: `dairy`,
    options: [`sut mahsulotlari`, `mikrob`, `drenaj`, `tan olmoq`],
    answer: 0,
  },
  {
    q: `descend`,
    options: [`tushish`, `xurofot`, `chidamoq`, `muntazam`],
    answer: 0,
  },
  { q: `grocer`, options: [`baqqol`, `ostida`, `peri`, `xurofot`], answer: 0 },
  {
    q: `hesitate`,
    options: [`ikkilanish`, `gorizont`, `ehtiyotkor`, `tiklash`],
    answer: 0,
  },
  {
    q: `institution`,
    options: [`muassasa`, `qo'pol`, `birlashtirish`, `ogohlantirish`],
    answer: 0,
  },
  {
    q: `jog`,
    options: [`yugurish`, `birlashtirish`, `to'sqinlik qilmoq`, `qoniqarli`],
    answer: 0,
  },
  {
    q: `merchant`,
    options: [`savdogar`, `egri chiziq`, `asbob`, `ta'qib qilish`],
    answer: 0,
  },
  {
    q: `poke`,
    options: [`pok`, `kecha davomida`, `uyaldi`, `siqish`],
    answer: 0,
  },
  {
    q: `postpone`,
    options: [`kechiktirish`, `nozik`, `ta'kidlash`, `ambitsiyali`],
    answer: 0,
  },
  {
    q: `splash`,
    options: [`chayqalish`, `qofiya`, `mikroskop`, `tilim`],
    answer: 0,
  },
  {
    q: `stubborn`,
    options: [`qaysar`, `noqulay`, `oqlangan`, `litsenziya`],
    answer: 0,
  },
  { q: `suburb`, options: [`chekka`, `o'q`, `kanal`, `shikoyat`], answer: 0 },
  { q: `tide`, options: [`to'lqin`, `kal`, `qimor o'ynash`, `bay`], answer: 0 },
  {
    q: `tragedy`,
    options: [`fojia`, `ikkilanish`, `maxfiylik`, `ziravorlar`],
    answer: 0,
  },
  {
    q: `bomb`,
    options: [`bomba`, `maysazor`, `paydo bo'ladi`, `tuman`],
    answer: 0,
  },
  {
    q: `certificate`,
    options: [`sertifikat`, `tanishish`, `isyonchi`, `savdogar`],
    answer: 0,
  },
  {
    q: `circumstance`,
    options: [`vaziyat`, `olov`, `arktika`, `xayol`],
    answer: 0,
  },
  {
    q: `coffin`,
    options: [`tobut`, `umurtqa pog'onasi`, `jirkanch`, `norozi`],
    answer: 0,
  },
  {
    q: `cope`,
    options: [`engish`, `imperator`, `iltifot`, `g'alaba`],
    answer: 0,
  },
  {
    q: `criticism`,
    options: [`tanqid`, `veterinar`, `tasma`, `bambuk`],
    answer: 0,
  },
  {
    q: `devastate`,
    options: [`vayron qilish`, `nur`, `bug'doy`, `iz`],
    answer: 0,
  },
  {
    q: `frown`,
    options: [`qovog'ini burish`, `bo'sh`, `to'da`, `tutmoq`],
    answer: 0,
  },
  {
    q: `gaze`,
    options: [`qarash`, `yopishtiring`, `baraka ber`, `shogird`],
    answer: 0,
  },
  {
    q: `glance`,
    options: [`qarash`, `mag'lubiyat`, `taqdir`, `maqtanmoq`],
    answer: 0,
  },
  {
    q: `grief`,
    options: [`qayg'u`, `tik`, `ajoyib`, `parchalanish`],
    answer: 0,
  },
  {
    q: `groom`,
    options: [`kuyov`, `arifmetik`, `engish`, `iltifot`],
    answer: 0,
  },
  {
    q: `license`,
    options: [`litsenziya`, `qichqirmoq`, `sayohat`, `ehtiros`],
    answer: 0,
  },
  {
    q: `microscope`,
    options: [`mikroskop`, `asab`, `torting`, `mehr`],
    answer: 0,
  },
  {
    q: `nuclear`,
    options: [`yadroviy`, `narvon`, `soxta`, `qayg'u`],
    answer: 0,
  },
  {
    q: `portray`,
    options: [`tasvirlash`, `ta'kidlash`, `toza`, `qulash`],
    answer: 0,
  },
  {
    q: `rotate`,
    options: [`aylantiring`, `tanqid`, `sherif`, `ertak`],
    answer: 0,
  },
  {
    q: `souvenir`,
    options: [`suvenir`, `chandiq`, `bandargoh`, `norasmiy`],
    answer: 0,
  },
  {
    q: `submarine`,
    options: [`suv osti kemasi`, `puls`, `oshpaz`, `ehtiyotkor`],
    answer: 0,
  },
  {
    q: `trace`,
    options: [`iz`, `ziravorlar`, `tola`, `mustaqillik`],
    answer: 0,
  },
  {
    q: `appliance`,
    options: [`asbob`, `egallash`, `joylashtirmoq`, `tashabbus`],
    answer: 0,
  },
  {
    q: `basin`,
    options: [`havzasi`, `yong'oq`, `hid`, `ushlab turish`],
    answer: 0,
  },
  {
    q: `broom`,
    options: [`supurgi`, `fil suyagi`, `asosida`, `erkinlik`],
    answer: 0,
  },
  {
    q: `caterpillar`,
    options: [`tırtıl`, `hech qayerda`, `bo'yoq`, `asabiylashtirmoq`],
    answer: 0,
  },
  {
    q: `cupboard`,
    options: [`Javon`, `siqish`, `oqilona`, `ilgak`],
    answer: 0,
  },
  {
    q: `delicate`,
    options: [`nozik`, `aylantiring`, `jins`, `tola`],
    answer: 0,
  },
  {
    q: `emerge`,
    options: [`paydo bo'ladi`, `otashinlar`, `egri chiziq`, `baqqol`],
    answer: 0,
  },
  {
    q: `handicap`,
    options: [`nogironlik`, `yangi kelgan`, `gullash`, `yovuz`],
    answer: 0,
  },
  {
    q: `hook`,
    options: [`ilgak`, `umidsiz`, `jangchi`, `illyuziya`],
    answer: 0,
  },
  {
    q: `hop`,
    options: [`hop`, `raqib`, `dengiz floti`, `dengiz floti`],
    answer: 0,
  },
  {
    q: `laundry`,
    options: [`kir yuvish`, `ajoyib`, `vaziyat`, `sakrash`],
    answer: 0,
  },
  {
    q: `pursue`,
    options: [`ta'qib qilish`, `cho'milish`, `chetga`, `Yo'l bering`],
    answer: 0,
  },
  {
    q: `reluctant`,
    options: [`istaksiz`, `tomizish`, `yengillik`, `kar`],
    answer: 0,
  },
  { q: `sleeve`, options: [`yeng`, `mos keladi`, `kaput`, `bum`], answer: 0 },
  {
    q: `spine`,
    options: [`umurtqa pog'onasi`, `soqol olish`, `g'alaba`, `so'nish`],
    answer: 0,
  },
  {
    q: `stain`,
    options: [`dog '`, `o'zgartirish`, `dahshatga tushgan`, `hayajon`],
    answer: 0,
  },
  { q: `strip`, options: [`tasma`, `tırtıl`, `sovuq`, `skelet`], answer: 0 },
  {
    q: `swear`,
    options: [`qasam iching`, `ishontirmoq`, `zaxira`, `hukmron`],
    answer: 0,
  },
  {
    q: `swing`,
    options: [`belanchak`, `portlash`, `halokatli`, `bochka`],
    answer: 0,
  },
  {
    q: `utilize`,
    options: [`foydalanish`, `aldamoq`, `kuylash`, `to'plam`],
    answer: 0,
  },
];

console.log(quiz.length); // 55
console.log(quiz.length); // 55

// === in gitBash: ====
// node js/question13.js
