// **Question-13**
// *tayyor*
// # 1: Yuqoridagi hammat testlar (jami 460)
'use strick';
// Array of Object;
const quiz = [
  {
    en: 'blood',
    pron: '[blʌd] n.',
    desc: 'Blood is the red liquid in your body.',
    exam: 'I cut my finger and got <strong>blood </strong>on my shirt.',
    vi: '',
    image: '1241.jpg',
    sound: '1241.mp3',
    bookNumber: 1,
    id: 1241,
    uz: 'qon',
    uzOptions: ['qon', "zo'rg'a", 'mulk', "qandaydir yo'l bilan"],
    enOptions: ['blood', 'relax', 'appreciate', 'introduce'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'burn',
    pron: '[bəːn] v.',
    desc: 'To burn something is to set it on fire.',
    exam: 'I <strong>burned </strong>some wood in the camp fire.',
    vi: '',
    image: '1242.jpg',
    sound: '1242.mp3',
    bookNumber: 1,
    id: 1242,
    uz: 'kuymoq',
    uzOptions: ['kuymoq', 'hissiyot', 'tomoshabin', 'belgi'],
    enOptions: ['burn', 'yet', 'puzzle', 'magical'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'cell',
    pron: '[sɛl] n.',
    desc: 'A cell is a small room where a person is locked in.',
    exam: 'The jail <strong>cell </strong>was very small.',
    vi: '',
    image: '1243.jpg',
    sound: '1243.mp3',
    bookNumber: 1,
    id: 1243,
    uz: 'hujayra  panjara',
    uzOptions: ['hujayra  panjara', "qo'riqchi", 'mavjud', 'xabar'],
    enOptions: ['cell', 'wise', 'solve', 'meal'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'contain',
    pron: '[kənˈteɪn] v.',
    desc: 'To contain something is to have it inside.',
    exam: 'The mailbox <strong>contained </strong>a letter.',
    vi: '',
    image: '1244.jpg',
    sound: '1244.mp3',
    bookNumber: 1,
    id: 1244,
    uz: "o'z ichiga olmoq",
    uzOptions: [
      "o'z ichiga olmoq",
      'qo`shimcha ma`lumot',
      'musobaqa',
      'xabardor',
    ],
    enOptions: ['contain', 'follow', 'board', 'symbol'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'correct',
    pron: '[kəˈrɛkt] adj.',
    desc: 'To be correct is to be right.',
    exam: 'All of my answers on the test were <strong>correct</strong>.',
    vi: '',
    image: '1245.jpg',
    sound: '1245.mp3',
    bookNumber: 1,
    id: 1245,
    uz: "to'g'ri",
    uzOptions: ["to'g'ri", "bo'lak", 'kesib', 'aqliy'],
    enOptions: ['correct', 'inform', 'personality', 'extreme'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'crop',
    pron: '[krɒp] n.',
    desc: 'A crop is food that a farmer grows.',
    exam: 'Wheat is a <strong>crop </strong>that is made into bread.',
    vi: '',
    image: '1246.jpg',
    sound: '1246.mp3',
    bookNumber: 1,
    id: 1246,
    uz: 'ekin',
    uzOptions: ['ekin', 'xalqaro', 'hid', 'tepalik'],
    enOptions: ['crop', 'technology', 'introduce', 'honesty'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'demand',
    pron: '[dɪˈmɑːnd] v.',
    desc: 'To demand something is to say strongly that you want it.',
    exam: 'The workers <strong>demanded </strong>to be paid more money.',
    vi: '',
    image: '1247.jpg',
    sound: '1247.mp3',
    bookNumber: 1,
    id: 1247,
    uz: 'talab',
    uzOptions: ['talab', 'hukm  baho', 'okean', 'buyum'],
    enOptions: ['demand', 'lot', 'store', 'fair'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'equal',
    pron: '[ˈiːkw(ə)l] adj.',
    desc: 'To be equal is to be the same.',
    exam: 'Both students are <strong>equal </strong>in age.',
    vi: '',
    image: '1248.jpg',
    sound: '1248.mp3',
    bookNumber: 1,
    id: 1248,
    uz: 'teng',
    uzOptions: ['teng', 'kelishuv', 'tajriba', 'suyak'],
    enOptions: ['equal', 'unite', 'purchase', 'normal'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'feed',
    pron: '[fiːd] v.',
    desc: 'To feed is to give food.',
    exam: 'Mother <strong>feeds </strong>my baby brother everyday.',
    vi: '',
    image: '1249.jpg',
    sound: '1249.mp3',
    bookNumber: 1,
    id: 1249,
    uz: 'boqmoq',
    uzOptions: ['boqmoq', 'shuning uchun', 'oldinga', 'farq'],
    enOptions: ['feed', 'proper', 'schedule', 'glad'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'hole',
    pron: '[həʊl] n.',
    desc: 'A hole is an opening in something.',
    exam: 'The man was going to jump into the <strong>hole </strong>in the ice.',
    vi: '',
    image: '1250.jpg',
    sound: '1250.mp3',
    bookNumber: 1,
    id: 1250,
    uz: 'teshik',
    uzOptions: ['teshik', 'yuz', 'shakl', 'laboratoriya'],
    enOptions: ['hole', 'create', 'clerk', 'center'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'increase',
    pron: '[ˈɪŋkriːs] v.',
    desc: 'To increase something is to make it larger or more.',
    exam: 'They&rsquo;ve <strong>increased </strong>the price of gas by 15 cents!',
    vi: '',
    image: '1251.jpg',
    sound: '1251.mp3',
    bookNumber: 1,
    id: 1251,
    uz: "o'smoq",
    uzOptions: ["o'smoq", 'yashamoq', 'sirt', "bo'lak"],
    enOptions: ['increase', 'block', 'arrive', 'customer'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'lord',
    pron: '[lɔːd] n.',
    desc: 'Long ago, a lord was a man in charge of a town.',
    exam: 'The <strong>lord </strong>of the town was not kind.',
    vi: '',
    image: '1252.jpg',
    sound: '1252.mp3',
    bookNumber: 1,
    id: 1252,
    uz: 'lord',
    uzOptions: ['lord', 'darhol', 'zerikarli', 'qiymat'],
    enOptions: ['lord', 'ground', 'unite', 'discover'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'owe',
    pron: '[əʊ] v.',
    desc: 'To owe is to have to pay or give back something received from another.',
    exam: 'I <strong>owed </strong>him twenty dollars, so I paid him back.',
    vi: '',
    image: '1253.jpg',
    sound: '1253.mp3',
    bookNumber: 1,
    id: 1253,
    uz: 'qarzdor',
    uzOptions: ['qarzdor', 'na', 'oldinga', 'tayinlamoq'],
    enOptions: ['owe', 'examine', 'regard', 'passage'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'position',
    pron: '[pəˈzɪʃ(ə)n] n.',
    desc: 'A position is the way something is placed.',
    exam: 'How can you sit in that <strong>position</strong>?',
    vi: '',
    image: '1254.jpg',
    sound: '1254.mp3',
    bookNumber: 1,
    id: 1254,
    uz: 'orin',
    uzOptions: ['orin', 'keyinchalik', 'keyinchalik', 'xulosa'],
    enOptions: ['position', 'example', 'gain', 'concert'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'raise',
    pron: '[reɪz] v.',
    desc: 'To raise something is to lift it up.',
    exam: 'We had to work together to <strong>raise </strong>the last piece.',
    vi: '',
    image: '1255.jpg',
    sound: '1255.mp3',
    bookNumber: 1,
    id: 1255,
    uz: 'oshirmoq',
    uzOptions: ['oshirmoq', 'likop', 'muvaffaqiyatsizlikka uchramoq', 'dono'],
    enOptions: ['raise', 'attend', 'refuse', 'stroll'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'responsible',
    pron: '[rɪˈspɒnsɪb(ə)l] adj.',
    desc: 'If a person is responsible, they do the right things.',
    exam: 'I try to be <strong>responsible </strong>and save money.',
    vi: '',
    image: '1256.jpg',
    sound: '1256.mp3',
    bookNumber: 1,
    id: 1256,
    uz: "mas'ul",
    uzOptions: ["mas'ul", 'chiqindi', "bo'ron", 'qon'],
    enOptions: ['responsible', 'propose', 'receive', 'breathe'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'sight',
    pron: '[sʌɪt] n.',
    desc: 'A sight is something interesting to see.',
    exam: 'I saw the pyramids of Egypt. What a <strong>sight</strong>!',
    vi: '',
    image: '1257.jpg',
    sound: '1257.mp3',
    bookNumber: 1,
    id: 1257,
    uz: "ko'rish",
    uzOptions: ["ko'rish", 'oldini olmoq  saqlanmoq', 'jamoat', 'mijoz'],
    enOptions: ['sight', 'compete', 'reside', 'maybe'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'spot',
    pron: '[spɒt] n.',
    desc: 'A spot is a place where something happens.',
    exam: 'The kitchen is a good <strong>spot </strong>to eat meals.',
    vi: '',
    image: '1258.jpg',
    sound: '1258.mp3',
    bookNumber: 1,
    id: 1258,
    uz: 'dog`  joy',
    uzOptions: ['dog`  joy', 'uzunlik', 'yechim', 'olam'],
    enOptions: ['spot', 'safety', 'length', 'solution'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'structure',
    pron: '[ˈstrʌktʃə] n.',
    desc: 'A structure is a building.',
    exam: 'They just built a beautiful new <strong>structure </strong>downtown.',
    vi: '',
    image: '1259.jpg',
    sound: '1259.mp3',
    bookNumber: 1,
    id: 1259,
    uz: 'tuzilish',
    uzOptions: ['tuzilish', "do'stlik", 'siyosat', 'imtihon'],
    enOptions: ['structure', 'project', 'already', 'include'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'whole',
    pron: '[həʊl] adj.',
    desc: 'Whole means all of something.',
    exam: 'I ate the <strong>whole </strong>pie. We don&rsquo;t have any more.',
    vi: '',
    image: '1260.jpg',
    sound: '1260.mp3',
    bookNumber: 1,
    id: 1260,
    uz: 'butun',
    uzOptions: ['butun', 'adolatsizlik', 'mavjud', 'musiqiy guruh'],
    enOptions: ['whole', 'progress', 'still', 'chemical'],
    answerIndex: 0,
    unitNumber: 13,
    quizNumber: 5,
  },
  {
    en: 'coach',
    pron: '[kəʊtʃ] n.',
    desc: 'A coach is a person who teaches sports.',
    exam: 'My <strong>coach </strong>gets very excited during games.',
    vi: '',
    image: '1261.jpg',
    sound: '1261.mp3',
    bookNumber: 1,
    id: 1261,
    uz: 'murabbiy',
    uzOptions: ['murabbiy', 'ajoyib', 'shoir', 'mahalliy'],
    enOptions: ['coach', 'publish', 'result', 'correct'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'control',
    pron: '[kənˈtrəʊl] v.',
    desc: 'To control something is to make it do what you want.',
    exam: 'To <strong>control </strong>the TV, just push the buttons.',
    vi: '',
    image: '1262.jpg',
    sound: '1262.mp3',
    bookNumber: 1,
    id: 1262,
    uz: 'boshqaruv',
    uzOptions: ['boshqaruv', 'tirik', 'tuzatmoq', 'bahslashmoq'],
    enOptions: ['control', 'bright', 'determine', 'scan'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'description',
    pron: '[dɪˈskrɪpʃ(ə)n] n.',
    desc: 'A description of someone or something says what they are like.',
    exam: 'I gave a <strong>description </strong>of the man with the gun and hat to the police.',
    vi: '',
    image: '1263.jpg',
    sound: '1263.mp3',
    bookNumber: 1,
    id: 1263,
    uz: 'tushuntirish',
    uzOptions: ['tushuntirish', 'uy hayvoni', 'chiqindi', 'yer'],
    enOptions: ['description', 'whether', 'bone', 'report'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'direct',
    pron: '[dɪˈrɛkt] adj.',
    desc: 'If something is direct, it goes straight between two places.',
    exam: 'The green path is a <strong>direct </strong>route to my house.',
    vi: '',
    image: '1264.jpg',
    sound: '1264.mp3',
    bookNumber: 1,
    id: 1264,
    uz: "to'g'ridan-to'g'ri",
    uzOptions: [
      "to'g'ridan-to'g'ri",
      "qo'ymoq  o'rnatmoq",
      "ta'riflamoq",
      "o'rgimchak to'ri",
    ],
    enOptions: ['direct', 'reflect', 'hang', 'evil'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'exam',
    pron: '[ɪɡˈzam] n.',
    desc: 'An exam is a test.',
    exam: 'I did some practice questions for the math <strong>exam </strong>on the board.',
    vi: '',
    image: '1265.jpg',
    sound: '1265.mp3',
    bookNumber: 1,
    id: 1265,
    uz: 'imtihon',
    uzOptions: ['imtihon', 'talab', 'imkoniyat', 'boylik'],
    enOptions: ['exam', 'passenger', 'professional', 'chart'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'example',
    pron: '[ɪɡˈzɑːmp(ə)l] n.',
    desc: 'An example of something is a thing that is typical of it.',
    exam: 'Cola is an <strong>example </strong>of a soft drink.',
    vi: '',
    image: '1266.jpg',
    sound: '1266.mp3',
    bookNumber: 1,
    id: 1266,
    uz: 'misol',
    uzOptions: ['misol', 'murakkab', 'reja', 'musobaqa'],
    enOptions: ['example', 'pattern', 'village', 'still'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'limit',
    pron: '[ˈlɪmɪt] n.',
    desc: 'A limit is the largest or smallest amount of something that you allow.',
    exam: 'My mother put a <strong>limit </strong>on how much I could use the phone.',
    vi: '',
    image: '1267.jpg',
    sound: '1267.mp3',
    bookNumber: 1,
    id: 1267,
    uz: 'chegara',
    uzOptions: ['chegara', 'mijoz', "o't", 'aniq'],
    enOptions: ['limit', 'own', 'drop', 'available'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'local',
    pron: '[ˈləʊk(ə)l] adj.',
    desc: 'If something is local, it is nearby.',
    exam: 'The <strong>local </strong>market in my neighborhood sells all the food we need.',
    vi: '',
    image: '1268.jpg',
    sound: '1268.mp3',
    bookNumber: 1,
    id: 1268,
    uz: 'mahalliy',
    uzOptions: ['mahalliy', "qirg'oq", 'ehtimol', 'katta'],
    enOptions: ['local', 'reward', 'badly', 'pleasant'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'magical',
    pron: '[ˈmadʒɪk(ə)l] adj.',
    desc: 'Magical describes a quality that makes someone or something special.',
    exam: 'The fireworks made the night sky look so <strong>magical</strong>.',
    vi: '',
    image: '1269.jpg',
    sound: '1269.mp3',
    bookNumber: 1,
    id: 1269,
    uz: 'sehrli',
    uzOptions: ['sehrli', 'foyda', 'oldini olmoq  saqlanmoq', 'kuch'],
    enOptions: ['magical', 'hero', 'available', 'board'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'mail',
    pron: '[meɪl] n.',
    desc: 'Mail is letters and other things sent to people.',
    exam: 'I get a lot of <strong>mail </strong>because I have friends all over the world.',
    vi: '',
    image: '1270.jpg',
    sound: '1270.mp3',
    bookNumber: 1,
    id: 1270,
    uz: 'pochta',
    uzOptions: ['pochta', 'ibora', 'xato', 'foyda'],
    enOptions: ['mail', 'trouble', 'later', 'reply'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'novel',
    pron: '[ˈnɒv(ə)l] n.',
    desc: 'A novel is a book that tells a story.',
    exam: 'He wrote a great <strong>novel </strong>about ancient China.',
    vi: '',
    image: '1271.jpg',
    sound: '1271.mp3',
    bookNumber: 1,
    id: 1271,
    uz: 'roman',
    uzOptions: ['roman', "sodir bo'lmoq", 'reklama qilmoq', 'shahzoda'],
    enOptions: ['novel', 'expect', 'habit', 'badly'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'outline',
    pron: '[ˈaʊtlʌɪn] n.',
    desc: 'An outline is the plan for a story or essay.',
    exam: 'Before I wrote my essay, I made an <strong>outline</strong>.',
    vi: '',
    image: '1272.jpg',
    sound: '1272.mp3',
    bookNumber: 1,
    id: 1272,
    uz: 'reja',
    uzOptions: ['reja', 'jalb qilmoq', 'tashvishlanmoq', 'ehtimol'],
    enOptions: ['outline', 'fit', 'poem', 'experience'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'poet',
    pron: '[ˈpəʊɪt] n.',
    desc: 'A poet is a person who writes poems.',
    exam: 'William Shakespeare was one of the greatest <strong>poets</strong>.',
    vi: '',
    image: '1273.jpg',
    sound: '1273.mp3',
    bookNumber: 1,
    id: 1273,
    uz: 'shoir',
    uzOptions: ['shoir', 'otmoq', 'tagi  osti', 'shoshilmoq'],
    enOptions: ['poet', 'extreme', 'factory', 'suggest'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'print',
    pron: '[prɪnt] v.',
    desc: 'To print something is to put it onto paper.',
    exam: 'Make sure that you <strong>print </strong>your name clearly.',
    vi: '',
    image: '1274.jpg',
    sound: '1274.mp3',
    bookNumber: 1,
    id: 1274,
    uz: 'bosib chiqarmoq',
    uzOptions: [
      'bosib chiqarmoq',
      'ovoz bermoq',
      'qabul qilmoq',
      "qo'shib qo'ymoq",
    ],
    enOptions: ['print', 'officer', 'worse', 'involve'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'scene',
    pron: '[siːn] n.',
    desc: 'A scene is one part of a book or movie.',
    exam: 'A movie is made up of many short pieces or <strong>scenes</strong>.',
    vi: '',
    image: '1275.jpg',
    sound: '1275.mp3',
    bookNumber: 1,
    id: 1275,
    uz: 'sahna',
    uzOptions: ['sahna', 'ozod qilmoq', 'markaz', 'ofitser'],
    enOptions: ['scene', 'chart', 'project', 'band'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'sheet',
    pron: '[ʃiːt] n.',
    desc: 'A sheet is a thin flat piece of paper.',
    exam: 'I only needed a single <strong>sheet </strong>of paper to do my homework.',
    vi: '',
    image: '1276.jpg',
    sound: '1276.mp3',
    bookNumber: 1,
    id: 1276,
    uz: 'varoq',
    uzOptions: ['varoq', 'jadval', 'taklif qilmoq', 'operatsiya'],
    enOptions: ['sheet', 'finally', 'consider', 'serious'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'silly',
    pron: '[ˈsɪli] adj.',
    desc: 'If someone or something is silly, they show a lack of thought.',
    exam: 'I made a <strong>silly </strong>mistake of dropping mom&rsquo;s vase.',
    vi: '',
    image: '1277.jpg',
    sound: '1277.mp3',
    bookNumber: 1,
    id: 1277,
    uz: 'ahmoqona',
    uzOptions: ['ahmoqona', "e'tiqod", "yolg'on gapirmoq", "sovg'a"],
    enOptions: ['silly', 'bottom', 'maintain', 'message'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'store',
    pron: '[stɔː] n.',
    desc: 'A store is a place where you can buy things.',
    exam: 'I picked up a few things at the grocery <strong>store</strong>.',
    vi: '',
    image: '1278.jpg',
    sound: '1278.mp3',
    bookNumber: 1,
    id: 1278,
    uz: "do'kon  saqlamoq",
    uzOptions: ["do'kon  saqlamoq", 'boshqaruv', 'qiymat', 'xususiyat'],
    enOptions: ['store', 'article', 'mental', 'face'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'suffer',
    pron: '[ˈsʌfə] v.',
    desc: 'To suffer is to feel pain.',
    exam: 'Her headache made her <strong>suffer </strong>all day.',
    vi: '',
    image: '1279.jpg',
    sound: '1279.mp3',
    bookNumber: 1,
    id: 1279,
    uz: 'azoblanmoq',
    uzOptions: ['azoblanmoq', 'kashf qilmoq', 'muvofiq', 'talab qilmoq'],
    enOptions: ['suffer', 'cloud', 'purpose', 'set'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'technology',
    pron: '[tɛkˈnɒlədʒi] n.',
    desc: 'Technology is new things made by using science.',
    exam: 'He loves <strong>technology </strong>such as laptop computers.',
    vi: '',
    image: '1280.jpg',
    sound: '1280.mp3',
    bookNumber: 1,
    id: 1280,
    uz: 'texnologiya',
    uzOptions: ['texnologiya', 'kapitan', "maqul ko'rmoq", 'baxtli'],
    enOptions: ['technology', 'site', 'single', 'angry'],
    answerIndex: 0,
    unitNumber: 14,
    quizNumber: 5,
  },
  {
    en: 'across',
    pron: '[əˈkrɒs] prep.',
    desc: 'To go across something is to go to the other side of it.',
    exam: 'He walked <strong>across </strong>the board to the other side.',
    vi: '',
    image: '1281.jpg',
    sound: '1281.mp3',
    bookNumber: 1,
    id: 1281,
    uz: 'kesib',
    uzOptions: ['kesib', 'yoymoq', 'ovqat', 'jiddiy'],
    enOptions: ['across', 'conclusion', 'mail', 'owe'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'breathe',
    pron: '[briːð] v.',
    desc: 'To breathe means to let air go in and out of your body.',
    exam: 'We need strong healthy lungs to help us <strong>breathe </strong>well.',
    vi: '',
    image: '1282.jpg',
    sound: '1282.mp3',
    bookNumber: 1,
    id: 1282,
    uz: 'nafas olmoq',
    uzOptions: ['nafas olmoq', 'haqiqat', 'talab', 'turmush qurmoq'],
    enOptions: ['breathe', 'technology', 'society', 'attract'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'characteristic',
    pron: '[karəktəˈrɪstɪk] n.',
    desc: 'A characteristic is something that shows what a person or a thing is like.',
    exam: 'One <strong>characteristic </strong>of tigers is their black stripes.',
    vi: '',
    image: '1283.jpg',
    sound: '1283.mp3',
    bookNumber: 1,
    id: 1283,
    uz: 'xususiyat',
    uzOptions: ['xususiyat', 'dalillar', 'yashamoq', "ma'no"],
    enOptions: ['characteristic', 'consume', 'later', 'rich'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'consume',
    pron: '[kənˈsjuːm] v.',
    desc: 'To consume something means to eat or drink it.',
    exam: 'Jack <strong>consumed </strong>a whole plate of spaghetti.',
    vi: '',
    image: '1284.jpg',
    sound: '1284.mp3',
    bookNumber: 1,
    id: 1284,
    uz: "iste'mol qilmoq",
    uzOptions: ["iste'mol qilmoq", 'otmoq', 'tashlab ketmoq', 'asbob'],
    enOptions: ['consume', 'essential', 'receive', 'store'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'excite',
    pron: '[ɪkˈsʌɪt] v.',
    desc: 'To excite someone means to make them happy and interested.',
    exam: 'I heard about the school dance on Friday. This <strong>excited </strong>me.',
    vi: '',
    image: '1285.jpg',
    sound: '1285.mp3',
    bookNumber: 1,
    id: 1285,
    uz: 'hayratlanmoq',
    uzOptions: ['hayratlanmoq', 'kesib', "yo'nalish  kurs", 'tanish'],
    enOptions: ['excite', 'regard', 'conclusion', 'prefer'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'extreme',
    pron: '[ɪkˈstriːm] adj.',
    desc: 'If something is extreme, it is in a large amount or degree.',
    exam: 'His workout was so <strong>extreme </strong>that he was sweating heavily.',
    vi: '',
    image: '1286.jpg',
    sound: '1286.mp3',
    bookNumber: 1,
    id: 1286,
    uz: 'haddan tashqari',
    uzOptions: ['haddan tashqari', 'jadval', "qo'shni", 'hali ham'],
    enOptions: ['extreme', 'evil', 'fortunate', 'wonder'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'fear',
    pron: '[fɪə] n.',
    desc: 'Fear is the feeling of being afraid.',
    exam: 'I have a great <strong>fear </strong>of skateboarding.',
    vi: '',
    image: '1287.jpg',
    sound: '1287.mp3',
    bookNumber: 1,
    id: 1287,
    uz: "qo'rquv",
    uzOptions: ["qo'rquv", 'javob', 'orqasida', 'odat'],
    enOptions: ['fear', 'war', 'ancient', 'argue'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'fortunate',
    pron: '[ˈfɔːtʃ(ə)nət] adj.',
    desc: 'If you are fortunate, you are lucky.',
    exam: 'I was <strong>fortunate </strong>to get a seat.',
    vi: '',
    image: '1288.jpg',
    sound: '1288.mp3',
    bookNumber: 1,
    id: 1288,
    uz: 'baxtli',
    uzOptions: ['baxtli', 'vakillik qilmoq', 'yashamoq', "bo'lak"],
    enOptions: ['fortunate', 'middle', 'theory', 'gain'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'happen',
    pron: '[ˈhap(ə)n] v.',
    desc: 'If someone happens to do something, they do it by chance.',
    exam: 'I <strong>happened </strong>to meet some new friends at school today.',
    vi: '',
    image: '1289.jpg',
    sound: '1289.mp3',
    bookNumber: 1,
    id: 1289,
    uz: "sodir bo'lmoq",
    uzOptions: ["sodir bo'lmoq", 'isbotlamoq', 'sahna', "qo'rquv"],
    enOptions: ['happen', 'contribute', 'treat', 'collect'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'length',
    pron: '[lɛn(t)θ] n.',
    desc: 'The length of something is how long it is from one end to the other.',
    exam: 'The <strong>length </strong>of the floor is three meters.',
    vi: '',
    image: '1290.jpg',
    sound: '1290.mp3',
    bookNumber: 1,
    id: 1290,
    uz: 'uzunlik',
    uzOptions: ['uzunlik', 'mavsum', 'aqliy', 'maslahat'],
    enOptions: ['length', 'remove', 'refuse', 'afraid'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'mistake',
    pron: '[mɪˈsteɪk] n.',
    desc: 'A mistake is something you do wrong.',
    exam: 'My boss always yells at me when I make a <strong>mistake</strong>.',
    vi: '',
    image: '1291.jpg',
    sound: '1291.mp3',
    bookNumber: 1,
    id: 1291,
    uz: 'xato',
    uzOptions: ['xato', "ega bo'lmoq", 'zarar', 'tanlamoq'],
    enOptions: ['mistake', 'quite', 'mail', 'space'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'observe',
    pron: '[əbˈzəːv] v.',
    desc: 'To observe something is to watch it.',
    exam: 'Brian <strong>observed </strong>the sun rising over the mountains.',
    vi: '',
    image: '1292.jpg',
    sound: '1292.mp3',
    bookNumber: 1,
    id: 1292,
    uz: 'kuzatmoq',
    uzOptions: [
      'kuzatmoq',
      "ko'z yoshi  yirtmoq",
      'yechim',
      'erishmoq  yetib bormoq',
    ],
    enOptions: ['observe', 'consume', 'produce', 'realize'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'opportunity',
    pron: '[ɒpəˈtjuːnɪti] n.',
    desc: 'An opportunity is a chance to do something.',
    exam: 'I had an <strong>opportunity </strong>to take pictures in the jungle.',
    vi: '',
    image: '1293.jpg',
    sound: '1293.mp3',
    bookNumber: 1,
    id: 1293,
    uz: 'imkoniyat',
    uzOptions: ['imkoniyat', 'shaxs', 'ijro etmoq', 'tagi  osti'],
    enOptions: ['opportunity', 'reside', 'pressure', 'represent'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'prize',
    pron: '[prʌɪz] n.',
    desc: 'A prize is something of value that is given to the winner.',
    exam: 'I won a <strong>prize </strong>for getting the best grade on my science test.',
    vi: '',
    image: '1294.jpg',
    sound: '1294.mp3',
    bookNumber: 1,
    id: 1294,
    uz: 'sovrin',
    uzOptions: ['sovrin', 'sehrli', 'jurnal', 'imtihon'],
    enOptions: ['prize', 'real', 'cell', 'flow'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'race',
    pron: '[reɪs] n.',
    desc: 'A race is a contest to see who is the fastest.',
    exam: 'Paul is a fast runner, so he easily won the <strong>race</strong>.',
    vi: '',
    image: '1295.jpg',
    sound: '1295.mp3',
    bookNumber: 1,
    id: 1295,
    uz: 'irq',
    uzOptions: ['irq', 'xususiyat', 'mahalliy', 'hissiyot'],
    enOptions: ['race', 'poet', 'hill', 'well'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'realize',
    pron: '[ˈrɪəlʌɪz] v.',
    desc: 'To realize is to suddenly understand.',
    exam: 'After I left my house, I <strong>realized </strong>that I left the light on.',
    vi: '',
    image: '1296.jpg',
    sound: '1296.mp3',
    bookNumber: 1,
    id: 1296,
    uz: 'tushunmoq',
    uzOptions: ['tushunmoq', 'xavfsizlik', 'muammo', 'musobaqa'],
    enOptions: ['realize', 'outline', 'event', 'avoid'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'respond',
    pron: '[rɪˈspɒnd] v.',
    desc: 'To respond is to give an answer to what someone else said.',
    exam: 'When the teacher asked the question, we all <strong>responded</strong>.',
    vi: '',
    image: '1297.jpg',
    sound: '1297.mp3',
    bookNumber: 1,
    id: 1297,
    uz: 'javob bermoq',
    uzOptions: ['javob bermoq', 'mashq qilmoq', 'xafa', "ko'rinish"],
    enOptions: ['respond', 'none', 'tip', 'ride'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'risk',
    pron: '[rɪsk] n.',
    desc: 'A risk is a chance of something bad happening.',
    exam: 'I took a <strong>risk </strong>and climbed the snowy mountain.',
    vi: '',
    image: '1298.jpg',
    sound: '1298.mp3',
    bookNumber: 1,
    id: 1298,
    uz: 'xavf',
    uzOptions: ['xavf', 'yana boshqa', 'sinoat', 'zerikarli'],
    enOptions: ['risk', 'scare', 'crop', 'choice'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'wonder',
    pron: '[ˈwʌndə] v.',
    desc: 'To wonder is to ask yourself questions or have a need to know.',
    exam: 'The young mother <strong>wondered </strong>if she&rsquo;d have a boy or a girl.',
    vi: '',
    image: '1299.jpg',
    sound: '1299.mp3',
    bookNumber: 1,
    id: 1299,
    uz: 'hayron bo`lmoq',
    uzOptions: ['hayron bo`lmoq', 'sportchi', 'nafas olmoq', 'kuzatmoq'],
    enOptions: ['wonder', 'quite', 'middle', 'gain'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
  {
    en: 'yet',
    pron: '[jɛt] adv.',
    desc: 'Yet is used to say something has not happened up to now.',
    exam: 'We can&rsquo;t go out <strong>yet</strong>; we&rsquo;re still eating.',
    vi: '',
    image: '1300.jpg',
    sound: '1300.mp3',
    bookNumber: 1,
    id: 1300,
    uz: 'hali',
    uzOptions: [
      'hali',
      'jalb qilmoq',
      "ko'nglini ko'tarmoq",
      "rag'batlantirmoq",
    ],
    enOptions: ['yet', 'contrast', 'community', 'fright'],
    answerIndex: 0,
    unitNumber: 15,
    quizNumber: 5,
  },
];

console.log(quiz.length); // 55
console.log(quiz.length); // 55

// === in gitBash: ====
// node js/question13.js
