// **Question-13**
// *tayyor*
// # 1: Yuqoridagi hammat testlar (jami 460)
'use strick';
// Array of Object;
const quiz = [
  {
    en: 'appropriate',
    pron: '[əˈprəʊprɪeɪt] adj.',
    desc: 'When a thing is appropriate, it is right or normal.',
    exam: 'It&rsquo;s <strong>appropriate </strong>to wear a suit when you go to the office.',
    vi: '',
    image: '1061.jpg',
    sound: '1061.mp3',
    bookNumber: 1,
    id: 1061,
    uz: 'muvofiq',
    uzOptions: ['muvofiq', 'tanlov', 'tanishtirmoq', 'yashirmoq'],
    enOptions: ['appropriate', 'consume', 'policy', 'strange'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'avoid',
    pron: '[əˈvɔɪd] v.',
    desc: 'To avoid something is to stay away from it.',
    exam: '<strong>Avoid </strong>the broken bottle on the floor.',
    vi: '',
    image: '1062.jpg',
    sound: '1062.mp3',
    bookNumber: 1,
    id: 1062,
    uz: 'oldini olmoq  saqlanmoq',
    uzOptions: ['oldini olmoq  saqlanmoq', 'uch', "cho'l", 'rasm'],
    enOptions: ['avoid', 'already', 'silly', 'skill'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'behave',
    pron: '[bɪˈheɪv] v.',
    desc: 'To behave is to act in a particular way, especially to be good.',
    exam: 'She always <strong>behaves </strong>well when her father is around.',
    vi: '',
    image: '1063.jpg',
    sound: '1063.mp3',
    bookNumber: 1,
    id: 1063,
    uz: "o'zini tutmoq",
    uzOptions: ["o'zini tutmoq", "yo'lak", 'yangi', 'rassom'],
    enOptions: ['behave', 'hidden', 'pound', 'own'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'calm',
    pron: '[kɑːm] adj.',
    desc: 'When someone is calm, they do not get excited or upset.',
    exam: 'A nice warm bath makes me feel so <strong>calm</strong>.',
    vi: '',
    image: '1064.jpg',
    sound: '1064.mp3',
    bookNumber: 1,
    id: 1064,
    uz: 'sokin',
    uzOptions: ['sokin', 'ichida', 'qadimiy', 'salqin  ajoyib'],
    enOptions: ['calm', 'consume', 'indicate', 'public'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'concern',
    pron: '[kənˈsəːn] n.',
    desc: 'Concern is a feeling of worry.',
    exam: 'I was filled with <strong>concern </strong>after reading the newspaper.',
    vi: '',
    image: '1065.jpg',
    sound: '1065.mp3',
    bookNumber: 1,
    id: 1065,
    uz: 'tashvishlanmoq',
    uzOptions: ['tashvishlanmoq', 'okean', 'akademiya', 'tirik'],
    enOptions: ['concern', 'follow', 'attract', 'individual'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'content',
    pron: '[kənˈtɛnt] adj.',
    desc: 'To be content is to be happy and not want more.',
    exam: 'The baby looked very <strong>content </strong>sitting on the floor.',
    vi: '',
    image: '1066.jpg',
    sound: '1066.mp3',
    bookNumber: 1,
    id: 1066,
    uz: 'mamnun',
    uzOptions: ['mamnun', 'jamoa', 'vakillik qilmoq', "bo'lim"],
    enOptions: ['content', 'produce', 'burn', 'pattern'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'expect',
    pron: '[ɪkˈspɛkt] v.',
    desc: 'If you expect something to happen, you believe it will happen.',
    exam: 'I <strong>expect </strong>the bus to be here very soon.',
    vi: '',
    image: '1067.jpg',
    sound: '1067.mp3',
    bookNumber: 1,
    id: 1067,
    uz: 'kutmoq',
    uzOptions: ['kutmoq', 'uyquda', 'qarshi', 'qarshi'],
    enOptions: ['expect', 'amount', 'situated', 'familiar'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'frequently',
    pron: '[ˈfriːkwəntli] adv.',
    desc: 'When something happens frequently, it happens often.',
    exam: 'We meet <strong>frequently</strong>, either at the beginning or ending of the week.',
    vi: '',
    image: '1068.jpg',
    sound: '1068.mp3',
    bookNumber: 1,
    id: 1068,
    uz: 'tez-tez',
    uzOptions: ['tez-tez', 'axlat', 'taxta', 'sokin'],
    enOptions: ['frequently', 'though', 'distance', 'skill'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'habit',
    pron: '[ˈhabɪt] n.',
    desc: 'A habit is a thing that you do often.',
    exam: 'Smoking is a bad <strong>habit </strong>that can kill you.',
    vi: '',
    image: '1069.jpg',
    sound: '1069.mp3',
    bookNumber: 1,
    id: 1069,
    uz: 'odat',
    uzOptions: ['odat', 'tajriba', "o'lik", 'jentleman'],
    enOptions: ['habit', 'exam', 'skill', 'reply'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'instruct',
    pron: '[ɪnˈstrʌkt] v.',
    desc: 'To instruct is to teach.',
    exam: 'My teacher <strong>instructs </strong>us in several subjects.',
    vi: '',
    image: '1070.jpg',
    sound: '1070.mp3',
    bookNumber: 1,
    id: 1070,
    uz: "ko'rsatma bermoq",
    uzOptions: ["ko'rsatma bermoq", 'tez-tez', 'taxta', "bo'lmoq"],
    enOptions: ['instruct', 'benefit', 'fear', 'pain'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'issue',
    pron: '[ˈɪʃuː] n.',
    desc: 'An issue is an important topic.',
    exam: 'The men spoke about <strong>issues </strong>that were important to the people.',
    vi: '',
    image: '1071.jpg',
    sound: '1071.mp3',
    bookNumber: 1,
    id: 1071,
    uz: 'masala',
    uzOptions: ['masala', 'qarzdor', 'uzoq', 'davr'],
    enOptions: ['issue', 'introduce', 'raise', 'race'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'none',
    pron: '[nəʊn] pron.',
    desc: 'None means not any of someone or something.',
    exam: 'He spent all his money. There is <strong>none </strong>left.',
    vi: '',
    image: '1072.jpg',
    sound: '1072.mp3',
    bookNumber: 1,
    id: 1072,
    uz: 'hech biri',
    uzOptions: ['hech biri', 'eslatmoq', 'shoir', "hissa qo'shmoq"],
    enOptions: ['none', 'lord', 'decision', 'universe'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'patient',
    pron: '[ˈpeɪʃ(ə)nt] adj.',
    desc: 'If a person is patient, they don’t become angry or upset easily.',
    exam: 'I had to be <strong>patient </strong>and wait until 5 o&rsquo;clock to leave.',
    vi: '',
    image: '1073.jpg',
    sound: '1073.mp3',
    bookNumber: 1,
    id: 1073,
    uz: 'sabrli',
    uzOptions: ['sabrli', 'azoblanmoq', 'adolatli', 'tuzilish'],
    enOptions: ['patient', 'crowd', 'beach', 'image'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'positive',
    pron: '[ˈpɒzɪtɪv] adj.',
    desc: 'If something is positive, it is good.',
    exam: 'She has a <strong>positive </strong>future ahead of her after finishing college.',
    vi: '',
    image: '1074.jpg',
    sound: '1074.mp3',
    bookNumber: 1,
    id: 1074,
    uz: 'ijobiy',
    uzOptions: ['ijobiy', 'imkoniyat', 'tinchlik', 'payqamoq'],
    enOptions: ['positive', 'operation', 'sense', 'grab'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'punish',
    pron: '[ˈpʌnɪʃ] v.',
    desc: 'To punish means to make someone suffer for breaking the rules or laws.',
    exam: 'To <strong>punish </strong>me, my teacher had me stand in the corner.',
    vi: '',
    image: '1075.jpg',
    sound: '1075.mp3',
    bookNumber: 1,
    id: 1075,
    uz: 'jazolamoq',
    uzOptions: ['jazolamoq', 'ehtimol', 'yer', "yo'lovchi"],
    enOptions: ['punish', 'several', 'compete', 'upset'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'represent',
    pron: '[rɛprɪˈzɛnt] v.',
    desc: 'To represent is to speak or act for a person or group.',
    exam: 'My lawyer will <strong>represent </strong>me in court.',
    vi: '',
    image: '1076.jpg',
    sound: '1076.mp3',
    bookNumber: 1,
    id: 1076,
    uz: 'vakillik qilmoq',
    uzOptions: [
      'vakillik qilmoq',
      'himoya qilmoq',
      "paydo bo'ladi",
      'ruxsat bermoq',
    ],
    enOptions: ['represent', 'communicate', 'demonstrate', 'serious'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'shake',
    pron: '[ʃeɪk] v.',
    desc: 'To shake is to move back and forth or up and down quickly.',
    exam: 'When people <strong>shake </strong>hands, it usually means they agree.',
    vi: '',
    image: '1077.jpg',
    sound: '1077.mp3',
    bookNumber: 1,
    id: 1077,
    uz: 'silkitmoq',
    uzOptions: ['silkitmoq', 'oldini olmoq', "o'ziga xos", "bo'lak"],
    enOptions: ['shake', 'essential', 'level', 'bite'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'spread',
    pron: '[sprɛd] v.',
    desc: 'To spread is to move quickly to more places.',
    exam: 'I like to <strong>spread </strong>butter on my toast.',
    vi: '',
    image: '1078.jpg',
    sound: '1078.mp3',
    bookNumber: 1,
    id: 1078,
    uz: 'tarqalmoq',
    uzOptions: ['tarqalmoq', 'grafik  jadval', 'aks ettirmoq', 'yomonlik'],
    enOptions: ['spread', 'loud', 'judge', 'predict'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'stroll',
    pron: '[strəʊl] v.',
    desc: 'To stroll means to walk slowly and calmly.',
    exam: 'My dog and I <strong>strolled </strong>through the park today.',
    vi: '',
    image: '1079.jpg',
    sound: '1079.mp3',
    bookNumber: 1,
    id: 1079,
    uz: 'sayrga chiqmoq',
    uzOptions: ['sayrga chiqmoq', 'rassom', 'voqea', 'anglatmoq'],
    enOptions: ['stroll', 'exist', 'product', 'face'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'village',
    pron: '[ˈvɪlɪdʒ] n.',
    desc: 'A village is a very small town.',
    exam: 'There are only a few houses in my <strong>village</strong>.',
    vi: '',
    image: '1080.jpg',
    sound: '1080.mp3',
    bookNumber: 1,
    id: 1080,
    uz: 'qishloq',
    uzOptions: ['qishloq', 'yaratmoq', 'bir nechta', 'jismoniy'],
    enOptions: ['village', 'price', 'prevent', 'mix'],
    answerIndex: 0,
    unitNumber: 4,
    quizNumber: 2,
  },
  {
    en: 'aware',
    pron: '[əˈwɛː] adj.',
    desc: 'If you are aware of something, you know about it.',
    exam: 'I was not <strong>aware </strong>of the ringing phone.',
    vi: '',
    image: '1081.jpg',
    sound: '1081.mp3',
    bookNumber: 1,
    id: 1081,
    uz: 'xabardor',
    uzOptions: ['xabardor', "yolg'on gapirmoq", 'sayt  joy', 'chunki'],
    enOptions: ['aware', 'aware', 'consider', 'hole'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'badly',
    pron: '[ˈbadli] adv.',
    desc: 'Badly means in a severe or harmful way.',
    exam: 'He hurt his arm <strong>badly </strong>playing with friends.',
    vi: '',
    image: '1082.jpg',
    sound: '1082.mp3',
    bookNumber: 1,
    id: 1082,
    uz: 'yomon',
    uzOptions: ['yomon', 'tarqalmoq', 'yomon', 'taxmin qilmoq'],
    enOptions: ['badly', 'bright', 'profit', 'content'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'belong',
    pron: '[bɪˈlɒŋ] v.',
    desc: 'If something belongs to you, you own it.',
    exam: 'The blue suit <strong>belongs </strong>to Paul.',
    vi: '',
    image: '1083.jpg',
    sound: '1083.mp3',
    bookNumber: 1,
    id: 1083,
    uz: "tegishli bo'lmoq",
    uzOptions: ["tegishli bo'lmoq", 'taklif qilmoq', 'xafa', "o'rmon"],
    enOptions: ['belong', 'coach', 'clerk', 'relax'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'continue',
    pron: '[kənˈtɪnjuː] v.',
    desc: 'To continue something is to keep doing it.',
    exam: 'She stood under her umbrella as the rain <strong>continued </strong>to fall.',
    vi: '',
    image: '1084.jpg',
    sound: '1084.mp3',
    bookNumber: 1,
    id: 1084,
    uz: 'davom etmoq',
    uzOptions: ['davom etmoq', 'orqasida', 'orol', "yo'q qilmoq"],
    enOptions: ['continue', 'therefore', 'regular', 'solve'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'error',
    pron: '[ˈɛrə] n.',
    desc: 'An error is something you do wrong.',
    exam: 'I made an <strong>error </strong>on my report, so my boss was angry.',
    vi: '',
    image: '1085.jpg',
    sound: '1085.mp3',
    bookNumber: 1,
    id: 1085,
    uz: 'xato',
    uzOptions: ['xato', "ko'tarilmoq", 'muntazam', 'professional'],
    enOptions: ['error', 'public', 'smell', 'success'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'experience',
    pron: '[ɪkˈspɪərɪəns] n.',
    desc: 'An experience is something you have seen or done.',
    exam: 'Rock climbing was a fun <strong>experience</strong>.',
    vi: '',
    image: '1086.jpg',
    sound: '1086.mp3',
    bookNumber: 1,
    id: 1086,
    uz: 'tajriba',
    uzOptions: ['tajriba', "ko'tarilmoq", 'bosim', 'uslub'],
    enOptions: ['experience', 'wonder', 'view', 'worse'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'field',
    pron: '[fiːld] n.',
    desc: 'A field is a big area of land.',
    exam: 'The <strong>field </strong>of flowers looked so pretty.',
    vi: '',
    image: '1087.jpg',
    sound: '1087.mp3',
    bookNumber: 1,
    id: 1087,
    uz: 'maydon',
    uzOptions: ['maydon', 'sayohat', 'miqdor', 'mijoz'],
    enOptions: ['field', 'harm', 'along', 'expert'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'hurt',
    pron: '[həːt] v.',
    desc: 'To hurt is to do something that makes you feel pain.',
    exam: 'She <strong>hurt </strong>her leg falling down the stairs.',
    vi: '',
    image: '1088.jpg',
    sound: '1088.mp3',
    bookNumber: 1,
    id: 1088,
    uz: 'jarohat olmoq',
    uzOptions: ['jarohat olmoq', 'chegara', 'sotib olmoq', "osib qo'y"],
    enOptions: ['hurt', 'regard', 'achieve', 'fix'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'judgment',
    pron: '[ˈdʒʌdʒm(ə)nt] n.',
    desc: 'Judgment is the ability to form opinions or decisions.',
    exam: 'It&rsquo;s good <strong>judgment </strong>to recycle your aluminum cans.',
    vi: '',
    image: '1089.jpg',
    sound: '1089.mp3',
    bookNumber: 1,
    id: 1089,
    uz: 'hukm  baho',
    uzOptions: ['hukm  baho', 'sinoat', 'irq', 'tepalik'],
    enOptions: ['judgment', 'beside', 'season', 'opposite'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'likely',
    pron: '[ˈlʌɪkli] adv.',
    desc: 'If something likely happens, it will probably happen.',
    exam: 'I will <strong>likely </strong>stay at home and watch TV tonight.',
    vi: '',
    image: '1090.jpg',
    sound: '1090.mp3',
    bookNumber: 1,
    id: 1090,
    uz: 'ehtimol',
    uzOptions: ['ehtimol', 'talab qilmoq', 'harakat', 'texnologiya'],
    enOptions: ['likely', 'continue', 'either', 'patient'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'normal',
    pron: '[ˈnɔːm(ə)l] adj.',
    desc: 'If something is normal, it is not strange nor surprising to you.',
    exam: 'It is <strong>normal </strong>for me to bathe every night.',
    vi: '',
    image: '1091.jpg',
    sound: '1091.mp3',
    bookNumber: 1,
    id: 1091,
    uz: 'oddiy',
    uzOptions: ['oddiy', "mashg'ul bo'lmoq", 'ruxsat bermoq', 'muntazam'],
    enOptions: ['normal', 'lot', 'consume', 'yet'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'rare',
    pron: '[rɛː] adj.',
    desc: 'If something is rare, you do not see it very often.',
    exam: 'It is <strong>rare </strong>for him to miss his flight.',
    vi: '',
    image: '1092.jpg',
    sound: '1092.mp3',
    bookNumber: 1,
    id: 1092,
    uz: 'noyob',
    uzOptions: ['noyob', 'tayyorlamoq', 'jurnal', 'qadam'],
    enOptions: ['rare', 'worse', 'hang', 'hidden'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'relax',
    pron: '[rɪˈlaks] v.',
    desc: 'To relax is to rest.',
    exam: 'The frog <strong>relaxed </strong>in the warm sun.',
    vi: '',
    image: '1093.jpg',
    sound: '1093.mp3',
    bookNumber: 1,
    id: 1093,
    uz: 'rohatlanmoq',
    uzOptions: ['rohatlanmoq', 'yaqinlashmoq', 'misol', 'kuch'],
    enOptions: ['relax', 'protect', 'amount', 'charge'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'request',
    pron: '[rɪˈkwɛst] v.',
    desc: 'To request something is to ask for it.',
    exam: 'The little girl <strong>requested </strong>a special gift from Santa Claus.',
    vi: '',
    image: '1094.jpg',
    sound: '1094.mp3',
    bookNumber: 1,
    id: 1094,
    uz: "so'ramoq",
    uzOptions: ["so'ramoq", "e'lon qilmoq", 'aniqlash', "hissa qo'shmoq"],
    enOptions: ['request', 'block', 'fail', 'instead'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'reside',
    pron: '[rɪˈzʌɪd] v.',
    desc: 'To reside means to live somewhere permanently or for a long time.',
    exam: 'My brother and his family <strong>reside </strong>in a lovely house on the beach.',
    vi: '',
    image: '1095.jpg',
    sound: '1095.mp3',
    bookNumber: 1,
    id: 1095,
    uz: 'yashamoq',
    uzOptions: ['yashamoq', 'hali', 'uslub', "to'g'ri"],
    enOptions: ['reside', 'error', 'professional', 'technology'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'result',
    pron: '[rɪˈzʌlt] n.',
    desc: 'A result is something that happens because of something else.',
    exam: 'Asa <strong>result </strong>of all the rain, the man had to climb on the roof.',
    vi: '',
    image: '1096.jpg',
    sound: '1096.mp3',
    bookNumber: 1,
    id: 1096,
    uz: 'natija',
    uzOptions: ['natija', 'yangi', 'tashkillashtirmoq', "sodir bo'lmoq"],
    enOptions: ['result', 'solution', 'necessary', 'achieve'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'roll',
    pron: '[rəʊl] v.',
    desc: 'To roll is to move by turning over and over.',
    exam: 'You must <strong>roll </strong>the ball into the pins when you bowl.',
    vi: '',
    image: '1097.jpg',
    sound: '1097.mp3',
    bookNumber: 1,
    id: 1097,
    uz: 'dumalamoq',
    uzOptions: ['dumalamoq', 'tepalik', 'haqiqiy', 'tanish'],
    enOptions: ['roll', 'instruct', 'structure', 'creature'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'since',
    pron: '[sɪns] prep.',
    desc: 'Since is used to talk about a past event still happening now.',
    exam: '<strong>Since </strong>1992, he has been driving that car.',
    vi: '',
    image: '1098.jpg',
    sound: '1098.mp3',
    bookNumber: 1,
    id: 1098,
    uz: 'chunki',
    uzOptions: ['chunki', 'daraja', "yolg'on gapirmoq", 'martaba'],
    enOptions: ['since', 'likely', 'contrast', 'print'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'visible',
    pron: '[ˈvɪzɪb(ə)l] adj.',
    desc: 'If something is visible, it can be seen.',
    exam: 'The moon and stars were <strong>visible </strong>in the night sky.',
    vi: '',
    image: '1099.jpg',
    sound: '1099.mp3',
    bookNumber: 1,
    id: 1099,
    uz: "ko'rinadigan",
    uzOptions: ["ko'rinadigan", 'yorqin', 'jahlda', 'dori'],
    enOptions: ['visible', 'probable', 'personality', 'noise'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'wild',
    pron: '[wʌɪld] adj.',
    desc: 'If something is wild, it is found in nature.',
    exam: 'You should be careful around a fox, because it is a <strong>wild </strong>animal.',
    vi: '',
    image: '1100.jpg',
    sound: '1100.mp3',
    bookNumber: 1,
    id: 1100,
    uz: 'yovvoyi',
    uzOptions: ['yovvoyi', 'biroq', 'baho', 'yoymoq'],
    enOptions: ['wild', 'condition', 'single', 'captain'],
    answerIndex: 0,
    unitNumber: 5,
    quizNumber: 2,
  },
  {
    en: 'advantage',
    pron: '[ədˈvɑːntɪdʒ] n.',
    desc: 'An advantage is something that helps you.',
    exam: 'Being tall is an <strong>advantage </strong>to a basketball player.',
    vi: '',
    image: '1101.jpg',
    sound: '1101.mp3',
    bookNumber: 1,
    id: 1101,
    uz: 'afzallik',
    uzOptions: ['afzallik', 'haqiqiy', 'hali', "o'rgimchak to'ri"],
    enOptions: ['advantage', 'frank', 'shape', 'amaze'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'cause',
    pron: '[kɔːz] v.',
    desc: 'To cause is to make something happen.',
    exam: 'The cold weather <strong>caused </strong>her to get sick.',
    vi: '',
    image: '1102.jpg',
    sound: '1102.mp3',
    bookNumber: 1,
    id: 1102,
    uz: 'sababi',
    uzOptions: ['sababi', "sovg'a", 'tavsiya qilmoq', "ma'no"],
    enOptions: ['cause', 'face', 'decision', 'contribute'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'choice',
    pron: '[tʃɔɪs] n.',
    desc: 'A choice is the act or possibility of picking something.',
    exam: 'I had my <strong>choice </strong>of five doors to open.',
    vi: '',
    image: '1103.jpg',
    sound: '1103.mp3',
    bookNumber: 1,
    id: 1103,
    uz: 'tanlov',
    uzOptions: ['tanlov', 'lord', 'tasavvur qilmoq', 'ajoyib'],
    enOptions: ['choice', 'method', 'advertise', 'captain'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'community',
    pron: '[kəˈmjuːnɪti] n.',
    desc: 'A community is a group of people who live together.',
    exam: 'The kids from my <strong>community </strong>usually play together.',
    vi: '',
    image: '1104.jpg',
    sound: '1104.mp3',
    bookNumber: 1,
    id: 1104,
    uz: 'jamoa',
    uzOptions: ['jamoa', 'xato', 'davom etmoq', "yo'l ko'rsatuvchi"],
    enOptions: ['community', 'already', 'driveway', 'toward'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'dead',
    pron: '[dɛd] adj.',
    desc: 'To be dead is to not be alive.',
    exam: 'A <strong>dead </strong>person is usually buried in the ground.',
    vi: '',
    image: '1105.jpg',
    sound: '1105.mp3',
    bookNumber: 1,
    id: 1105,
    uz: "o'lik",
    uzOptions: ["o'lik", 'munosabat', 'darhol', 'kutmoq'],
    enOptions: ['dead', 'react', 'print', 'likely'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'distance',
    pron: '[ˈdɪst(ə)ns] n.',
    desc: 'The distance between two things is how far it is between them.',
    exam: 'The <strong>distance </strong>between the Earth and the Moon is 384,400 kilometers.',
    vi: '',
    image: '1106.jpg',
    sound: '1106.mp3',
    bookNumber: 1,
    id: 1106,
    uz: 'masofa',
    uzOptions: ['masofa', 'asosiy', 'bosib chiqarmoq', 'tushunmoq'],
    enOptions: ['distance', 'excellent', 'center', 'master'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'escape',
    pron: '[ɪˈskeɪp] v.',
    desc: 'To escape is to run away from something bad.',
    exam: 'The butterfly could not <strong>escape </strong>from the cage.',
    vi: '',
    image: '1107.jpg',
    sound: '1107.mp3',
    bookNumber: 1,
    id: 1107,
    uz: 'qochmoq',
    uzOptions: ['qochmoq', 'kuzatmoq', 'uy hayvoni', 'omon qolmoq'],
    enOptions: ['escape', 'attend', 'sheet', 'yet'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'face',
    pron: '[feɪs] v.',
    desc: 'If you face a problem, you deal with it.',
    exam: 'My sister and I have to find a better way to <strong>face </strong>our differences.',
    vi: '',
    image: '1108.jpg',
    sound: '1108.mp3',
    bookNumber: 1,
    id: 1108,
    uz: 'yuz',
    uzOptions: ['yuz', 'tayyorlamoq', 'mahsulot', "yolg'iz"],
    enOptions: ['face', 'pleased', 'wave', 'friendship'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'follow',
    pron: '[ˈfɒləʊ] v.',
    desc: 'To follow means to go behind someone and go where they go.',
    exam: 'The little boy <strong>followed </strong>his mother home.',
    vi: '',
    image: '1109.jpg',
    sound: '1109.mp3',
    bookNumber: 1,
    id: 1109,
    uz: 'amal qilmoq  ortidan bormoq',
    uzOptions: [
      'amal qilmoq  ortidan bormoq',
      "qo'ymoq  o'rnatmoq",
      'jiddiy',
      'mamnun',
    ],
    enOptions: ['follow', 'difference', 'cloud', 'creature'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'fright',
    pron: '[frʌɪt] n.',
    desc: 'Fright is the feeling of being scared.',
    exam: 'She was filled with <strong>fright</strong>.',
    vi: '',
    image: '1110.jpg',
    sound: '1110.mp3',
    bookNumber: 1,
    id: 1110,
    uz: "qo'rquv",
    uzOptions: ["qo'rquv", 'aqliy', 'hali ham', 'ichida'],
    enOptions: ['fright', 'propose', 'excite', 'save'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'ghost',
    pron: '[ɡəʊst] n.',
    desc: 'A ghost is the spirit of a dead person.',
    exam: 'Many people are afraid of <strong>ghosts</strong>.',
    vi: '',
    image: '1111.jpg',
    sound: '1111.mp3',
    bookNumber: 1,
    id: 1111,
    uz: 'arvoh',
    uzOptions: [
      'arvoh',
      'kirmoq',
      "davolamoq  munosabatda bo'lmoq",
      'chiqindi',
    ],
    enOptions: ['ghost', 'common', 'moment', 'material'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'individual',
    pron: '[ɪndɪˈvɪdjʊ(ə)l] n.',
    desc: 'An individual is one person.',
    exam: 'Only one <strong>individual </strong>could win the bicycle race.',
    vi: '',
    image: '1112.jpg',
    sound: '1112.mp3',
    bookNumber: 1,
    id: 1112,
    uz: 'shaxs',
    uzOptions: ['shaxs', 'miya', 'reja', 'operatsiya'],
    enOptions: ['individual', 'mail', 'view', 'afraid'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'pet',
    pron: '[pɛt] n.',
    desc: 'A pet is an animal that lives with people.',
    exam: 'Out of all my <strong>pets</strong>, the dog is my favorite.',
    vi: '',
    image: '1113.jpg',
    sound: '1113.mp3',
    bookNumber: 1,
    id: 1113,
    uz: 'uy hayvoni',
    uzOptions: ['uy hayvoni', 'mashhur', 'sinoat', "lug'at"],
    enOptions: ['pet', 'fair', 'error', 'else'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'reach',
    pron: '[riːtʃ] v.',
    desc: 'To reach means to arrive at a place.',
    exam: 'I was happy to finally <strong>reach </strong>my destination.',
    vi: '',
    image: '1114.jpg',
    sound: '1114.mp3',
    bookNumber: 1,
    id: 1114,
    uz: 'erishmoq  yetib bormoq',
    uzOptions: [
      'erishmoq  yetib bormoq',
      'holat',
      'kulmoq',
      "yolg'on gapirmoq",
    ],
    enOptions: ['reach', 'social', 'either', 'proud'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'return',
    pron: '[rɪˈtəːn] v.',
    desc: 'To return is to go back to a place.',
    exam: 'I was happy to <strong>return </strong>home to my mom after school.',
    vi: '',
    image: '1115.jpg',
    sound: '1115.mp3',
    bookNumber: 1,
    id: 1115,
    uz: 'qaytmoq',
    uzOptions: ['qaytmoq', 'hayqiriq', 'suyak', "o'g'irlamoq"],
    enOptions: ['return', 'international', 'average', 'moment'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'survive',
    pron: '[səˈvʌɪv] v.',
    desc: 'To survive is to stay alive.',
    exam: 'My dog <strong>survived </strong>her fall into the water.',
    vi: '',
    image: '1116.jpg',
    sound: '1116.mp3',
    bookNumber: 1,
    id: 1116,
    uz: 'omon qolmoq',
    uzOptions: ['omon qolmoq', 'tanishtirmoq', 'qadrlamoq', 'shaxsiyat'],
    enOptions: ['survive', 'flat', 'board', 'suddenly'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'upset',
    pron: '[ʌpsɛt] adj.',
    desc: 'To be upset is to be unhappy about something.',
    exam: 'She was <strong>upset </strong>because she broke her toy.',
    vi: '',
    image: '1117.jpg',
    sound: '1117.mp3',
    bookNumber: 1,
    id: 1117,
    uz: 'xafa',
    uzOptions: ['xafa', 'xulosa', 'professor', "to'lqin"],
    enOptions: ['upset', 'damage', 'alien', 'recommend'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'voice',
    pron: '[vɔɪs] n.',
    desc: 'A voice is the sound a person makes when they talk or sing.',
    exam: 'He used a microphone, so everyone could hear his <strong>voice</strong>.',
    vi: '',
    image: '1118.jpg',
    sound: '1118.mp3',
    bookNumber: 1,
    id: 1118,
    uz: 'ovoz',
    uzOptions: ['ovoz', 'halollik', 'oriq', 'okean'],
    enOptions: ['voice', 'glad', 'skill', 'shoot'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'weather',
    pron: '[ˈwɛðə:r] n.',
    desc: 'The weather is the condition of the air: hot, rainy, windy, etc.',
    exam: 'The <strong>weather </strong>can be sunny, rainy, or cold.',
    vi: '',
    image: '1119.jpg',
    sound: '1119.mp3',
    bookNumber: 1,
    id: 1119,
    uz: 'ob-havo',
    uzOptions: ['ob-havo', 'bekor qilmoq', 'hissiyot', 'orasida'],
    enOptions: ['weather', 'major', 'lay', 'exercise'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
  {
    en: 'wise',
    pron: '[wʌɪz] adj.',
    desc: 'To be wise is to use experience and intelligence to make good choices.',
    exam: 'Many people believe that owls are very <strong>wise </strong>animals.',
    vi: '',
    image: '1120.jpg',
    sound: '1120.mp3',
    bookNumber: 1,
    id: 1120,
    uz: 'dono',
    uzOptions: ['dono', 'shovqin', 'sayt  joy', 'aks holda'],
    enOptions: ['wise', 'store', 'trick', 'advance'],
    answerIndex: 0,
    unitNumber: 6,
    quizNumber: 2,
  },
];


