// **Question-13**
// *tayyor*
// # 1: Yuqoridagi hammat testlar (jami 460)
'use strick';
// Array of Object;
const quiz = [
  {
    en: 'benefit',
    pron: '[ˈbɛnɪfɪt] n.',
    desc: 'A benefit is a good thing.',
    exam: 'Being able to fly is a good <strong>benefit </strong>to birds.',
    vi: '',
    image: '1181.jpg',
    sound: '1181.mp3',
    bookNumber: 1,
    id: 1181,
    uz: 'foyda',
    uzOptions: ['foyda', 'imkoniyat', 'nazariya', 'maqsad'],
    enOptions: ['benefit', 'attitude', 'middle', 'century'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'certain',
    pron: '[ˈsəːt(ə)n] adj.',
    desc: 'If you are certain about something, you know it is true.',
    exam: 'I am <strong>certain </strong>that zebras have stripes.',
    vi: '',
    image: '1182.jpg',
    sound: '1182.mp3',
    bookNumber: 1,
    id: 1182,
    uz: 'aniq',
    uzOptions: ['aniq', 'oldini olmoq  saqlanmoq', 'yonida', 'sabzavot'],
    enOptions: ['certain', 'rock', 'conclusion', 'content'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'chance',
    pron: '[tʃɑːns] n.',
    desc: 'A chance is an opportunity to do something.',
    exam: 'I had a <strong>chance </strong>to see the Roman Coliseum last summer.',
    vi: '',
    image: '1183.jpg',
    sound: '1183.mp3',
    bookNumber: 1,
    id: 1183,
    uz: 'imkoniyat',
    uzOptions: ['imkoniyat', 'turli', "to'g'ri", 'varoq'],
    enOptions: ['chance', 'vote', 'customer', 'spread'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'effect',
    pron: '[ɪˈfɛkt] n.',
    desc: 'An effect is a change made by something else.',
    exam: 'The medicine had a good <strong>effect </strong>on the boy.',
    vi: '',
    image: '1184.jpg',
    sound: '1184.mp3',
    bookNumber: 1,
    id: 1184,
    uz: "ta'sir",
    uzOptions: ["ta'sir", 'misol', "yo'l ko'rsatuvchi", "yo'lak"],
    enOptions: ['effect', 'arrive', 'coast', 'consume'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'essential',
    pron: '[ɪˈsɛnʃ(ə)l] adj.',
    desc: 'If something is essential, it is very important and necessary.',
    exam: 'It is <strong>essential </strong>to have oxygen when you scuba dive.',
    vi: '',
    image: '1185.jpg',
    sound: '1185.mp3',
    bookNumber: 1,
    id: 1185,
    uz: 'muhim',
    uzOptions: ['muhim', 'asbob', "to'g'ri", 'uzunlik'],
    enOptions: ['essential', 'attract', 'mix', 'divide'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'far',
    pron: '[fɑ:r] adj.',
    desc: 'If something is far, it is not close.',
    exam: 'It&rsquo;s <strong>far </strong>going from the east coast to the west coast of America.',
    vi: '',
    image: '1186.jpg',
    sound: '1186.mp3',
    bookNumber: 1,
    id: 1186,
    uz: 'uzoq',
    uzOptions: ['uzoq', 'qabul qilmoq', 'orqasida', 'xalqaro'],
    enOptions: ['far', 'refuse', 'personality', 'conclusion'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'focus',
    pron: '[ˈfəʊkəs] v.',
    desc: 'To focus on something is to think about it and pay attention to it.',
    exam: 'My mom always helps me to <strong>focus </strong>on my school work.',
    vi: '',
    image: '1187.jpg',
    sound: '1187.mp3',
    bookNumber: 1,
    id: 1187,
    uz: 'diqqat markazi',
    uzOptions: ['diqqat markazi', 'ehtimol', "ta'm  tatib ko'rmoq", 'sir'],
    enOptions: ['focus', 'image', 'property', 'voice'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'function',
    pron: '[ˈfʌŋ(k)ʃ(ə)n] n.',
    desc: 'The function of something is what it does.',
    exam: 'The <strong>function </strong>of a flashlight is to help you see in the dark.',
    vi: '',
    image: '1188.jpg',
    sound: '1188.mp3',
    bookNumber: 1,
    id: 1188,
    uz: 'vazifa',
    uzOptions: ['vazifa', "ko'lmak", 'jazolamoq', 'okean'],
    enOptions: ['function', 'none', 'conversation', 'single'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'grass',
    pron: '[ɡrɑːs] n.',
    desc: 'Grass is the green leaves that cover the ground.',
    exam: 'The <strong>grass </strong>looked so soft and green.',
    vi: '',
    image: '1189.jpg',
    sound: '1189.mp3',
    bookNumber: 1,
    id: 1189,
    uz: "o't",
    uzOptions: ["o't", 'ajoyib', 'darhol', 'sovrin'],
    enOptions: ['grass', 'support', 'crowd', 'boring'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'guard',
    pron: '[ɡɑːd] v.',
    desc: 'To guard something is to take care of it.',
    exam: 'The police officer will <strong>guard </strong>us from any harm.',
    vi: '',
    image: '1190.jpg',
    sound: '1190.mp3',
    bookNumber: 1,
    id: 1190,
    uz: "qo'riqchi",
    uzOptions: ["qo'riqchi", 'professor', 'zarar', 'dolzarb  haqiqiy'],
    enOptions: ['guard', 'professional', 'competition', 'control'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'image',
    pron: '[ˈɪmɪdʒ] v.',
    desc: 'The image of something is a picture of it.',
    exam: 'The <strong>image </strong>of her eye was very clear.',
    vi: '',
    image: '1191.jpg',
    sound: '1191.mp3',
    bookNumber: 1,
    id: 1191,
    uz: 'rasm',
    uzOptions: ['rasm', 'javob bermoq', 'sir', 'rad qilmoq'],
    enOptions: ['image', 'accept', 'entertain', 'event'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'immediate',
    pron: '[iˈmiːdiət] adj.',
    desc: 'If something is immediate, it happens quickly.',
    exam: 'An <strong>immediate </strong>response came from the pizza place.',
    vi: '',
    image: '1192.jpg',
    sound: '1192.mp3',
    bookNumber: 1,
    id: 1192,
    uz: 'darhol',
    uzOptions: ['darhol', 'taxta', 'kuzatmoq', 'boshqaruv'],
    enOptions: ['immediate', 'argue', 'arrive', 'skill'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'primary',
    pron: '[ˈprʌɪm(ə)ri] adj.',
    desc: 'If something is primary, it is the most important thing.',
    exam: 'His <strong>primary </strong>thoughts are about money.',
    vi: '',
    image: '1193.jpg',
    sound: '1193.mp3',
    bookNumber: 1,
    id: 1193,
    uz: 'asosiy',
    uzOptions: ['asosiy', 'shafqatsiz', "zo'rg'a", 'ekin'],
    enOptions: ['primary', 'island', 'professional', 'perform'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'proud',
    pron: '[praʊd] adj.',
    desc: 'If someone feels proud, they are happy about what they have done.',
    exam: 'She is <strong>proud </strong>of the picture she drew of her house.',
    vi: '',
    image: '1194.jpg',
    sound: '1194.mp3',
    bookNumber: 1,
    id: 1194,
    uz: "mag'rur",
    uzOptions: ["mag'rur", 'javob bermoq', 'oqim', 'irq'],
    enOptions: ['proud', 'prize', 'gift', 'attract'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'remain',
    pron: '[rɪˈmeɪn] v.',
    desc: 'To remain somewhere is to stay there.',
    exam: 'My sister had to <strong>remain </strong>home since she was sick.',
    vi: '',
    image: '1195.jpg',
    sound: '1195.mp3',
    bookNumber: 1,
    id: 1195,
    uz: 'qolmoq',
    uzOptions: ['qolmoq', 'operatsiya', 'asramoq', 'qahramon'],
    enOptions: ['remain', 'correct', 'imply', 'function'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'rest',
    pron: '[rɛst] v.',
    desc: 'To rest is to stop being active while the body gets back its strength.',
    exam: 'I <strong>rested </strong>on the couch after work.',
    vi: '',
    image: '1196.jpg',
    sound: '1196.mp3',
    bookNumber: 1,
    id: 1196,
    uz: 'dam olmoq  qolgan',
    uzOptions: ['dam olmoq  qolgan', 'ijro etmoq', 'allaqachon', 'samimiy'],
    enOptions: ['rest', 'none', 'toward', 'fright'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'separate',
    pron: '[ˈsepəreit] v.',
    desc: 'If two things are separate, they are not together.',
    exam: 'New York and Los Angeles are in two <strong>separate </strong>parts of America.',
    vi: '',
    image: '1197.jpg',
    sound: '1197.mp3',
    bookNumber: 1,
    id: 1197,
    uz: 'alohida',
    uzOptions: ['alohida', "bo'lim", "bo'lak", 'turli'],
    enOptions: ['separate', 'alone', 'within', 'contain'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'site',
    pron: '[saɪt] n.',
    desc: 'A site is a place.',
    exam: 'We found the perfect <strong>site </strong>for our picnic.',
    vi: '',
    image: '1198.jpg',
    sound: '1198.mp3',
    bookNumber: 1,
    id: 1198,
    uz: 'sayt  joy',
    uzOptions: ['sayt  joy', 'isbotlamoq', 'yashirmoq', 'zaryadlash'],
    enOptions: ['site', 'benefit', 'frequently', 'feed'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'tail',
    pron: '[teɪl] n.',
    desc: 'A tail is a part of an animal’s body, sticking out from its rear or back.',
    exam: 'Our dog wags its <strong>tail </strong>when it&rsquo;s happy.',
    vi: '',
    image: '1199.jpg',
    sound: '1199.mp3',
    bookNumber: 1,
    id: 1199,
    uz: 'dum',
    uzOptions: ['dum', 'birlashtirmoq', "rozi bo'lmoq", "o'rniga"],
    enOptions: ['tail', 'inside', 'describe', 'judge'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'trouble',
    pron: '[ˈtrʌbəl] n.',
    desc: 'Trouble is a problem ora difficulty.',
    exam: 'I have <strong>trouble </strong>working with my boss.',
    vi: '',
    image: '1200.jpg',
    sound: '1200.mp3',
    bookNumber: 1,
    id: 1200,
    uz: 'muammo',
    uzOptions: ['muammo', 'siyosat', 'xotira', 'yomonlik'],
    enOptions: ['trouble', 'attack', 'produce', 'amaze'],
    answerIndex: 0,
    unitNumber: 10,
    quizNumber: 4,
  },
  {
    en: 'anymore',
    pron: '[ēnimɔ:r] adv.',
    desc: 'Anymore means any longer.',
    exam: 'Her old pants don&rsquo;t fit her <strong>anymore</strong>.',
    vi: '',
    image: '1201.jpg',
    sound: '1201.mp3',
    bookNumber: 1,
    id: 1201,
    uz: 'endi  qaytib',
    uzOptions: ['endi  qaytib', "o't", 'vazifa', 'xususiyat'],
    enOptions: ['anymore', 'theory', 'cool', 'dictionary'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'asleep',
    pron: '[əˈsliːp] adj.',
    desc: 'When a person is asleep, they are not awake.',
    exam: 'The baby has been <strong>asleep </strong>for hours.',
    vi: '',
    image: '1202.jpg',
    sound: '1202.mp3',
    bookNumber: 1,
    id: 1202,
    uz: 'uyquda',
    uzOptions: ['uyquda', "qo'ymoq  o'rnatmoq", "bo'lak", 'boqmoq'],
    enOptions: ['asleep', 'pound', 'pain', 'dish'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'berry',
    pron: '[ˈbɛrɪ] n.',
    desc: 'A berry is a small round fruit that grows on certain plants and trees.',
    exam: 'The <strong>berry </strong>looked delicious.',
    vi: '',
    image: '1203.jpg',
    sound: '1203.mp3',
    bookNumber: 1,
    id: 1203,
    uz: 'maymunjon',
    uzOptions: ['maymunjon', 'oqim', 'umumiy', 'harakat'],
    enOptions: ['berry', 'shake', 'independent', 'band'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'collect',
    pron: '[kəˈlɛkt] v.',
    desc: 'To collect things is to group them together all in one place.',
    exam: 'I <strong>collected </strong>shells when I was younger.',
    vi: '',
    image: '1204.jpg',
    sound: '1204.mp3',
    bookNumber: 1,
    id: 1204,
    uz: "to'plamoq",
    uzOptions: ["to'plamoq", "qo'shni", 'tagi  osti', 'muvozanat'],
    enOptions: ['collect', 'therefore', 'contrast', 'boring'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'compete',
    pron: '[kəmˈpiːt] v.',
    desc: 'To compete is to try to be better than someone.',
    exam: 'He will <strong>compete </strong>with very good athletes.',
    vi: '',
    image: '1205.jpg',
    sound: '1205.mp3',
    bookNumber: 1,
    id: 1205,
    uz: 'raqobatlashmoq',
    uzOptions: [
      'raqobatlashmoq',
      'aralashtirmoq',
      "qirg'oq",
      'muvaffaqiyatsizlikka uchramoq',
    ],
    enOptions: ['compete', 'glad', 'realize', 'outline'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'conversation',
    pron: '[kɒnvəˈseɪʃ(ə)n] n.',
    desc: 'A conversation is a talk between people.',
    exam: 'There were two <strong>conversations </strong>going on at once.',
    vi: '',
    image: '1206.jpg',
    sound: '1206.mp3',
    bookNumber: 1,
    id: 1206,
    uz: 'suhbat',
    uzOptions: ['suhbat', "e'tiqod", 'tanlov', 'tez-tez'],
    enOptions: ['conversation', 'prove', 'direct', 'value'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'creature',
    pron: '[ˈkriːtʃə] n.',
    desc: 'A creature is any living thing.',
    exam: 'The <strong>creature </strong>we saw today was either a dolphin or a porpoise.',
    vi: '',
    image: '1207.jpg',
    sound: '1207.mp3',
    bookNumber: 1,
    id: 1207,
    uz: 'jonzot',
    uzOptions: ['jonzot', 'diqqat', 'saqlamoq', 'faraz qilmoq'],
    enOptions: ['creature', 'skill', 'own', 'solution'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'decision',
    pron: '[dɪˈsɪʒ(ə)n] n.',
    desc: 'A decision is a choice.',
    exam: 'He made the wrong <strong>decision</strong>.',
    vi: '',
    image: '1208.jpg',
    sound: '1208.mp3',
    bookNumber: 1,
    id: 1208,
    uz: 'qaror',
    uzOptions: ['qaror', 'murabbiy', 'sehrli', 'yurist'],
    enOptions: ['decision', 'whole', 'rare', 'else'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'either',
    pron: '[ˈiːðə] conj.',
    desc: 'Either is used with “or” to say there are two or more possibilities.',
    exam: 'You can choose to be <strong>either </strong>white or black when you play chess.',
    vi: '',
    image: '1209.jpg',
    sound: '1209.mp3',
    bookNumber: 1,
    id: 1209,
    uz: 'yoki',
    uzOptions: ['yoki', 'yaxshi', "do'stona", 'hujayra  panjara'],
    enOptions: ['either', 'propose', 'divide', 'county'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'forest',
    pron: '[ˈfɒrɪst] n.',
    desc: 'A forest is a place with lots of trees and animals.',
    exam: 'I love to go walking in the <strong>forest</strong>.',
    vi: '',
    image: '1210.jpg',
    sound: '1210.mp3',
    bookNumber: 1,
    id: 1210,
    uz: "o'rmon",
    uzOptions: ["o'rmon", 'otmoq', 'halollik', 'yer'],
    enOptions: ['forest', 'glad', 'sight', 'include'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'ground',
    pron: '[ɡraʊnd] n.',
    desc: 'The ground is the top part of the Earth that we walk on.',
    exam: 'The <strong>ground </strong>under our feet was dry and brown.',
    vi: '',
    image: '1211.jpg',
    sound: '1211.mp3',
    bookNumber: 1,
    id: 1211,
    uz: 'yer',
    uzOptions: ['yer', 'tasavvur qilmoq', 'graflik', 'omon qolmoq'],
    enOptions: ['ground', 'fix', 'bit', 'prove'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'introduce',
    pron: '[intrəˈdjuːs] v.',
    desc: 'To introduce someone or something is to say who they are.',
    exam: 'I <strong>introduced </strong>myself to our newest co-worker today.',
    vi: '',
    image: '1212.jpg',
    sound: '1212.mp3',
    bookNumber: 1,
    id: 1212,
    uz: 'tanishtirmoq',
    uzOptions: ['tanishtirmoq', 'yorqin', 'qiyinchilik', "ko'rsatma bermoq"],
    enOptions: ['introduce', 'accept', 'lawyer', 'within'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'marry',
    pron: '[ˈmari] v.',
    desc: 'To marry is to legally become husband and wife.',
    exam: 'Rose and Henry were <strong>married</strong>, and they lived happily.',
    vi: '',
    image: '1213.jpg',
    sound: '1213.mp3',
    bookNumber: 1,
    id: 1213,
    uz: 'turmush qurmoq',
    uzOptions: ['turmush qurmoq', 'kimyoviy', 'yaratmoq', 'shuning uchun'],
    enOptions: ['marry', 'toward', 'neighbor', 'however'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'prepare',
    pron: '[prɪˈpɛə] v.',
    desc: 'To prepare is to get ready for something.',
    exam: 'I <strong>prepared </strong>my speech to the class.',
    vi: '',
    image: '1214.jpg',
    sound: '1214.mp3',
    bookNumber: 1,
    id: 1214,
    uz: 'tayyorlamoq',
    uzOptions: ['tayyorlamoq', "yo'lak", "ta'sir", "ko'nglini ko'tarmoq"],
    enOptions: ['prepare', 'beat', 'idiom', 'message'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'sail',
    pron: '[seɪl] v.',
    desc: 'To sail is to move a boat on the water.',
    exam: 'I love to <strong>sail </strong>my boat on the lake.',
    vi: '',
    image: '1215.jpg',
    sound: '1215.mp3',
    bookNumber: 1,
    id: 1215,
    uz: 'suzmoq',
    uzOptions: ['suzmoq', 'markaz', 'tosh', 'sayyora'],
    enOptions: ['sail', 'period', 'instruct', 'frequently'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'serious',
    pron: '[ˈsɪərɪəs] adj.',
    desc: 'When something is serious, it is bad or unsafe.',
    exam: 'The accident was very <strong>serious</strong>.',
    vi: '',
    image: '1216.jpg',
    sound: '1216.mp3',
    bookNumber: 1,
    id: 1216,
    uz: 'jiddiy',
    uzOptions: ['jiddiy', 'mavjud', 'chegara', 'bosib chiqarmoq'],
    enOptions: ['serious', 'calm', 'behind', 'protect'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'spend',
    pron: '[spɛnd] v.',
    desc: 'To spend is to use time doing something or being somewhere.',
    exam: 'I like to <strong>spend </strong>my free time fishing.',
    vi: '',
    image: '1217.jpg',
    sound: '1217.mp3',
    bookNumber: 1,
    id: 1217,
    uz: 'sarflamoq',
    uzOptions: ['sarflamoq', 'qarzdor', 'javob bermoq', 'vazifa'],
    enOptions: ['spend', 'rock', 'drop', 'opposite'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'strange',
    pron: '[streɪn(d)ʒ] adj.',
    desc: 'When something is strange, it is not normal.',
    exam: 'Joe had a <strong>strange </strong>look on his face after he saw what happened.',
    vi: '',
    image: '1218.jpg',
    sound: '1218.mp3',
    bookNumber: 1,
    id: 1218,
    uz: "g'alati",
    uzOptions: ["g'alati", 'bosim', "o'zini tutmoq", 'ovlamoq'],
    enOptions: ['strange', 'product', 'stage', 'approach'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'truth',
    pron: '[truːθ] n.',
    desc: 'The truth is a fact or something that is right.',
    exam: 'He was telling the <strong>truth </strong>about seeing a large green snake.',
    vi: '',
    image: '1219.jpg',
    sound: '1219.mp3',
    bookNumber: 1,
    id: 1219,
    uz: 'haqiqat',
    uzOptions: ['haqiqat', 'erishmoq', 'ajoyib', "o'rgimchak to'ri"],
    enOptions: ['truth', 'celebrate', 'behind', 'choice'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'wake',
    pron: '[weɪk] v.',
    desc: 'To wake is to not be sleeping anymore.',
    exam: 'He is always full of energy when he <strong>wakes </strong>in the morning.',
    vi: '',
    image: '1220.jpg',
    sound: '1220.mp3',
    bookNumber: 1,
    id: 1220,
    uz: "uyg'otmoq",
    uzOptions: ["uyg'otmoq", 'misol', "do'stlik", 'zarur'],
    enOptions: ['wake', 'proper', 'mean', 'block'],
    answerIndex: 0,
    unitNumber: 11,
    quizNumber: 4,
  },
  {
    en: 'alone',
    pron: '[əˈləʊn] adj.',
    desc: 'If someone is alone, they are not with another person.',
    exam: 'The boy wanted to be <strong>alone </strong>to think.',
    vi: '',
    image: '1221.jpg',
    sound: '1221.mp3',
    bookNumber: 1,
    id: 1221,
    uz: "yolg'iz",
    uzOptions: ["yolg'iz", "paydo bo'ladi", 'hujayra  panjara', 'qon'],
    enOptions: ['alone', 'bottom', 'fortunate', 'foreign'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'apartment',
    pron: '[əˈpaːtmənt] n.',
    desc: 'An apartment is a set of rooms in a building where people live.',
    exam: 'She has a nice <strong>apartment </strong>in the city.',
    vi: '',
    image: '1222.jpg',
    sound: '1222.mp3',
    bookNumber: 1,
    id: 1222,
    uz: 'xonadon',
    uzOptions: ['xonadon', 'uslub', 'uchramoq', 'tuzatmoq'],
    enOptions: ['apartment', 'examine', 'step', 'proper'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'article',
    pron: '[ˈaːtikl] n.',
    desc: 'An article is a story in a newspaper or magazine.',
    exam: 'Did you read the <strong>article </strong>in the newspaper about the soccer game?',
    vi: '',
    image: '1223.jpg',
    sound: '1223.mp3',
    bookNumber: 1,
    id: 1223,
    uz: 'maqola',
    uzOptions: ['maqola', 'vazifa', 'qarshi', 'tosh'],
    enOptions: ['article', 'passage', 'produce', 'pleasant'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'artist',
    pron: '[ˈɑːtɪst] n.',
    desc: 'An artist is a person who paints, draws, or makes sculptures.',
    exam: 'He went to Paris to become an <strong>artist</strong>.',
    vi: '',
    image: '1224.jpg',
    sound: '1224.mp3',
    bookNumber: 1,
    id: 1224,
    uz: 'rassom',
    uzOptions: ['rassom', 'mamnun', "so'ramoq", 'sabzavot'],
    enOptions: ['artist', 'speech', 'taste', 'support'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'attitude',
    pron: '[ˈӕtitjuːd] n.',
    desc: 'Someone’s attitude is the way they feel and think.',
    exam: 'John has a bad <strong>attitude</strong>. He&rsquo;s always angry.',
    vi: '',
    image: '1225.jpg',
    sound: '1225.mp3',
    bookNumber: 1,
    id: 1225,
    uz: 'munosabat',
    uzOptions: ['munosabat', 'rassom', 'reklama qilmoq', "afzal ko'rmoq"],
    enOptions: ['attitude', 'behavior', 'still', 'village'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'compare',
    pron: '[kəmˈpɛː] v.',
    desc: 'To compare means to say how two things are the same and different.',
    exam: 'If you <strong>compare </strong>cats and dogs, you&rsquo;ll see that they&rsquo;re both good pets.',
    vi: '',
    image: '1226.jpg',
    sound: '1226.mp3',
    bookNumber: 1,
    id: 1226,
    uz: 'solishtirmoq',
    uzOptions: [
      'solishtirmoq',
      "to'g'ridan-to'g'ri",
      "sovg'a",
      "do'kon  saqlamoq",
    ],
    enOptions: ['compare', 'imagine', 'match', 'steal'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'judge',
    pron: '[dʒʌdʒ] v.',
    desc: 'To judge something is to say if it is good or bad.',
    exam: 'The boy was going to <strong>judge </strong>how his mother&rsquo;s turkey tasted.',
    vi: '',
    image: '1227.jpg',
    sound: '1227.mp3',
    bookNumber: 1,
    id: 1227,
    uz: 'hukm qilmoq',
    uzOptions: [
      'hukm qilmoq',
      'bezovta qilmoq',
      'ishlab chiqarmoq',
      'hatti-harakat',
    ],
    enOptions: ['judge', 'basic', 'band', 'public'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'magazine',
    pron: '[maɡəˈziːn] n.',
    desc: 'A magazine is a regular publication with news, stories, and articles.',
    exam: 'She likes to read fashion <strong>magazines</strong>.',
    vi: '',
    image: '1228.jpg',
    sound: '1228.mp3',
    bookNumber: 1,
    id: 1228,
    uz: 'jurnal',
    uzOptions: ['jurnal', "qo'rqitmoq", 'lord', 'oldinga'],
    enOptions: ['magazine', 'universe', 'difference', 'breakfast'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'material',
    pron: '[məˈtɪərɪəl] n.',
    desc: 'A material is what is used to make something.',
    exam: 'Brick is a good <strong>material </strong>for building houses.',
    vi: '',
    image: '1229.jpg',
    sound: '1229.mp3',
    bookNumber: 1,
    id: 1229,
    uz: 'ashyo',
    uzOptions: ['ashyo', 'uzoq', "yog'och", "ko'tarilmoq"],
    enOptions: ['material', 'exam', 'clerk', 'trash'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'meal',
    pron: '[miːl] n.',
    desc: 'A meal is a time when food is eaten like breakfast, lunch, or dinner.',
    exam: 'Breakfast is my favorite <strong>meal </strong>because I enjoy breakfast foods.',
    vi: '',
    image: '1230.jpg',
    sound: '1230.mp3',
    bookNumber: 1,
    id: 1230,
    uz: 'ovqat',
    uzOptions: ['ovqat', 'ehtimol', "o'rmon", 'allaqachon'],
    enOptions: ['meal', 'attitude', 'hill', 'task'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'method',
    pron: '[ˈmɛθəd] n.',
    desc: 'A method is the way to do something.',
    exam: 'One <strong>method </strong>to remember things is to tie a string around your finger.',
    vi: '',
    image: '1231.jpg',
    sound: '1231.mp3',
    bookNumber: 1,
    id: 1231,
    uz: 'uslub',
    uzOptions: ['uslub', "qo'riqchi", 'hayratlantirmoq', 'muvozanat'],
    enOptions: ['method', 'notice', 'amaze', 'involve'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'neighbor',
    pron: '[ˈneɪ bər] n.',
    desc: 'A neighbor is a person who lives near you.',
    exam: 'I like my <strong>neighbor </strong>because he&rsquo;s very friendly.',
    vi: '',
    image: '1232.jpg',
    sound: '1232.mp3',
    bookNumber: 1,
    id: 1232,
    uz: "qo'shni",
    uzOptions: ["qo'shni", "do'stona", "ega bo'lmoq", "o'rta"],
    enOptions: ['neighbor', 'mean', 'announce', 'empty'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'professional',
    pron: '[prəˈfɛʃ(ə)n(ə)l] adj.',
    desc: 'If something is professional, it deals with work that uses special skills.',
    exam: 'If you want to be a pilot, you must have <strong>professional </strong>training.',
    vi: '',
    image: '1233.jpg',
    sound: '1233.mp3',
    bookNumber: 1,
    id: 1233,
    uz: 'professional',
    uzOptions: ['professional', "bo'ron", 'jarayon', 'tomonga'],
    enOptions: ['professional', 'chart', 'positive', 'return'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'profit',
    pron: '[ˈprɒfɪt] n.',
    desc: 'A profit is the extra money you make when you sell something.',
    exam: 'I made a small <strong>profit </strong>from selling my old clothes.',
    vi: '',
    image: '1234.jpg',
    sound: '1234.mp3',
    bookNumber: 1,
    id: 1234,
    uz: 'foyda',
    uzOptions: ['foyda', 'darvoza', 'xizmatchi', 'samimiy'],
    enOptions: ['profit', 'error', 'patient', 'locate'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'quality',
    pron: '[ˈkwɒlɪti] n.',
    desc: 'The quality of something is how good it is.',
    exam: 'The <strong>quality </strong>of his car is very good.',
    vi: '',
    image: '1235.jpg',
    sound: '1235.mp3',
    bookNumber: 1,
    id: 1235,
    uz: 'sifat',
    uzOptions: ['sifat', "ko'z yoshi  yirtmoq", 'oshirmoq', 'ob-havo'],
    enOptions: ['quality', 'finally', 'customer', 'steal'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'shape',
    pron: '[ʃeɪp] n.',
    desc: 'A shape is a simple form like a square or circle.',
    exam: 'The triangle is my favorite <strong>shape</strong>.',
    vi: '',
    image: '1236.jpg',
    sound: '1236.mp3',
    bookNumber: 1,
    id: 1236,
    uz: 'shakl',
    uzOptions: ['shakl', 'tagi  osti', 'erishmoq  yetib bormoq', "o'rta"],
    enOptions: ['shape', 'consider', 'return', 'bite'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'space',
    pron: '[speɪs] n.',
    desc: 'A space is an empty area.',
    exam: 'I don&rsquo;t have much <strong>space </strong>for things in my small house.',
    vi: '',
    image: '1237.jpg',
    sound: '1237.mp3',
    bookNumber: 1,
    id: 1237,
    uz: "bo'shliq",
    uzOptions: ["bo'shliq", "o'yin", "yog'och", 'xabar'],
    enOptions: ['space', 'experiment', 'excellent', 'pain'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'stair',
    pron: '[stɛː] n.',
    desc: 'Stairs are the things that are used to go up in a building.',
    exam: 'You can take the <strong>stairs </strong>to the second floor.',
    vi: '',
    image: '1238.jpg',
    sound: '1238.mp3',
    bookNumber: 1,
    id: 1238,
    uz: 'zina',
    uzOptions: ['zina', 'odat', 'vazifa', "o'ylab ko'rmoq"],
    enOptions: ['stair', 'normal', 'captain', 'probable'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'symbol',
    pron: '[ˈsɪmbəl] n.',
    desc: 'A symbol is a thing that stands for something else.',
    exam: 'This <strong>symbol </strong>tells us that we cannot smoke in this area.',
    vi: '',
    image: '1239.jpg',
    sound: '1239.mp3',
    bookNumber: 1,
    id: 1239,
    uz: 'belgi',
    uzOptions: ['belgi', "tegishli bo'lmoq", 'tanlamoq', 'ashyo'],
    enOptions: ['symbol', 'relax', 'respect', 'customer'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
  {
    en: 'thin',
    pron: '[θɪn] adj.',
    desc: 'If someone or something is thin, they are not fat.',
    exam: 'The man was <strong>thin </strong>because he didn&rsquo;t eat much.',
    vi: '',
    image: '1240.jpg',
    sound: '1240.mp3',
    bookNumber: 1,
    id: 1240,
    uz: 'oriq',
    uzOptions: ['oriq', 'tanishtirmoq', "mag'rur", 'kuymoq'],
    enOptions: ['thin', 'save', 'exam', 'result'],
    answerIndex: 0,
    unitNumber: 12,
    quizNumber: 4,
  },
];

console.log(quiz.length); // 55
console.log(quiz.length); // 55

// === in gitBash: ====
// node js/question13.js
