// **Question-13**
// *tayyor*
// # 1: Yuqoridagi hammat testlar (jami 460)
'use strick';
// Array of Object;
const quiz = [
  {
    en: 'allow',
    pron: '[əˈlaʊ] v.',
    desc: 'To allow something to happen means to let it happen.',
    exam: 'Having a ticket will <strong>allow </strong>you to enter the show.',
    vi: '',
    image: '1121.jpg',
    sound: '1121.mp3',
    bookNumber: 1,
    id: 1121,
    uz: 'ruxsat bermoq',
    uzOptions: ['ruxsat bermoq', 'aniq', 'mutaxassis', 'muhim'],
    enOptions: ['allow', 'list', 'rare', 'control'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'announce',
    pron: '[əˈnaʊns] v.',
    desc: 'To announce something is to make it known.',
    exam: 'He <strong>announced </strong>to everyone his new idea for the company.',
    vi: '',
    image: '1122.jpg',
    sound: '1122.mp3',
    bookNumber: 1,
    id: 1122,
    uz: "e'lon qilmoq",
    uzOptions: ["e'lon qilmoq", 'hayratlanmoq', "qo'shib qo'ymoq", "yo'lovchi"],
    enOptions: ['announce', 'exam', 'explore', 'laboratory'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'beside',
    pron: '[bɪˈsʌɪd] prep.',
    desc: 'When someone or something is beside you, they are next to you.',
    exam: 'The two brothers stood <strong>beside </strong>each other.',
    vi: '',
    image: '1123.jpg',
    sound: '1123.mp3',
    bookNumber: 1,
    id: 1123,
    uz: 'yonida',
    uzOptions: ['yonida', 'xato', 'nazariya', 'maymunjon'],
    enOptions: ['beside', 'face', 'meal', 'tradition'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'challenge',
    pron: '[ˈtʃalɪn(d)ʒ] n.',
    desc: 'A challenge is something difficult to complete.',
    exam: 'It was a <strong>challenge </strong>to climb to the top of the mountain.',
    vi: '',
    image: '1124.jpg',
    sound: '1124.mp3',
    bookNumber: 1,
    id: 1124,
    uz: 'qiyinchilik',
    uzOptions: ['qiyinchilik', 'reklama qilmoq', 'sehrli', 'akademiya'],
    enOptions: ['challenge', 'policy', 'receive', 'among'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'claim',
    pron: '[kleɪm] v.',
    desc: 'To claim means to say that something is true.',
    exam: 'He <strong>claimed </strong>to know why the country&rsquo;s laws were weak.',
    vi: '',
    image: '1125.jpg',
    sound: '1125.mp3',
    bookNumber: 1,
    id: 1125,
    uz: 'takidlamoq',
    uzOptions: ['takidlamoq', 'yechim', 'shoshilmoq', "an'ana"],
    enOptions: ['claim', 'factory', 'calm', 'already'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'condition',
    pron: '[kənˈdɪʃ(ə)n] n.',
    desc: 'The condition of someone or something is the state that they are in.',
    exam: 'The patient&rsquo;s <strong>condition </strong>was very good.',
    vi: '',
    image: '1126.jpg',
    sound: '1126.mp3',
    bookNumber: 1,
    id: 1126,
    uz: 'holat',
    uzOptions: ['holat', 'nazariya', 'turli', 'sababi'],
    enOptions: ['condition', 'promise', 'value', 'barely'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'contribute',
    pron: '[kənˈtrɪbjuːt] v.',
    desc: 'To contribute to something means to do something to make it successful.',
    exam: 'We decided to <strong>contribute </strong>money to the new hospital.',
    vi: '',
    image: '1127.jpg',
    sound: '1127.mp3',
    bookNumber: 1,
    id: 1127,
    uz: "hissa qo'shmoq",
    uzOptions: ["hissa qo'shmoq", 'masofa', 'halollik', 'tarqalmoq'],
    enOptions: ['contribute', 'value', 'strike', 'waste'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'difference',
    pron: '[ˈdɪf(ə)r(ə)ns] n.',
    desc: 'A difference is a way that something is not like other things.',
    exam: 'The biggest <strong>difference </strong>between the birds is the color of their feathers.',
    vi: '',
    image: '1128.jpg',
    sound: '1128.mp3',
    bookNumber: 1,
    id: 1128,
    uz: 'farq',
    uzOptions: ['farq', 'samarali', 'munosabat', 'nihoyat'],
    enOptions: ['difference', 'suggest', 'band', 'spot'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'divide',
    pron: '[dɪˈvʌɪd] v.',
    desc: 'To divide something is to make it into smaller parts.',
    exam: 'We <strong>divided </strong>the pizza.',
    vi: '',
    image: '1129.jpg',
    sound: '1129.mp3',
    bookNumber: 1,
    id: 1129,
    uz: "bo'lmoq",
    uzOptions: ["bo'lmoq", "qo'rquv", 'qochmoq', 'farovonlik'],
    enOptions: ['divide', 'set', 'scan', 'rich'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'expert',
    pron: '[ˈɛkspəːt] n.',
    desc: 'An expert is someone who is very good at doing something.',
    exam: 'The wizard was an <strong>expert </strong>at magic.',
    vi: '',
    image: '1130.jpg',
    sound: '1130.mp3',
    bookNumber: 1,
    id: 1130,
    uz: 'mutaxassis',
    uzOptions: ['mutaxassis', 'adolatsizlik', 'tayyorlamoq', "do'stlik"],
    enOptions: ['expert', 'tour', 'later', 'creature'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'famous',
    pron: '[ˈfeɪməs] adj.',
    desc: 'If someone or something is famous, they are known to many people.',
    exam: 'The Eiffel Tower in Paris is very <strong>famous</strong>.',
    vi: '',
    image: '1131.jpg',
    sound: '1131.mp3',
    bookNumber: 1,
    id: 1131,
    uz: 'mashhur',
    uzOptions: ['mashhur', 'hal qilmoq', 'bahslashmoq', 'taraqqiyot'],
    enOptions: ['famous', 'property', 'lack', 'critic'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'force',
    pron: '[fɔːs] n.',
    desc: 'Force is a person’s strength or power.',
    exam: 'He used all his <strong>force </strong>to try and open the door.',
    vi: '',
    image: '1132.jpg',
    sound: '1132.mp3',
    bookNumber: 1,
    id: 1132,
    uz: 'kuch',
    uzOptions: ['kuch', "erishmoq  ega bo'lmoq", "bo'shliq", "do'stlik"],
    enOptions: ['force', 'evidence', 'section', 'suddenly'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'harm',
    pron: '[hɑːm] n.',
    desc: 'Harm is hurt or problems caused to someone or something.',
    exam: 'A hot iron can cause great <strong>harm </strong>if you are not careful.',
    vi: '',
    image: '1133.jpg',
    sound: '1133.mp3',
    bookNumber: 1,
    id: 1133,
    uz: 'zarar',
    uzOptions: ['zarar', 'luqma  tishlamoq', "og'riq", 'javob bermoq'],
    enOptions: ['harm', 'inside', 'vegetable', 'academy'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'lay',
    pron: '[leɪ] v.',
    desc: 'To lay means to put or place in a horizontal or flat position.',
    exam: 'Don&rsquo;t <strong>lay </strong>your socks on the floor.',
    vi: '',
    image: '1134.jpg',
    sound: '1134.mp3',
    bookNumber: 1,
    id: 1134,
    uz: 'yoymoq',
    uzOptions: ['yoymoq', 'safar', 'ekin', 'qobiliyat'],
    enOptions: ['lay', 'crowd', 'effort', 'band'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'peace',
    pron: '[piːs] n.',
    desc: 'Peace is a time without war.',
    exam: 'A white dove is a symbol for <strong>peace</strong>.',
    vi: '',
    image: '1135.jpg',
    sound: '1135.mp3',
    bookNumber: 1,
    id: 1135,
    uz: 'tinchlik',
    uzOptions: ['tinchlik', 'sabrli', 'yana boshqa', 'shubha'],
    enOptions: ['peace', 'certain', 'punish', 'punish'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'prince',
    pron: '[prɪns] n.',
    desc: 'A prince is the son of a king.',
    exam: 'The <strong>prince </strong>and the princess were married.',
    vi: '',
    image: '1136.jpg',
    sound: '1136.mp3',
    bookNumber: 1,
    id: 1136,
    uz: 'shahzoda',
    uzOptions: ['shahzoda', 'xalqaro', 'taklif qilmoq', 'olam'],
    enOptions: ['prince', 'success', 'bright', 'tour'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'protect',
    pron: '[prəˈtɛkt] v.',
    desc: 'To protect someone is to stop them from getting hurt.',
    exam: 'Firemen <strong>protect </strong>us from fires.',
    vi: '',
    image: '1137.jpg',
    sound: '1137.mp3',
    bookNumber: 1,
    id: 1137,
    uz: 'himoya qilmoq',
    uzOptions: ['himoya qilmoq', "qachon bo'lsa ham", 'voqea', 'haqiqat'],
    enOptions: ['protect', 'assign', 'stroll', 'field'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'sense',
    pron: '[sɛns] v.',
    desc: 'To sense something is to know about it without being told.',
    exam: 'I could <strong>sense </strong>that he was watching me.',
    vi: '',
    image: '1138.jpg',
    sound: '1138.mp3',
    bookNumber: 1,
    id: 1138,
    uz: "ma'no",
    uzOptions: ["ma'no", "e'tiqod", "yo'lak", "ega bo'lmoq"],
    enOptions: ['sense', 'mistake', 'instrument', 'require'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'sudden',
    pron: '[ˈsʌd(ə)n] adj.',
    desc: 'When something is sudden, it happens very quickly.',
    exam: 'He felt a <strong>sudden </strong>pain in his chest.',
    vi: '',
    image: '1139.jpg',
    sound: '1139.mp3',
    bookNumber: 1,
    id: 1139,
    uz: "to'satdan",
    uzOptions: ["to'satdan", 'begona', 'asr', 'xususiyat'],
    enOptions: ['sudden', 'average', 'method', 'clever'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'therefore',
    pron: '[ˈðɛːfɔː] adv.',
    desc: 'Therefore means for this reason.',
    exam: 'He is fat. <strong>Therefore</strong>, he will go on a diet.',
    vi: '',
    image: '1140.jpg',
    sound: '1140.mp3',
    bookNumber: 1,
    id: 1140,
    uz: 'shuning uchun',
    uzOptions: ['shuning uchun', 'haddan tashqari', 'ovlamoq', 'jonzot'],
    enOptions: ['therefore', 'claim', 'challenge', 'silly'],
    answerIndex: 0,
    unitNumber: 7,
    quizNumber: 3,
  },
  {
    en: 'accept',
    pron: '[əkˈsɛpt] v.',
    desc: 'To accept something that is offered is to take it.',
    exam: 'I <strong>accepted </strong>the girl&rsquo;s very nice gift.',
    vi: '',
    image: '1141.jpg',
    sound: '1141.mp3',
    bookNumber: 1,
    id: 1141,
    uz: 'qabul qilmoq',
    uzOptions: ['qabul qilmoq', 'haddan tashqari', "o'yin", 'sotib olmoq'],
    enOptions: ['accept', 'emotion', 'waste', 'frank'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'arrange',
    pron: '[əˈreɪn(d)ʒ] v.',
    desc: 'To arrange things is to put them in the right place.',
    exam: 'Please <strong>arrange </strong>the bowling pins in order so we can play.',
    vi: '',
    image: '1142.jpg',
    sound: '1142.mp3',
    bookNumber: 1,
    id: 1142,
    uz: 'tartibga solmoq',
    uzOptions: ['tartibga solmoq', 'odat', "o'smoq", 'na'],
    enOptions: ['arrange', 'wake', 'chance', 'moment'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'attend',
    pron: '[əˈtɛnd] v.',
    desc: 'To attend something is to go to it.',
    exam: 'My sister and I <strong>attend </strong>the same school.',
    vi: '',
    image: '1143.jpg',
    sound: '1143.mp3',
    bookNumber: 1,
    id: 1143,
    uz: 'qatnashmoq',
    uzOptions: ['qatnashmoq', 'oldinga', "yolg'iz", "bo'lak"],
    enOptions: ['attend', 'associate', 'product', 'disappear'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'balance',
    pron: '[ˈbal(ə)ns] v.',
    desc: 'To balance something is to keep it from falling.',
    exam: 'We saw an elephant <strong>balance </strong>itself on a ball.',
    vi: '',
    image: '1144.jpg',
    sound: '1144.mp3',
    bookNumber: 1,
    id: 1144,
    uz: 'muvozanat',
    uzOptions: ['muvozanat', 'xususiyat', 'irq', 'tosh'],
    enOptions: ['balance', 'empty', 'berry', 'report'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'contrast',
    pron: '[kənˈtrɑːst] n',
    desc: 'A contrast is the sharp difference between two things.',
    exam: 'The <strong>contrast </strong>between my parents is very noticeable.',
    vi: '',
    image: '1145.jpg',
    sound: '1145.mp3',
    bookNumber: 1,
    id: 1145,
    uz: 'farq',
    uzOptions: ['farq', 'boylik', 'natija', 'uslub'],
    enOptions: ['contrast', 'prevent', 'pleasant', 'doubt'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'encourage',
    pron: '[ɪnˈkʌrɪdʒ] v.',
    desc: 'To encourage someone is to make them want to do something.',
    exam: 'My football coach will <strong>encourage </strong>us when we are losing.',
    vi: '',
    image: '1146.jpg',
    sound: '1146.mp3',
    bookNumber: 1,
    id: 1146,
    uz: "rag'batlantirmoq",
    uzOptions: ["rag'batlantirmoq", 'ehtimol', 'sayyora', 'muvaffaqiyat'],
    enOptions: ['encourage', 'major', 'feed', 'instead'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'familiar',
    pron: '[fəˈmɪlɪə] adj.',
    desc: 'If someone or something is familiar to you, you know them well.',
    exam: 'The two friends were very <strong>familiar </strong>with each other.',
    vi: '',
    image: '1147.jpg',
    sound: '1147.mp3',
    bookNumber: 1,
    id: 1147,
    uz: 'tanish',
    uzOptions: ['tanish', 'mamnun', 'uzoqroq', 'ahamiyat'],
    enOptions: ['familiar', 'apartment', 'vegetable', 'toward'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'grab',
    pron: '[ɡrab] v.',
    desc: 'To grab is to take a hold of someone or something suddenly.',
    exam: 'I <strong>grabbed </strong>a pear from the tree.',
    vi: '',
    image: '1148.jpg',
    sound: '1148.mp3',
    bookNumber: 1,
    id: 1148,
    uz: 'changallamoq',
    uzOptions: ['changallamoq', 'usta', "noto'g'ri", 'sabzavot'],
    enOptions: ['grab', 'pound', 'chance', 'universe'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'hang',
    pron: '[haŋ] v.',
    desc: 'To hang something is to keep it above the ground.',
    exam: 'I drew a picture of my family, and my mother <strong>hung </strong>it on the wall.',
    vi: '',
    image: '1149.jpg',
    sound: '1149.mp3',
    bookNumber: 1,
    id: 1149,
    uz: "osib qo'y",
    uzOptions: ["osib qo'y", 'xodimlar', 'jarayon', 'natija'],
    enOptions: ['hang', 'physical', 'own', 'extra'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'huge',
    pron: '[hjuːdʒ] adj.',
    desc: 'If something is huge, it is very big.',
    exam: 'At work, my father drives a <strong>huge </strong>truck.',
    vi: '',
    image: '1150.jpg',
    sound: '1150.mp3',
    bookNumber: 1,
    id: 1150,
    uz: 'katta',
    uzOptions: ['katta', 'tartibga solmoq', 'davomida', 'himoya qilmoq'],
    enOptions: ['huge', 'escape', 'trip', 'yet'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'necessary',
    pron: '[ˈnɛsəs(ə)ri] adj.',
    desc: 'If something is necessary, you must do it.',
    exam: 'It is <strong>necessary </strong>to have a passport when you travel to a foreign country.',
    vi: '',
    image: '1151.jpg',
    sound: '1151.mp3',
    bookNumber: 1,
    id: 1151,
    uz: 'zarur',
    uzOptions: ['zarur', 'na', 'uslub', 'otmoq'],
    enOptions: ['necessary', 'hero', 'scene', 'bright'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'pattern',
    pron: '[ˈpat(ə)n] n.',
    desc: 'A pattern is a way in which something is done or organized.',
    exam: 'My <strong>pattern </strong>of brushing my teeth is the same as most people&rsquo;s.',
    vi: '',
    image: '1152.jpg',
    sound: '1152.mp3',
    bookNumber: 1,
    id: 1152,
    uz: 'naqsh  tartib',
    uzOptions: ['naqsh  tartib', 'jonzot', 'yovvoyi', "o'rtacha"],
    enOptions: ['pattern', 'expert', 'produce', 'associate'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'propose',
    pron: '[prəˈpəʊz] v.',
    desc: 'To propose something is to say that it should be done.',
    exam: 'Santa Claus <strong>proposed </strong>that I try to be a good boy all year.',
    vi: '',
    image: '1153.jpg',
    sound: '1153.mp3',
    bookNumber: 1,
    id: 1153,
    uz: 'taklif qilmoq',
    uzOptions: ['taklif qilmoq', 'bir qator  tur', "qo'shib qo'ymoq", 'masofa'],
    enOptions: ['propose', 'likely', 'specific', 'protect'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'purpose',
    pron: '[ˈpəːpəs] n.',
    desc: 'A purpose is the reason that you do something.',
    exam: 'The <strong>purpose </strong>of exercising is to get into shape.',
    vi: '',
    image: '1154.jpg',
    sound: '1154.mp3',
    bookNumber: 1,
    id: 1154,
    uz: 'maqsad',
    uzOptions: ['maqsad', "qo'rquv", 'solishtirmoq', "bo'sh"],
    enOptions: ['purpose', 'sudden', 'wise', 'career'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'release',
    pron: '[rɪˈliːs] v.',
    desc: 'To release something is to stop holding it.',
    exam: 'She <strong>released </strong>the bird from her hands.',
    vi: '',
    image: '1155.jpg',
    sound: '1155.mp3',
    bookNumber: 1,
    id: 1155,
    uz: 'ozod qilmoq',
    uzOptions: ['ozod qilmoq', "o'g'irlamoq", 'muvozanat', 'boy'],
    enOptions: ['release', 'boring', 'breakfast', 'explore'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'require',
    pron: '[rɪˈkwʌɪə] v.',
    desc: 'To require something is to say that it is necessary.',
    exam: 'We <strong>require </strong>teachers to have a university degree.',
    vi: '',
    image: '1156.jpg',
    sound: '1156.mp3',
    bookNumber: 1,
    id: 1156,
    uz: 'talab qilmoq',
    uzOptions: ['talab qilmoq', 'oqim', 'ibora', 'yaqinlashmoq'],
    enOptions: ['require', 'control', 'desert', 'communicate'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'single',
    pron: '[ˈsɪŋɡ(ə)l] adj.',
    desc: 'If something is single, then there is only one.',
    exam: 'I have a <strong>single </strong>key in my hand.',
    vi: '',
    image: '1157.jpg',
    sound: '1157.mp3',
    bookNumber: 1,
    id: 1157,
    uz: 'yakka',
    uzOptions: ['yakka', 'pochta', 'ishlab topmoq', 'professional'],
    enOptions: ['single', 'wise', 'contrast', 'breathe'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'success',
    pron: '[səkˈsɛs] n.',
    desc: 'Success is doing something well that you choose to do.',
    exam: 'My daughter was a big <strong>success </strong>at school.',
    vi: '',
    image: '1158.jpg',
    sound: '1158.mp3',
    bookNumber: 1,
    id: 1158,
    uz: 'muvaffaqiyat',
    uzOptions: ['muvaffaqiyat', 'xususiyat', "a'zo", 'murabbiy'],
    enOptions: ['success', 'lot', 'clue', 'ocean'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'tear',
    pron: '[tɪə] v.',
    desc: 'To tear something means to pull it apart.',
    exam: 'It is easy to <strong>tear </strong>paper.',
    vi: '',
    image: '1159.jpg',
    sound: '1159.mp3',
    bookNumber: 1,
    id: 1159,
    uz: "ko'z yoshi  yirtmoq",
    uzOptions: ["ko'z yoshi  yirtmoq", 'yashamoq', 'xavfsizlik', 'varoq'],
    enOptions: ['tear', 'novel', 'above', 'decision'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'theory',
    pron: '[ˈθɪəri] n.',
    desc: 'A theory is an idea about how something works.',
    exam: 'We talked about Einstein&rsquo;s <strong>theory </strong>of relativity in class.',
    vi: '',
    image: '1160.jpg',
    sound: '1160.mp3',
    bookNumber: 1,
    id: 1160,
    uz: 'nazariya',
    uzOptions: ['nazariya', 'yoki', 'jamoat', 'aks holda'],
    enOptions: ['theory', 'visible', 'hide', 'breathe'],
    answerIndex: 0,
    unitNumber: 8,
    quizNumber: 3,
  },
  {
    en: 'against',
    pron: '[əˈɡeɪnst] prep.',
    desc: 'To be against something is to be touching it or opposed to it.',
    exam: 'They both leaned <strong>against </strong>the wall.',
    vi: '',
    image: '1161.jpg',
    sound: '1161.mp3',
    bookNumber: 1,
    id: 1161,
    uz: 'qarshi',
    uzOptions: ['qarshi', 'jazolamoq', 'yoki', 'yangi'],
    enOptions: ['against', 'celebrate', 'vegetable', 'hide'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'beach',
    pron: '[biːtʃ] n.',
    desc: 'The beach is a sandy or rocky place by the ocean.',
    exam: 'The little girl built a sandcastle on the <strong>beach</strong>.',
    vi: '',
    image: '1162.jpg',
    sound: '1162.mp3',
    bookNumber: 1,
    id: 1162,
    uz: 'sohil',
    uzOptions: ['sohil', 'zerikarli', 'yoki', 'murabbiy'],
    enOptions: ['beach', 'weather', 'clue', 'notice'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'damage',
    pron: '[ˈdamɪdʒ] v.',
    desc: 'To damage something is to break it.',
    exam: 'The car was <strong>damaged </strong>in the accident.',
    vi: '',
    image: '1163.jpg',
    sound: '1163.mp3',
    bookNumber: 1,
    id: 1163,
    uz: 'zarar',
    uzOptions: ['zarar', 'talab', 'davr', 'jadval'],
    enOptions: ['damage', 'theater', 'berry', 'captain'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'discover',
    pron: '[dɪˈskʌvə] v.',
    desc: 'To discover something is to find it for the first time.',
    exam: 'I <strong>discovered </strong>some new information in this book!',
    vi: '',
    image: '1164.jpg',
    sound: '1164.mp3',
    bookNumber: 1,
    id: 1164,
    uz: 'kashf qilmoq',
    uzOptions: ['kashf qilmoq', 'ulashmoq', 'standart', 'kesib'],
    enOptions: ['discover', 'thin', 'forward', 'necessary'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'emotion',
    pron: '[ɪˈməʊʃ(ə)n] n.',
    desc: 'An emotion is how you feel.',
    exam: 'Anger is a common <strong>emotion </strong>that we all feel.',
    vi: '',
    image: '1165.jpg',
    sound: '1165.mp3',
    bookNumber: 1,
    id: 1165,
    uz: 'hissiyot',
    uzOptions: ['hissiyot', 'sayrga chiqmoq', 'jalb qilmoq', "bo'sh"],
    enOptions: ['emotion', 'either', 'cruel', 'perform'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'fix',
    pron: '[fɪks] v.',
    desc: 'To fix something is to make it work.',
    exam: 'My dad has many tools to help him <strong>fix </strong>broken things.',
    vi: '',
    image: '1166.jpg',
    sound: '1166.mp3',
    bookNumber: 1,
    id: 1166,
    uz: 'tuzatmoq',
    uzOptions: ['tuzatmoq', 'uzunlik', 'xato', 'davomida'],
    enOptions: ['fix', 'explore', 'lack', 'captain'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'frank',
    pron: '[fraŋk] adj.',
    desc: 'If you are frank, you are being very honest.',
    exam: 'The teacher had a <strong>frank </strong>discussion with her students.',
    vi: '',
    image: '1167.jpg',
    sound: '1167.mp3',
    bookNumber: 1,
    id: 1167,
    uz: 'samimiy',
    uzOptions: ['samimiy', 'haqiqat', "bo'sh", "o'rgimchak to'ri"],
    enOptions: ['frank', 'laugh', 'separate', 'community'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'identify',
    pron: '[ʌɪˈdɛntɪfʌɪ] v.',
    desc: 'To identify something is to be able to name it.',
    exam: 'I used the file to <strong>identify </strong>his name.',
    vi: '',
    image: '1168.jpg',
    sound: '1168.mp3',
    bookNumber: 1,
    id: 1168,
    uz: 'aniqlash',
    uzOptions: ['aniqlash', "ta'riflamoq", 'sarguzasht', 'jentleman'],
    enOptions: ['identify', 'positive', 'remove', 'empty'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'island',
    pron: '[ˈʌɪlənd] n.',
    desc: 'An island is land in the middle of water.',
    exam: 'Japan is a group of <strong>islands</strong>.',
    vi: '',
    image: '1169.jpg',
    sound: '1169.mp3',
    bookNumber: 1,
    id: 1169,
    uz: 'orol',
    uzOptions: [
      'orol',
      "qo'ymoq  o'rnatmoq",
      'shuning uchun',
      "qachon bo'lsa ham",
    ],
    enOptions: ['island', 'whether', 'promise', 'cause'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'ocean',
    pron: '[ˈəʊʃ(ə)n] n.',
    desc: 'The ocean is all of the salt water that surrounds land.',
    exam: 'The <strong>ocean </strong>can make powerful waves.',
    vi: '',
    image: '1170.jpg',
    sound: '1170.mp3',
    bookNumber: 1,
    id: 1170,
    uz: 'okean',
    uzOptions: ['okean', 'miya', 'ishlab chiqarmoq', 'tekis'],
    enOptions: ['ocean', 'celebrate', 'deliver', 'disappear'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'perhaps',
    pron: '[pəˈhaps] adv.',
    desc: 'Perhaps is used when you say that something could happen.',
    exam: '<strong>Perhaps </strong>I will eat an apple for lunch.',
    vi: '',
    image: '1171.jpg',
    sound: '1171.mp3',
    bookNumber: 1,
    id: 1171,
    uz: 'ehtimol',
    uzOptions: ['ehtimol', 'haqiqiy', 'kamchilik', 'sovrin'],
    enOptions: ['perhaps', 'sign', 'village', 'range'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'pleasant',
    pron: '[ˈplɛz(ə)nt] adj.',
    desc: 'If something is pleasant, you enjoy it.',
    exam: 'The character had a <strong>pleasant </strong>look on its face.',
    vi: '',
    image: '1172.jpg',
    sound: '1172.mp3',
    bookNumber: 1,
    id: 1172,
    uz: 'yoqimli',
    uzOptions: ['yoqimli', "yog'och", "afzal ko'rmoq", 'endi  qaytib'],
    enOptions: ['pleasant', 'common', 'grab', 'else'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'prevent',
    pron: '[prɪˈvɛnt] v.',
    desc: 'To prevent something is to stop it from happening.',
    exam: 'The handcuffs <strong>prevented </strong>me from moving my hands.',
    vi: '',
    image: '1173.jpg',
    sound: '1173.mp3',
    bookNumber: 1,
    id: 1173,
    uz: 'oldini olmoq',
    uzOptions: ['oldini olmoq', 'uch', 'sohil', 'maymunjon'],
    enOptions: ['prevent', 'period', 'choice', 'regard'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'rock',
    pron: '[rɒk] n.',
    desc: 'A rock is a hard thing in the dirt.',
    exam: 'I stacked <strong>rocks </strong>on top of one another.',
    vi: '',
    image: '1174.jpg',
    sound: '1174.mp3',
    bookNumber: 1,
    id: 1174,
    uz: 'tosh',
    uzOptions: ['tosh', 'rasm', 'jiddiy', 'kuzatmoq'],
    enOptions: ['rock', 'gentleman', 'function', 'frank'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'save',
    pron: '[seɪv] v.',
    desc: 'To save something is to keep it from being hurt.',
    exam: 'I want to help <strong>save </strong>the world.',
    vi: '',
    image: '1175.jpg',
    sound: '1175.mp3',
    bookNumber: 1,
    id: 1175,
    uz: 'asramoq',
    uzOptions: ['asramoq', 'uslub', 'tekis', 'taklif qilmoq'],
    enOptions: ['save', 'rich', 'pain', 'bone'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'step',
    pron: '[stɛp] v.',
    desc: 'To step is to walk.',
    exam: 'Be careful where you <strong>step</strong>.',
    vi: '',
    image: '1176.jpg',
    sound: '1176.mp3',
    bookNumber: 1,
    id: 1176,
    uz: 'qadam',
    uzOptions: ['qadam', "to'plamoq", 'sohil', 'ruxsat bermoq'],
    enOptions: ['step', 'wild', 'feed', 'grab'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'still',
    pron: '[stɪl] adv.',
    desc: 'Still is used when you say that a situation keeps going on.',
    exam: 'They are <strong>still </strong>waiting in line to get tickets.',
    vi: '',
    image: '1177.jpg',
    sound: '1177.mp3',
    bookNumber: 1,
    id: 1177,
    uz: 'hali ham',
    uzOptions: ['hali ham', 'ehtimol', 'tartibga solmoq', 'sarguzasht'],
    enOptions: ['still', 'lie', 'meal', 'professional'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'taste',
    pron: '[teɪst] n.',
    desc: 'A taste is the flavor something makes in your mouth.',
    exam: 'The <strong>taste </strong>of the fruit was sweet.',
    vi: '',
    image: '1178.jpg',
    sound: '1178.mp3',
    bookNumber: 1,
    id: 1178,
    uz: "ta'm  tatib ko'rmoq",
    uzOptions: ["ta'm  tatib ko'rmoq", 'ehtimol', 'chegara', "o'g'ri"],
    enOptions: ['taste', 'later', 'success', 'propose'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'throw',
    pron: '[θrəʊ] v.',
    desc: 'To throw something is to use your hand to make it go through the air.',
    exam: 'The pitcher can <strong>throw </strong>the baseball very fast.',
    vi: '',
    image: '1179.jpg',
    sound: '1179.mp3',
    bookNumber: 1,
    id: 1179,
    uz: 'otmoq',
    uzOptions: ['otmoq', 'taxmin qilmoq', 'uslub', 'jahlda'],
    enOptions: ['throw', 'refuse', 'inform', 'harm'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
  {
    en: 'wave',
    pron: '[weɪv] n.',
    desc: 'A wave is a line of water that moves higher than the rest of the water.',
    exam: 'The water was filled with large blue <strong>waves</strong>.',
    vi: '',
    image: '1180.jpg',
    sound: '1180.mp3',
    bookNumber: 1,
    id: 1180,
    uz: "to'lqin",
    uzOptions: ["to'lqin", 'uchramoq', "erishmoq  ega bo'lmoq", 'sabrli'],
    enOptions: ['wave', 'judgment', 'responsible', 'within'],
    answerIndex: 0,
    unitNumber: 9,
    quizNumber: 3,
  },
];
console.log(quiz.length); // 55
console.log(quiz.length); // 55

// === in gitBash: ====
// node js/question13.js
